### PR TITLE
Fixed a variety of incorrect catalyst scaling

### LINKED ISSUE #3193: Replica Siegebreaker
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

Using Turbulent Catalysts in game increases the minions spread burning ground damge mod from 20% of life per second, to 24% life per second damage.  (also this probably happens with normal siegebreaker too? in PoB the chaos damage catalyst doesnt do anything and I assume that affects it in game like the replica, dont have one or the catalysts to test though.)

### What is the actual behaviour/value?

This is not supported and importing a version with the 24% from in game, or just modifying the text, completely breaks the mod, also manually putting the catalysts on a fresh one in PoB doesn't affect the mod at all, it stays at 20%.

### How to reproduce the issue

Select replica siegebreaker in pob
Turbulent Catalysts
Mod doesnt work.
or
Copy catalysted version from in game/modify text to 24% from 20%
Mod doesnt work

### Build code

```shell
https://pastebin.com/gQnbUpHm
```

### Screenshots

image
image
image

### PR DESCRIPTION
**Pull request by QuickStick123**
The current plan with this is to run https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/2662 and then fixed the last few mistakes in here detailed in https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/2662#issuecomment-1179720326.

The changes are based off some testing and work I did in 17/4/2021
So any recently changed mods or new uniques will not be guaranteed to be correct.
https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/2521#issuecomment-821748654
https://docs.google.com/spreadsheets/d/11mOp3VLPXgbhJq562DdFmP34nx4tNqoF47LbrM-R93g/edit#gid=0

Further fixes i did was fixing noxious catalyst to scale physical and chaos damage instead of generic tags.

Fixes #3193 #2843 #2521 #4482 #5614 #5688

image
image

### Description of the problem being solved:
Catalyst scaling is incorrect in a number of cases.

### Steps taken to verify a working solution:
I have verified all of these either using trade or through in game but I haven't collated documentation due to the large number of changes.

### CODE REVIEW

**Comment by Wires77** [comment]
For whoever looks at this, the tags being wrong can be fixed generically with #2662 even if we just run the scripts once to clean everything up.  I'm sure there are other uniques with the wrong tags that no one has noticed/reported

**Comment by QuickStick123** [comment]
I am down to run the script and then just cleanup the remaining few it missed/got wrong. (rare cases of unscalable values) Noxious catalyst still needs to be fixed but that could be split into a separate pull request.

**Review by LocalIdentity — APPROVED** [review]

**Comment by QuickStick123** [comment]
I want to review the mods again. Don't merge this yet.

**Comment by QuickStick123** [comment]
This is good for review again.

**Review by LocalIdentity — APPROVED** [review]

**Pull request merged**
