### PR TITLE
Cap of dot dps

### PR DESCRIPTION
**Pull request by Regisle**
initial cap, currently only for poison/ignite/bleed

### CODE REVIEW

**Comment by Nostrademous** [comment]
Can we delete: `--InsertIfNew(self.controls.warnings.lines, "Bleed dps is overcap")` instances? Just adds noise to the code.

**Comment by Regisle** [comment]
The goal was to add proper warnings because it was requested, but I didnt get around to supporting it properly

**Comment by LocalIdentity** [comment]
Builds to test PR with
Bleed - https://pobb.in/eZ-UQTL8NWrG
Ignite - https://pobb.in/J_W8XHaQRQid
Poison - https://pobb.in/RW-Oo6wB2MdG

Breakdowns now look like this
image

**Comment by LocalIdentity** [comment]
This PR caps the DPS at the very end of the calculation stage and may be incorrect is some parts as GGG have said it is capped at multiple points in the damage calculation but we don't know what these points are.
It also does not add a warning for Full DPS which is something we should definitely add

**Review by LocalIdentity — APPROVED** [review]

**Pull request merged**
