### PR TITLE
Jewel ItemSet saving/loading/swapping

### PR DESCRIPTION
**Pull request by Nostrademous**
Jewels put in Sockets below main gear now save between ItemSets. They also Save to XML builds and load from XML builds.

Only small (doesn't break anything) issue is that when you create a new set, it doesn't by default zero out the current jewels in sockets.

### CODE REVIEW

**Comment by Nostrademous** [comment]
Fixed the small issue with setting socket jewels in new itemsets to nothing.

**Comment by NickRyder** [comment]
This change seems like it has the capability to break importing/exporting - which many people have pipelines attached to.

I think we should develop a export/import test before accepting
@ppoelzl thoughts?

**Comment by Nostrademous** [comment]
I tested a bunch and they all worked. I tested adding new socket passives and removing. All worked. I agree the more testing we have the better

**Comment by ppoelzl** [comment]
Since this PR isn't critical to merge right now, I think it would be a good first candidate for automated testing.

**Pull request closed without merging**
