### PR TITLE
Add display for totem resistances in skill type specific stats

### PR DESCRIPTION
**Pull request by deathbeam**
These stats were parsed but werent displayed anywhere.

Signed-off-by: Tomas Slusny <slusnucky@gmail.com>

Example screenshot:

image

image

Example pob:

https://pastebin.com/AEuPhhym

### CODE REVIEW

**Comment by Lothrik** [comment]
Tested and works as expected. It's worth noting though that resistances from auras (Purity of Elements, etc) should probably affect totems the same way they currently affect minions.

**Comment by deathbeam** [comment]
I dont think purity of elements affect totems (or auras in general). totems inherit your offensive stats but they arent affected by auras (as this would cause offensive auras to apply to them twice).

**Comment by Regisle** [comment]
iirc totems are affected by all auras, offensive auras do nothing because they use your offensive stats, but defensive auras do help keep them alive

**Comment by deathbeam** [comment]
Oh interseting. I know I was looking for this before but also I was specifically searching for purity of elements so did not found much so I assumed its same as with offensive auras. But if i look for defensive auras in general it looks like you are right.

**Review by Wires77 — APPROVED** [review]
Even without the auras affecting the totems I think this still a useful PR to merge.  I'll open a separate bug report for adding that later if someone wants to tackle it.

**Pull request merged**
