### PR TITLE
Preselect current loadout based on currently selected tree

### PR DESCRIPTION
**Pull request by deathbeam**
Before this change the information about selected loadout in dropdown is lost on closing and reopening build. With this change it tries to match selected loadout with active tree.

### Link to a build that showcases this PR:

https://pobb.in/j3Z597YrowzK

### Before screenshot:

image

### After screenshot:

image

### CODE REVIEW

**Review by Wires77 — COMMENTED** [review]
This doesn't quite work because someone could save their build with different sets selected and this automatically forces their tree set to be the loadout for all tabs.  Having the loadout dropdown selected makes sense if they already had one selected (i.e. all their sets are the same), but maybe not otherwise

**Comment by deathbeam** [comment]
Alright updated, new testing pobbin as I had to adjust for config sets etc:

https://pobb.in/j3Z597YrowzK

**Comment by deathbeam** [comment]
Alright now it should work

**Review by Wires77 — APPROVED** [review]
This won't fill in the loadout when the tree spec has more than one loadout (e.g. {L10,L20}), but it looks like the code before wasn't doing that anyway.

**Pull request merged**
