### PR TITLE
Added Arcane Surge Buff Button in Skill Options

### PR DESCRIPTION
**Pull request by ALT-F-X**
My own solution for #2053. I essentially copied Infused Channeling's implementation.

### CODE REVIEW

**Comment by Nostrademous** [comment]
@ppoelzl @LocalIdentity - how do you guys feel about this? Either we enable the user to select this as per this PR or we take the approach of calculating when mana cost is 0 and know not to apply the Arcane Surge buff as explained in #2053 

I feel doing the mana cost 0 approach is better, but also requires more future maintenance on our part.

**Comment by ALT-F-X** [comment]
I apologize for all of the extraneous changes, I've reverted them all. I am a GitHub noob and am trying and failing to create a separate fork for another push request so my changes don't come into this request.

**Comment by Nostrademous** [comment]
go back to your `dev` branch
do a `git checkout -b <new_branch_name>` <-- this creates a new branch forked from your dev branch
check changes into that branch, then do an upstream push there

**Comment by ALT-F-X** [comment]
Thanks. I was able to get it working at #2113. To many more push requests successfully done in the future 🍹

**Comment by Wires77** [comment]
My main issue is that users are going to file a bug when they add arcane surge support and see that it doesn't do anything anymore, because there's a new config option they'd have to enable as well.  We could negate the flag, I suppose, so it's defaulted to being set, but then the checkbox will show up for everyone, when 99% of users won't need it there.

I think detecting the 0 mana cost is a better approach, personally, we have so many config options as it is.  One thing to watch out for (for whoever does that mana cost tie-in) is arcane cloak, which also costs 0 mana, but procs a fully leveled arcane surge most of the time.

**Comment by ALT-F-X** [comment]
Sure, and while I can work on this I think this might be a little out of my skillset with Lua and this project. Should make another branch and close this request?

**Comment by Wires77** [comment]
> 
> 
> Sure, and while I can work on this I think this might be a little out of my skillset with Lua and this project. Should I make another branch and close this request?

I think that's best, we can start with a clean slate then based off of #2053 (I do wish we had a workaround for that issue, though, in the meantime)

**Pull request closed without merging**
