### PR TITLE
Build Loadouts

### PR DESCRIPTION
**Pull request by Subtractem**
### Description of the problem being solved:
Currently, managing multiple sets of passive trees, items, and skill sets can be a serious pain. This is even worse for the consumer of a build guide who can easily get lost trying to juggle all the differences.

### Solution:
Loadouts!
6Q4ip7P

These are automatically generated based on identical namings of item/skills/passive trees, you can also use the dropdown option of "New Loadout" to create a new full set of all three to populate later.

The Sync option is for situations where the user mucks around with the different sets too much and wants to rerun the loadout generating function. This is preferred over triggering in the code every time one of these data sets is touched (there are a LOT of places where we'd have to insert code to listen, the code is not particularly conducive to a clean Observer without some refactoring).

There are a few places where I force it to Sync just so it doesn't get wildly out of date on load/etc.

When selecting a Loadout from the dropdown, all 3 dropdowns will select the proper set.

### Link to a build that showcases this PR:
https://pobb.in/u/Subtractem/1OOStQLc9ePX

### CODE REVIEW

**Comment by KonstantinosKoubetsos** [comment]
Possible problem.
Usually in pobs, leveling sections have 1 set of gear that includes all possibilities while having multiple multiple trees. For example trees for each act but only 1 or 2 gear sets that won't change between acts. With the current implementation is it possible to match the same gear set to multiple gem / tree loadouts?

I understand the concern of overcomplicating the UI and putting a ton of buttons that overwhelm the user. But, as you said, 95% of people will just copy a streamer's pob that has everything already setup while the 5% of power users would benefit way more from having the ability to customize this to whatever extent they want.

It's a great feature to have and I believe the more customization the better. We will be able to create the perfect setup and if having 2 extra buttons is the sacrifice for it, then I think it's worth it. As a pob power user, I adore the multitude of options it offers and I find it best when we can do whatever we want and not be limited by UI design choices. And the normal users won't ever notice the extra button, as they will just import the already completed pob and never mess with it.

**Review by Wires77 — CHANGES_REQUESTED** [review]
I tend to agree that this doesn't provide enough flexibility in several cases and seems unintuitive, even with the tooltips/help text explaining things.  I did like the idea though, as it wouldn't require us to change our save file format at all.

I'm really not a fan of using list elements as buttons.  It's not good UX especially when nothing else works like that.

Finally, this dropdown is not visible on lower screen widths.

**Comment by Subtractem** [comment]
> I tend to agree that this doesn't provide enough flexibility in several cases and seems unintuitive, even with the tooltips/help text explaining things. I did like the idea though, as it wouldn't require us to change our save file format at all.

How would you feel about a manage panel without changing the underlying convention over configuration setup? This would make it more clear about what's going on at least. I very much prefer convention when possible, particularly for long term maintenance and, after it is learned by the user, significantly easier usage. Configuration will make it more brittle and prone to annoyance when things aren't lined up just right.

A popup panel like the manage trees one could make it more clear about what's going on for users that want to engage with the system.

> I'm really not a fan of using list elements as buttons. It's not good UX especially when nothing else works like that.

I agree, I don't like it. I wouldn't say nothing else works like that. This is, to me, similar to the "manage trees..." option in the dropdown for passive trees. I was trying to go with conventions that we already had while reduced visual clutter for options that will be rarely used.  I'm open to ideas here but adding a couple extra buttons seems odd as well.  It does feel like a Manage button for loadouts could solve many of the concerns.

> Finally, this dropdown is not visible on lower screen widths.

Talking to @LocalIdentity the other day we already have concessions for 1080p on the bottom bar so I wasn't overly concerned as long as I stayed within 1920 width on the top as well. There is plenty of room to move this a bit to the left however.

**Comment by Wires77** [comment]
> How would you feel about a manage panel without changing the underlying convention over configuration setup? This would make it more clear about what's going on at least. I very much prefer convention when possible, particularly for long term maintenance and, after it is learned by the user, significantly easier usage. Configuration will make it more brittle and prone to annoyance when things aren't lined up just right.

I wouldn't mind that as much, since like I said I am a fan of not changing the save file format, as that has knock-on effects.  The workaround right now is to simply copy an item/skill/tree set and change the name for the loadout.  A popup would help make this more transparent.  For example, most builds never want to change the tree once they reach end game, but often have skill/gear swaps for bossing vs. mapping.

The downside to this approach is it bloats the save file, especially if you have duplicate item sets but a bunch of different skill/tree sets.  I'm just waiting for a build creator to only ever create a single PoB with all their builds in it and wind up with a 1GB build file.....

Sidenote, I haven't dug into the code deeply enough to see if there's something better we can do, but having the popup might let us do away with the Sync calls/button, since the list can be built when the popup appears.

> This is, to me, similar to the "manage trees..." option in the dropdown for passive trees. I was trying to go with conventions that we already had while reduced visual clutter for options that will be rarely used.

Ooo, yeah I forgot Manage trees works like that.  Makes me feel better about it being used as a button.  This looks very odd though, haha:

image

>  Talking to @LocalIdentity the other day we already have concessions for 1080p on the bottom bar so I wasn't overly concerned as long as I stayed within 1920 width on the top as well. There is plenty of room to move this a bit to the left however.

Honestly, I'm not really happy with the bottom bar right now either, since a subset of our users can't use the power report at all right now.  There actually isn't any room to the left, as that is earmarked for longer build names:
image

I don't yet have a lot of opinions on what the pop-up should look like.  I had an idea of it if we were to do explicitly assigned loadouts, but with a naming convention approach I guess it's just a list of the sets that allows renaming?

**Comment by Wires77** [comment]
Superceded by #7672

**Pull request closed without merging**
