### PR TITLE
Modules/Main: Dont use implizit arg table in LoadPastebinCode

### PR DESCRIPTION
**Pull request by farmboy0**
This is a fix for using Path of Building with pobfrontend.

### CODE REVIEW

**Comment by ppoelzl** [comment]
Why is this change needed for pobfrontend to function? I can see that there's a release for 2.4.0 here: https://github.com/hsource/pobfrontend/releases/tag/2.4.0, without relying on these changes.

**Review by ppoelzl — COMMENTED** [review]
Closing this PR, since it's not clear why these changes are needed for pobfrontend.

**Comment by farmboy0** [comment]
The pobfrontend author made an ugly hack to fix this in pobfrontend:
https://github.com/bernhardfritz/pobfrontend/commit/1e8aa4593531cc4befd513d613ececd9c52710a4
I think this PR would be a much cleaner fix.

**Comment by ppoelzl** [comment]
Doesn't seem ugly to me. @bernhardfritz, if you want these changes as well, please let us know.

**Comment by bernhardfritz** [comment]
Changes are not necessary imo, PoB works fine without it.
What has been added in bernhardfritz/pobfrontend@1e8aa45 allows build links to be loaded from CLI like this:
```bash
./PathOfBuilding https://pastebin.com/2TWTQ5z3
```
I stumbled upon this PoB feature by accident and found it useful enough that I decided to forward CLI args from pobfrontend wrapper to PoB.

**Pull request closed without merging**
