### PR TITLE
Explicitely check for 1 size sets for loadouts

### PR DESCRIPTION
**Pull request by deathbeam**
Instead of assigning 1 size sets to existing loadout links, just check for this when the loadouts are being matched instead. Its more reliable and do not relies on links to be filled (in case of name match sets for example).

### Link to a build that showcases this PR:

Loadouts with groups: https://pobb.in/u/thedeathbeam/pf-poison-scourge-arrow
Default loadout with names: https://pobb.in/u/thedeathbeam/pf-poison-spark
Abc loadout with config being "Default": https://pobb.in/jdpxU9ADNlGF

### CODE REVIEW

**Comment by Peechey** [comment]
What about for a single Tree? I don't think this is supported in live even now with group Loadouts and I don't see a huge need for it but if we're not going to, the third condition in Help should be updated to say so

**Comment by Wires77** [comment]
Found an issue, but I'm not sure it's caused by this PR or if it's just a side effect:
1. Using your 2nd example build
2. Create a new config set and swap to it
3. Notice loadout dropdown doesn't change, and clicking on the loadout doesn't swap the config set back (you have to click on "Loadouts:" and go back to "Default" for it to do so

**Comment by deathbeam** [comment]
> Found an issue, but I'm not sure it's caused by this PR or if it's just a side effect:
> 
> 1. Using your 2nd example build
> 2. Create a new config set and swap to it
> 3. Notice loadout dropdown doesn't change, and clicking on the loadout doesn't swap the config set back (you have to click on "Loadouts:" and go back to "Default" for it to do so

This was also problem on master, loadout selection wasnt resynced on active set change. Pushed commit that will fix it here

**Comment by deathbeam** [comment]
> What about for a single Tree? I don't think this is supported in live even now with group Loadouts and I don't see a huge need for it but if we're not going to, the third condition in Help should be updated to say so

Updated te help file

**Review by Wires77 — APPROVED** [review]

**Pull request merged**
