### PR TITLE
Item pricing mod calculation does now use dps instead of damage

### PR DESCRIPTION
**Pull request by Urganot**
### Description of the problem being solved:
Mod comparison was looking at total damage and not dps

### CODE REVIEW

**Comment by QuickStick123** [comment]
This looks good but this entire section of code is getting replaced soon in https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/5376

**Comment by QuickStick123** [comment]
The comparison seems to have gotten broken.

**Comment by Urganot** [comment]
Thats kinda funny :)
Ill reset the branch and implement the changes again

**Comment by LocalIdentity** [comment]
Can you change the spaces to tabs for indenting

**Comment by Urganot** [comment]
Sure

**Review by LocalIdentity — APPROVED** [review]

**Pull request merged**
