### PR TITLE
Fix support gem crosslink issues.

### LINKED ISSUE #6618: Sort gems by DPS not working for Raise Spiders (Arakaali's Fang)
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Check for support

- [X] I've checked that the behaviour is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What is the behaviour in-game?

N/A

### What is the behaviour in Path of Building?

Gems are not being sorted by DPS with respect to Raise Spiders; active gems are suggested over support gems.

### How to reproduce the issue

1. Add Arakaali's Fang to Weapon 1
2. Make Raise Spiders your Main Skill
3. Check Include in Full DPS and set Count to 20 (optional)
4. In Gem Options, check Sort gems by DPS
5. Add a new Socket Group and set Socketed in to Weapon 1
6. Click Gem name

### Character build code

```shell
eNqtW21T4zgS_jz8ClWq7mqn6khix3mBC7sVEhiogxk2gZm7T1vCFokW2crYMpC9uv9-LclOTBI7MjYzNeNY_fSbpFZ3Kwx_e_MZeiFhRHlw1rCa7QYigcs9GszPGg_3l8eDxm-_Hg3vsFh8ezqPKZMjvx59GqpnxMgLYYBrIIHDORHfU06dP4DTEgdiQXhwi__k4RfunTW-8oA00CMOPCrSTy7DUfQV--SsMXMB3EA4ckngjTfvE8IFDrErSHgjpY5iwW-5B6MijGHUxzSYcfeZiC8hj5dKqRdKXjXN9e3dt-l9RiUaZFUCiz4N7xhekXAmsEAR_HPWGLmCvhAgBa1uqE8FcMQsBnZ2u9HKwYAz8ZxcZYgP0Z7HYSQm2IfHw5jZkhBvQ9Z0Tnr9fvtkMOj2Hbufh7oLycXTE1H2jEMqxgscuAbSytLexkzQJaMkXNNbzW4e4mqHudXOZX_PBWaTu9lhRTQlN5iAH1Qszhk41IivpL6eB1QQY_I7TiMelNLaiHgcMwYb0Yh2SiISvmBBDRUZc_-RBoY-GXPOPP4abHZGs2118qhvcYDHPDKYGUl5R0KIA6IUYEZcDqGjrIySyBv6RMwpS9mRAMpq8zE7LmamdKUZf0yhKcRAM8oZj5khpQgN4vaEvBlQTcnPLGF3kEd4HQgzdllCy-7kq_fChTocjeLIxdXdRsmTpmV1Ou22c2L3LCv3iFisIupidovfqB_7EJvv8TPZCOwVrL_5QgQQjvKgnVw3XdKQlEeNIeZ8ALXAPCoPk7vLwAlwLrunkvY6cM227EMQqsicOc57hYApbCSZMTwyYojYiEi2o8lBq0XNSZDIW5mZc0OIu_gCSdgUC2IWfDdLtNitktbIrZJwj1u7hoASTpLAHCc1T4pAJd10EZBwvpotKGFeOepUsTFeGmWV7mkWbeTu9-JKrZgstKRLfuDQMztJyur0gqNsiLV6xe7S5GYLk0CWCQCPmGbTdyH_U-brrBxsFPo8Dg0nXBMbGZCeDrpMmRIvds2Oo3MGNZmp9qAVY6UQIyGw-zzh3pyUElIeMYuXSwgUcspNcfJ0g-ybZrKU454B9TdYr0bbVh6E5gI21MYC1ke7uZQtiLkt8nguYcyG3FjEugS-hYjgQ6RXxfQt34ST3OzoEgqubEHkWHb7pGmf9J3uYDBwCmHvazrb7vTTijjhOnumjKFI_nuHQ4A1UAQb0yXqac0I6WoSleU2W1KPhEj3MU7Rd7qET5AV02eyK8huv6EpphFBGhZtfDMYdJzDJt_xV5iOhWwHRQZxJUMNudkmH8v1aEiCv1bG_N-RGwm4CLw4lPvbWMY2wkiMQW9JD-72i7ZaRSdtp9l2enZ_0LZ7TicP_L5xZAHE6qU__VpBO52aE8dq9i1n0LdPHMcuhu1p2-xQ7m3bmAnZ38Mxw-42c-zeYN3dyiN_P1lWu-8U6bZHRrvXbjo9U-9loZZlDZr9XAULmkg7tAeaSLu89zSRDC15V3B1nF6viLA4xdsLKU43dyCFGXghdUndzFPie-pDPhlFEyww8pLOwHccUhwIWzW-I4JDd3EDh-MlZuwRUiQV4ddv5actoJWefsOW6u3Lp2t_yUOByJv8Tx4mq7PGE2YR0YTqDfCJBA3U0oAQxVgDzRb8deS9yJB4zzmLUhDCyyUJvHc87kNCEFbBUOakUgllo_yQvQi49qT9yMeRAG_qkzySZgQcFJCtmEGn00AC2GUuIWw7uV_QcMn50_BheqMePi2EWEanrdbr62tzicWCP5E3SLibLvdbSwCBTsfqHD2WbFsj-Dmfj9SPYtRKOQ31xUPU0p9kQhLC4ak_D1vSFuVYaax8-MoFieSYfJl-GKqDO4ITORRfiB-dr2DzXMrVsLWdEm9J6hkRer6zmPRGxCNPOGby_e8xZlROXjv79kZf3gQ89NdtH2AFkydzXc3xfrWU3h3d3OiRERMJMykunUk9Y4lCiHrpLCYv1d3MaKP1GDM3UnrTwGWxR66DJHdJVWf4UarWQHN5lzPmcaBSk026ci2If2pBBYOfMajzd7zk0T8jdImD-T8QOC3w0ATP5_IeggSyY-KlrCPGZawlgAiQ1djWba36pyFYmIC_MP6IGWytgMLyVksi2b7vzcmMJC91EqVfNTLXZVm-1lo1CZcr9T6kUnfizWLfBymKya5gxelnZm63THW135TSAfaTDbaV3WWYbqmbrOaWknV4OpWY3QlNtv56RstOh2Sb7qNkham9pHeLfFTyFcV1sIyFMvWs4dPI_eMxfnqSF4Ayuw3VnebF5eXF-P76-0XCNAtRrvgjiP1H6W39_6YmmBFV8qIofoz041njOyWvSpEJEZiySPqcMbyMyDrKqe2QaM4AV8BNUV3R9V3gfl4bgnxOF28khKA8_wEBP6QkV6_1-AGltEB5kMmzJ4-bTN7yGelSfQwBXB9qOZ5SGWc-F3nLmGuOHCzAwnGGWa7kZPSAJ4QMiLCP6BN15eFdPOUyfGqqAr-4LpQP7qpgvpOGQz4PlQ3nMdCD-WCdc-ahk9ECr6p0OterejQfPiEuzrVdD-aD13kSD9SN-34ua6oCTl-TVB02zYgy2RzIndkLRtYk-Qy_iQUJkzwlj9MtxKiUpHDjhPQxFvnbOENR4CuVV-d4SI7lQ3WzPscGOVYQid6lzzkOzdLks9KN39xAVgTVjaJc_yVtp4IpSNqqOe7XowVOSDvLOfYnwwWbRMXf0Qunnm495myXLbKigAEZa3U2qo1anc12g7U6x0tI-p9z5zsZzYc_CCqTqj1cdNZixERuqmoc5N6qxmG6nUhssNPiFELFrwl5IuDowgC2pimYXxEHEzjkRMHcGrJSau3fCBvTSvHSoXyvpaU56gWaXC0XrWFNcoARnEVXBdmOGad10_uKYCYbTJxVY7hzhV7JTi4iHHgT2SqpaKjstMRLYJZq9m1furqZ0m2uw1ZaSKimhEztk47JTISycvmLc_8_qs6ST0n13EkqZkjyJhRcHaolksqRhP9OGzdDWbRGSfkun9PqPY6I_pKMLoPUa1n26AIFCLMl9RRDkrs6RQ9fr39_uDjaVwEfZQvgo6ReP0V2-yjpU5yi82P4c6RsmJKfp6jbOYL8l1GXylHryGn_TdZyIcHgNaTrVCTTa3kJmFweIJ2WHlltIHbVMxIcJcUrUsyR9f42AcGk_QsS46P_hqAoOW03u__7xeq3j-12-3NWZHrhiPQ0ZelHnhehXwbHVuezlPeL3T7utD_vIBSZJSm6J0hdF6UjVjerb3KrAn9h4agqFyrGqZSGlEx5pd9tJFOQ1MS5FPZBis5BCucgRfcgRdo0bcnls15HsjuTt9jet22gKkeQt_t3jw_TG9VmUxUyLIQXGSPlkG6ptYoBm8I-hViHIOccYgIaPa6iSC41tWJRt4TMc8LENt4ugVeHKup8wEo0e8XLbdHORxhVMD_hYdfAY79BvRoM6tVg0Id47DPIKrO49q3OTg0eseuypsx6uyKQ_IhK_tiz2XqVNbBLc6gsslOX_7s1LAarhu1h1aCHU3Il1BVi7Ko70qnBgeXPjNpCbKeq_XbFLVxOAW-FdA-kyhrUuUUVDvs3drcyh15d02rVFWPKL83qfnQqz2W3nkVVxviRHzMiaoiEnRoCSqfipnQq4q16_P_hk7L0onVKIz6SRVX0ardqrK5pWpy6gkttefWHS6gSuCkN5qWmcH9osuuZg9pOijoKPudjNpV1fvUzvqZko1tZkepHXK9sMKgaPHYF6p5P-jUJ1XNU35LgwROdp19GdcmCM_mtYM2aBMRfJV_2TL_30M_-9ss-etkOTL-qkII6BzDpEkvpbfuwjPTr9immWwxJfkWBM6ZaY1mDioHrW7oU0OsXA97_UkRGUNpPTlw-bG3__vz_AVZ0KPc=
```

### Screenshots

image

### PR DESCRIPTION
**Pull request by Paliak**
Fixes #6618

### Description of the problem being solved:
When a skill is added from some other source than a gem new a group is created for that skill specifically. Currently support gems from the groups socketed in the source slot are copied over (This is quite inefficient as they need to be processed separately). This only happens in the `MAIN` calc mode as is assumed to have been done in `CACHE` and `CALCS` modes. The linked issue is caused by the dps tooltip comparison using the `CALCS` mode for calculations which causes the support gems that may have changed to not be copied over.

This pr reworks the way support gem cross linking is handled in general to better handle possible cases where doing so may be needed.

I will add some tests after i figure out what is causing ac203b7d091e9b866d9f3e4cf7cc2e4d2d498561

### Steps taken to verify a working solution:
- Test Empower, Enhance supports
- Test Energy Blade
- Test Various combinations of linked groups
- Test [Uul-Netol's Vow](https://www.poewiki.net/wiki/Uul-Netol%27s_Vow) and [The Squire](https://www.poewiki.net/wiki/The_Squire)

TODO:
- [x] Treat each socket group as an in game link group with the exception of groups created by skills coming from items and when an item is crosslinked to another by a mod. In such cases apply all supports from all groups socketed in sourcce item to all groups socketed in target item
- [x] Apply simillar logic to above to the gem dropdown
- [ ] Check if more filtering can be applied to the lessen the amount of calcFunc calls when calculating gems for dropdown.

### Link to a build that showcases this PR:
https://pobb.in/3o5KNz0wEfyH
https://pobb.in/1ygiNxHUhLno

### Before screenshot:
obraz
obraz

### After screenshot:
obraz
obraz

### CODE REVIEW

**Comment by gaaasstly** [comment]
Is there a bug with alternate quality dps calculation? Why would Anomalous Multistrike be above Superior or Divergent?

From [the wiki](https://www.poewiki.net/wiki/Multistrike_Support)

**Superior**
Supported Skills deal 0.5% increased Melee Physical Damage

**Anomalous**
Supported Skills have 1% reduced Attack Speed
Supported Skills have 1% increased Area of Effect per Repeat

**Divergent**
Supported Skills have 0.5% increased Attack Speed

image

Switching from Anomalous to another quality gives a dps increase.

image
image

**Comment by Regisle** [comment]
Sounds like quality isnt taken into account when that is done and those are just sorted by the base gems dps change and then alphabetically

**Comment by Paliak** [comment]
@gaaasstly Thanks for testing. Latest commit should fix the issue.

**Review by LocalIdentity — APPROVED** [review]

**Comment by Paliak** [comment]
This currently has issues with cases where there are multiple link groups in the same item which causes them all to be linked together and causes the gem dropdown to show supports considering all active gems in the current item.

Need some more time to think how to go about solving this.

**Comment by Paliak** [comment]
Needs testing again after fixing noSupport flag. Also there's some duplicate code that could be pulled out into a function.

**Comment by sida-wang** [comment]
This should resolve #647 - don't mind me, just going through old issues sorted by likes

**Review by LocalIdentity — APPROVED** [review]

**Comment by UchihaWind4U** [comment]
I notice the spider's basic damage of Arakaali's Fang is changed into 586 to 879 from 716 to 1074 from 2.38. Is this change a number fix or missing? 
2.38 basic damge

2.39 basic damge

Waiting for your reply.

**Comment by sida-wang** [comment]
Per the v2.39.0 Release notes
> Fix longstanding issues with minion stats (more fixes will come in future updates) by (@LocalIdentity, @ifnjeff) in https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/7253
Some Minion Attacks will reduce by 10-30% DPS

**Pull request merged**
