### PR TITLE
feat: add 3.17 skill tree

### PR DESCRIPTION
**Pull request by ppoelzl**
Add 3.17 passive skill tree prerelease. Currently visually broken, likely needs changes to the way orbits are handled.

### CODE REVIEW

**Comment by Guitaraholic** [comment]
From the read me : 

### 3.17.0
---
The amount of nodes per orbit has changed to give us more angles to work with.

| Orbit | Nodes (Old) | Nodes (New) |
| --- | --- | --- |
| 0 | 1 | 1 |
| 1 | 6 | 6 |
| 2 | 12 | **16** |
| 3 | 12 | **16** |
| 4 | 40 | 40 |
| 5 | 72 | 72 |
| 6 | 72 | 72 |

The angle for positions in these orbits (2 & 3) are now:

| Orbit Index | Angle |
| --- | --- |
| 0 | 0 |
| 1 | 30 |
| 2 | **45** |
| 3 | 60 |
| 4 | 90 |
| 5 | 120 |
| 6 | **135** |
| 7 | 150 |
| 8 | 180 |
| 9 | 210 |
| 10 | **225** |
| 11 | 240 |
| 12 | 270 |
| 13 | 300 |
| 14 | **315** |
| 15 | 330 |

and this seems to be calculated in Classes/passiveTree.lua but need to identify the calculation changes

**Comment by Nostrademous** [comment]
OBE's by #3972

**Comment by alphastrata** [comment]
> From the read me :
> ### 3.17.0
> 
> The amount of nodes per orbit has changed to give us more angles to work with.
> Orbit 	Nodes (Old) 	Nodes (New)
> 0 	1 	1
> 1 	6 	6
> 2 	12 	**16**
> 3 	12 	**16**
> 4 	40 	40
> 5 	72 	72
> 6 	72 	72
> 
> The angle for positions in these orbits (2 & 3) are now:
> Orbit Index 	Angle
> 0 	0
> 1 	30
> 2 	**45**
> 3 	60
> 4 	90
> 5 	120
> 6 	**135**
> 7 	150
> 8 	180
> 9 	210
> 10 	**225**
> 11 	240
> 12 	270
> 13 	300
> 14 	**315**
> 15 	330
> 
> and this seems to be calculated in Classes/passiveTree.lua but need to identify the calculation changes

How is it you worked this out? is there a formula somewhere in here? (I've not had any luck searching for it)..
Context: I'm building a graph solver thinggo for fun and have been using POE2's tree data to seed it (lots of data and numbers etc).

**Comment by Wires77** [comment]
@alphastrata copied from [the source](https://github.com/grindinggear/skilltree-export)

**Comment by alphastrata** [comment]
> @alphastrata copied from [the source](https://github.com/grindinggear/skilltree-export)

thank you.

**Pull request closed without merging**
