### PR TITLE
Don't save default minion skill set choice

### PR DESCRIPTION
**Pull request by Paliak**
### Description of the problem being solved:
Default minion skillset was being saved to skills triggering phantasm support causing the default minion skill set to spread like a disease in build save files.

Marking as draft as while rather innocent still sort of worried it may break some edge case.

### CODE REVIEW

**Review by Nostrademous — APPROVED** [review]

**Comment by QuickStick123** [comment]
AFAIK this should only be occurring with disabled skills/vaal skills atm.

**Comment by Paliak** [comment]
@QuickStick123 This happens with all skills. This is caused by the drop down sorting functionality adding the summon phantasms support which saves the default selection of minion skill in the drop down to the skillInstance which is then later saved to the build xml.

**Comment by QuickStick123** [comment]
Do you have some replication steps?

**Comment by Paliak** [comment]
This now causes the minion selection to not be saved to build xml which is probably not worth the minor build xml bloating. Closing in favor of https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/5700 (and to clean up the opened prs a bit)

**Pull request closed without merging**
