### PR TITLE
Automatically apply Energy Blade buff

### PR DESCRIPTION
**Pull request by QuickStick123**
Fixes https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/4100#issuecomment-1233635861

### Description of the problem being solved:
Energy blade due to overwriting the weapon creates problems due to circular dependencies. The previous solution resolved this by a config option.
This checks if energy blade is present in a first pass recalculates everything with the AffectedByEnergyBlade flag if it is. 

### Steps taken to verify a working solution:
- Enabling/Disabling the gem now enables/disables energy blade and correctly enables/disables stats on weapon.

### Link to a build that showcases this PR:
https://poe.ninja/pob/FHZ

### CODE REVIEW

**Comment by Paliak** [comment]
Is it be possible to use `overrides` var for the `flag` var in initEnv ? I think that would be more elegant.

**Comment by livejamie** [comment]
Does this mean it will be implemented in the next release?

**Comment by Wires77** [comment]
> Does this mean it will be implemented in the next release?

Once this PR is reviewed, it'll be merged and then will make it into the next release, yes

**Review by LocalIdentity — APPROVED** [review]

**Comment by livejamie** [comment]
Hello @QuickStick123 , when I import current characters from poe.ninja using Energy Blade it's showing the incorrect ES still. The problem seems to be because POB is confused by the main weapon slot being empty.

Once I add any weapon, it seems to work as expected.

Example character: https://poe.ninja/challenge/builds/char/SpiritKinay/SpiritSanctum

**Comment by QuickStick123** [comment]
I notified the poe.ninja person about this a few weeks ago. It is caused by us treating energy blade specially. It works correctly if you import the character but if you copy paste the item (energy blade) which I think poe.ninja functionally does it doesn't work.

**Pull request merged**
