### PR TITLE
Added Bear's Girdle new unique

### PR DESCRIPTION
**Pull request by Wires77**
I opted to have "Crushed" as a config option for future-proofing, and since we don't really support "Nearby" on things like Belt of the Deceiver anyway

### CODE REVIEW

**Comment by LocalIdentity** [comment]
Instead of being a tooltip, this should be based on a stat threshold of 25 rage

**Comment by Wires77** [comment]
That seems inconsistent with other uniques, then.  Belt of the Deceiver doesn't automatically add Intimidate, and Eclipse Solaris doesn't automatically add Blind, for example

**Comment by Quotae** [comment]
The difference is that this mod is also using a stat that PoB already tracks, while the generic "Nearby" is inconsistent and not already tracked. There *are* instances of PoB automatically applying "Nearby" mods like the Occultist's Void Beacon or the unique staff Dying Breath, and of course there's already mods that automatically enabled based on having a certain amount of Rage, like this one:
image

I think the current best way to support this mod would be to have it apply a "Crushed" condition to the enemy based on how much Rage you have, then add "Crushed" as an effect in CalcSetup.lua, near the top of the file next to things like Maimed and Blinded. I'd also remove the config option since this is the only source of the mod in the game right now and the config can be added pretty easily if it gets more support in future patches.

**Comment by Wires77** [comment]
I'm fine with the rage conditional, of course that's easy enough to add, but "Nearby" is inconsistently added as a condition.  I'd rather add it to the missing uniques if I'm going to add it here too.

Removing the config is fine too if this gets added when you're above 25 rage regardless of "Nearby".  The only thing that breaks is getting the crushed condition from an aurabot, but we don't have much support for them anyway.

**Comment by Quotae** [comment]
"Nearby" is applied automatically in cases where the mod isn't easily applied, like Dying Breath or Void Beacon. It's not applied automatically when the thing it's doing is already a checkbox in the Config, like Belt of the Deceiver or Saboteur's Born in the Shadows. It would be annoying to force players to manually add effect of Curses, and you can't just add a toggle for "Nearby" since the range is different on so many things. But Blind, Intimidate, or Hindered all have checkboxes already in the Config, which are easy to click and apply.

For this case, not only is Crushed a unique effect to the item that would be irritating to make players apply manually, it has an extra condition with the 25 Rage. The 25 Rage is easily checked, so that combined with the convenience factor means it should just apply automatically if you have 25 Rage. If you just made Crushed a config toggle it would be possible to enable it with less than 25 Rage, which isn't correct for solo play. You can still simulate an aurabot by manually setting Enemy Phys Reduction for those that care enough to add their aurabot effects to their build.

**Comment by Wires77** [comment]
If the convenience factor is the main point of the argument, why don't the other sources of Blind, Intimidate, and Hinder just automatically apply their effects too?  They all have some conditional effect, most of which are also already implemented.  Does it just boil down to "Those checkboxes were already there", so if Crushed existed prior to this we wouldn't implement this line, either?

**Comment by dclamage** [comment]
Could you add the catalyst tags to this unique?

**Comment by Quotae** [comment]
If there were already a checkbox and there were many other sources of this mechanic, I would still say that this one should be automatic because of the Rage condition on it. If the mod were simply "Nearby enemies are Crushed" I would add Crushed as a global effect in CalcSetup and have a config option that shows up similarly to how Rage and Elusive do(with a Condition:Can<thing> and a dummy variable with a condition of "<thing>").

The truth is though that this exact situation(Nearby with a condition) has no precedent. I searched around and the only other example like this I can find is the Ascendant's Raider node. It gives Onslaught while you're at maximum Frenzy Charges, without you having to check the box to enable Onslaught. The box would work just fine but the condition means it just enables whenever the condition is met. That's how this one should work.

**Comment by Wires77** [comment]
Honestly, I'd rather just remove the checkbox if it's such a sticking point.  Nearby is not at all consistent and I don't want to mislead people by having their DPS go up just because they have 25 rage even if they aren't meeting the other condition.

Since Crushed is only on this item, I can look into hiding the config option unless you have 25 rage (or are wearing this belt) also.

**Comment by Quotae** [comment]
I think that that's inconsistent with every other source of Nearby besides the easy "Nearby enemies are \<thing\>" mods I mentioned earlier. War Banner, Flesh and Stone, Ascendancy notables, -res mod on Delve/Influence helmets, Dying Breath, Perquil's Toe. All of these use the word "Nearby" and are enabled with no further input, just from my memory. At this point I'm probably not going to convince you though so I guess it'll be up to LocalIdentity to give his decision on it.

**Comment by Wires77** [comment]
Looking through everything in PoB that has "Nearby enemies", here is the best ruleset I can tell is implemented/not implemented:

1. Buffs/debuffs that affect enemy damage are not implemented (e.g. Augury of Pentinence, Avatar of the Veil)
2. Buffs/debuffs with a name are not implemented, and are instead added as a checkbox in Config (e.g. Blinded, Intimidated, Shocked, Exposure [caveat being you have to add an exposure skill for the checkbox to appear], etc) 
3. Other numerical buffs ARE implemented (e.g. Void Beacon, Opportunistic, Dying Breath)

The only exception to this I could find was in Eye of Malice, which doesn't apply the -50% fire and cold resistance to nearby enemies.

By this logic, "Crushed" is a named effect, and should be a checkbox as well.

**Comment by ppoelzl** [comment]
@PathOfBuildingCommunity/maintainer decided that we should apply "Crushed" by default for now. We'll possibly rework all instances of "nearby" to be more consistent the update after next though. Could you please rework your PR to add the "Crushed" mod to the mod parser? @Wires77

**Comment by Wires77** [comment]
Fixed to add "Crushed"

**Pull request merged**
