### PR TITLE
Remove trailing and leading spaces from the import character name

### LINKED ISSUE #3870: Trim trailing whitespaces
### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Is your feature request related to a problem?

image
image

### Describe the solution you'd like

Input fields should trim trailing whitespaces

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by pHiney**
Fixes #3870.

### Description of the problem being solved:
Whitespaces were not being removed from the character name on the import tab

### Steps taken to verify a working solution:
- Open a new build
- Select import
- paste in " xyllywyt "
- Select Start
- Note characters are listed
- Select Done
- Note the spaces that were there (in character name) are gone.

### Link to a build that showcases this PR:
N/A

### Before screenshot:
image

### After screenshot:
image

I have not tested special character names cause i don't know one

### CODE REVIEW

**Review by Nostrademous — CHANGES_REQUESTED** [review]
To keep with the convention of the rest of the file can you please change this to:
```
-- Trim Trailing/Leading spaces
local accountName = self.controls.accountName.buf:gsub("%s+", "")
```

The two changes are
1) putting comments above the line rather than at end
2) not using `string.gsub(<string>, <pattern>, <sub>)` but rather `<string>:gsub(<pattern>, <sub>)`

**Comment by pHiney** [comment]
Apologies. Done.

**Comment by Nostrademous** [comment]
No worries. Since you are active and doing good stuff just offering minor tips to help move things faster. Hopefully I'm not being too picky or annoying.

**Comment by pHiney** [comment]
No, all part of the learning.

**Review by LocalIdentity — APPROVED** [review]

**Pull request merged**
