### PR TITLE
Gem Fixes

### PR DESCRIPTION
**Pull request by Nostrademous**
Fixes:

1) Seismic Trap scaling
2) Multistrike support for Totems
3) Ruthless Support
4) Sneaks in Forbidden Rite implemenation

### CODE REVIEW

**Comment by pundm** [comment]
fixes #2949 and #2936

**Comment by Lothrik** [comment]
Based on the behavior seen in the skill preview the projectile count in Forbidden Rite here is off by 1, as it hits with 2 projectiles even with no support gems (or sources of additional projectiles) against a single enemy.

**Comment by Nostrademous** [comment]
Once we export the GGPK we will have real numbers. The skill is supposed to launch one projectile where you target and then 6-7 (depending on gem level) at the nearest 6-7 enemies. If it's a solo enemy (aka boss) it will launch 2 (the 1 location target, and 1 of the 6-7 nearest).

**Comment by LocalIdentity** [comment]
Changes made in other PRs, this one is no longer needed.

**Pull request closed without merging**
