### PR TITLE
Show accuracy above hit chance when using Precise Technique

### PR DESCRIPTION
**Pull request by Peechey**
### Description of the problem being solved:
Adding a little QoL for Precise Technique users, normally when playing around with the tree or items or some configuration you would need to flip over to the Calcs tab to track down exact accuracy. With this, MainHand (and OffHand if using) Accuracy is displayed above Hit Chance in the sidebar stats given the keystone is allocated. Strictly a conditional displayStat.

I'm not 100% certain the CalcOffense change is in the best location to set whether Precise Technique is allocated but I figured it's inside the "isAttack" and around the MainHand/OffHand calcs so it's a safe bet.

### Steps taken to verify a working solution:
- Main Skill: Boneshatter, 2H weapon, verify MH Accuracy
- Main Skill: Dual Strike, Dual Wield, verify MH and OH Accuracy
- Verify spells do not show Accuracy

### Link to a build that showcases this PR:
<pre>
eNrtW21z4jgS_jz5FS6q7tORgN8ISSW7RYBkqA0JC5mZu09TwhbgjbAYW07CXt1_v5Zkg2GQsbGr7rbqZqqIsfppdT8ttVqyufn1Y0m0NxyEHvVva_pFs6Zh36Gu589va19e7s_btV9_ObsZIbZ4nt1FHuEtv5x9uhHXGsFvmNzWjJrGUDDH7GuiyfwOmlbIZwtM_SH6gwYP1L2tPVEf17Qp8l2PJd8cgsLwCS3xbW3iALimodDBvtvd3o8FFyhADsPBI--1EzE6pC60zhAJoXmJPH9CnVfMHgIarcCbmvbm4XcpNBiOnscvKZs8P20TuPTpZkTQGgcThpgWwsdtrQPMoDnuoSV8gjZEIlClW5dXF229rVu2odtWrZEJvouCkJ2mYbLC2N2CLgBmq2RHAe7PZthh3hvuBh7rLpDvbHtsqnBFZYcRYd6KeDg4Lv_5J9V6Uyn8QhkivdFkK9u6al80r3TT0FumdZmNo-y4Od88trgjQOkJvXDsYO57DJ8IHlEvpH4J_9JQdYQiQmCC5pId4xAHb4h5u2apddPl1PNPYm-IfNSl4TZGdpbkCAcw_9kOoHkEMMEOhZSx08fFpXmZp6PDcGWPj94M55cs5EwMKGrNaX70J3nlCis-zaAxpMh8khMakZySbJunDFs9FX6kBXVbKdnDH3mSGShMS161VYIDf-uEkaUuLZhp3xtlYhE9xozIK_3Po43kpXFx1WxZTfPKarbbyrk8WqxDz0FkiD68ZbSEHP-CXvG2w0tLPVTnC-ZDelJB7ZYKeu8FuDiqS4l7AmqBaKiCWa2siZiDBFjTnWsuO_CdfLP7ix-ITJ0qBbI4nuExzDlee0wJzonYdhHP3DxjXHY1x37c3zqfO48YO4sHqNXGiOF8-T1H0AStXDYXrVzwAK1q9buAAiRx4GGS9CxIQZL6Pg7m68nCw8QtJp2Y1UWrHMmUk5xG5yJ7t7tC4yUNLUjJNxS4-Zacoja9oTCdYA0jmy4pnmbKUM7FIYbyFBAuzluSjwL6By_6STFYJ1jSKMgZcSmcz4NkdZAbnjF2IyffcnRHYOuW13wwi5BCiA5jyHntUXeOC3VSHDGJVitIFDzoeXF8dYNq3EsVNOemcVz6GUZsronLF8L8HWylc3ewWdrz97IHye8LX573u2nlEc_dxWYjPYScsIRMLzbiQ-oeT973sAHLtZsSgjl3dSP6DpYv-AlLWEwaypgNwFSaEmD_z3Vu_TviuTro-24U8KmQu499xKFuXrwlpMsw7CGGNDeue7-iwEM-M8TpT4hR4CweIfT3iJApJIDbWvou_7YH1JPY3jTECRe_GixXNGDiZhcRJxS9D_xVxDRfHE8tvdD5Po1mM37UBB2wQByf9e_v-92Xwdd-bHAaEr56hHz3o-WUH6TIv9thNcEia2phNA3l5W3tq4ffJxzVwwx5BEh0KCFoFWJ3cwTmwaWQmQAzDsvQJqSguk0Opg7r2gqoNfU_cMDAX1hwncDDSrs27UeMkh3yxZgHWKWNH_ioFcls30Uhk8WCgilxvKbWwo-7lO7wxgwsjBlElD3HrUeYYOsVDmEB9maew-dGdshfQFpKZfDiODCtnHVGvOM1S61DnKCpFMhGNViegqnQcWsGq-IETsmqbFXDe9hBSt9loxq8qT-pDzSptGykMjQ9UV8Mcpg0HY_w9UUZ2T7BGxG1wme2wIFctJSahpCjEpHMiRN404ipp3FKIoMrsRdWMMTb1FC531P4wNsyMtHOLkhBaFpGrUruHpSJLAsqaw0lf3HlkhGCuDRX0C9bM0hIticK_-PmjEki8m_njXqurF4V02VPLCthQJ1eXo2oxMur2a_Ry2u8Jyh8VcY7blXDv8DmzWPrA1pYEOVVwidVOQ18bpXTMN4vJLbYcXYJIfJXD88wEJ2ZwDYyGfFlkd-DRY5lxDanKmHW4Ymwda2QLpnKD3paWKMcoPHpZNYYliJHFMFa9Dmj2smnabNv-owR4Y-8KCmn8KdT2FJ-UhYi3-3x456SjvLTomgFyhLLng-Vq9uQ7mu9aSQbiRtRu4VaCDuMB7wM79awI7znq9PeAzckiI2Leya3N2lM0p2LZygi_P7vEeKJhe-yUncf5RN7nwbLzRk-qFrQd54UpUZeSoaw1jw-ypYOYbEy3l3Cl2QnNki4qYt78U3xPL6ztVp4LOz2fIdELh748WZ5EwCCptw2_goCP7zeULinadPRpxuwJxZ-IHSKiJFAkhcTmrWddj1pF_uvAa9YqY_DBWKM78N-SC8HohwUjMWSIxRIzud4yVuHsAdzYd_ZGDBgpMFpaQjb4OqQRhGEPa82irfMwKjyZT98l8gP33YNbEh-ZVd_Pa57QMYEysdXfJjqHOQeUHGI20NEcqgWY__iRHYC52QG09i81HHMT5TFlzD5RUaTiYxfvgQYJ_lKwPU4V8CX9Ls93NImJyqEsb2ONyecSZ-6PP-YVuuqbrfs9lXdMK1Lva4328ZVXW_prct6y2wZzbptNdt1u902zbrZardB5Eq3LBBv13Xdurqsm6YNEqZtN8261W4b7ZrGwLzUe0qGHr-CJM2RXn4ZP8pgLRhbhdeNxvv7-8UKsQWd4Q-P4AuHLhsrAIGP5yIs51xtowP_7uadTm9uPJm_69NgvXoarWfW4u7L_PXu_rd1pxc9Pi-79uDH21vwDtK3t5LWpMcb-QpT2IgpBs4EvZxUfvFEYevF2_jN5IugnB8QxYdbMMo5j39Suvznbe3caFkXpvwap38rTvkMsZ4HxAei2kiGABf8B-Ds-Jz_RgyjOKT8OlmBohDLB_zfMFpRX9xOLQ5cNL0wjFEAg-5aG3fG_bMnsJYLnHVW-EPrEoxgDT3rBmjGsHutcUvORgGeeR_XGn9FK-PLJJrl-RKvYdea0TyLWb7WHs43_88EOWP841q7bJ4NliviOR6X0c_-bjT_pjGqxQumFqsSARtSd4z8OdYC_glj6MKuxV7HQeRu7hJiZBLi8xh6jjZZedA-JcjF_yViMij5F0Pz8HoVP-_57ooSp46JODDf3oj_JHJbgToSh3T_1ptALZ1pyZMjTRZL2iygS43XpNq7xxYaW3ihJoeZBldd6sNwAUJ4VBCn3gXxvlR-cljM_4flfywsvLRUZ5ndqpNQKEMBM5pCMhXriDhqh0X0jW-2eJPM8Y1sQOyOvoXoxyB3FDYXWme6DkNeZIhgaXaBPu8wYft4owBe7M418wQvtck7Wu13bZ2iqIT7sQ6jAh2HHWpV4FCrAodO0nHIIb3I4Do0Os0KGDGq8qbIePuMyRKzUnwcmGyt0hYYhTWU7tKsin-7gsGgVzA99ArssAqOhKpSjFF2RloVEFh8zagsxZpl_TdKTuFiBrhrTT5MKTMGZW1RRsPhiW2X1tCqKqx6VTmm-NAsz6NVOpZ2NYOqiPOdZUQwqyATmhUkFLPkpLRK4vVq-D95pSw8aK3CiFOqqJKs2mVzdUVhsapKLpXV1SdvoQrgxp4_LxTCw6nJqCYGla0UVWz4rNN8Kkp--TW-omLDLm1I-SWuVTQZlE0eP3coT32SRwniuFm8bkn9mTdPXhF18IISFwexauzj5Tr-iWzyAuVl-pcYh-Tj99IpIeIUKo3MBibjLJE3Wtny6d_VJhj7OCR5HzOBmEfM2rzukwDaR-zafUE_hUseTMeU3zT2f_P9HyHdzfQ=
</pre>

### After screenshot:
preciseTechnique

**Commit 4: Position updated to be above Life**:

image

**Commit 5 update, warning and color change**

image

### CODE REVIEW

**Comment by QuickStick123** [comment]
Would it be better to represent these as main hand hit chance and off hand hit chance instead and hide regular hit chance?

**Comment by Peechey** [comment]
This isn't about Hit Chance, it's purely so you can compare the values of Accuracy Rating to Total Life more easily/without needing to go to the Calcs Tab. I believe Hit Chance today is already accounting for two weapons of different accuracies.

**Comment by Nightblade** [comment]
Perhaps just generate a warning `if Total_Life > Accuracy and Precise_Technique`?
And/or have the amount of `Accuracy` over `Total_Life` appear in the sidebar with that warning? (Similar to how `Strength Requirement` etc. only show when necessary.)

Just some random thoughts :)

**Comment by mortentc** [comment]
I think having the actual accuracy rating always show, when Precise Technique is allocated, is preferable to a warning.
There are cases where you want to know by how much accuracy is greater than life, in case you want to proof against being blinded or running maps with "Players have x% less accuracy rating."

**Comment by Nightblade** [comment]
How much over cap might would be nice to see as well.

**Review by LocalIdentity — APPROVED** [review]

**Pull request merged**
