### PR TITLE
Make Skitterbots automatically Chill

### LINKED ISSUE #2091: Elemental hit and Skitterbots interaction.
Was just messing around with my Ele Hit Raider when I saw that the chill provided by Skitterbots does not affect Elemental Hit damage calculation. Ele Hit has this line "10% more Damage per Elemental Ailment on the Enemy" and seems to work fine with the shock portion of Skitterbots, but not the chill.

POB: https://pastebin.com/WDMTLWCu

### PR DESCRIPTION
**Pull request by Quotae**
Makes Skitterbots automatically Chill the enemy, just like they automatically Shock.

Resolves #2091

### CODE REVIEW

**Comment by Nostrademous** [comment]
LGTM

**Review by Nostrademous — APPROVED** [review]

**Review by ppoelzl — COMMENTED** [review]
Shouldn't this Chill also scale with Chill Effect?

**Comment by Quotae** [comment]
This is just to automatically set the Chilled flag on the enemy. If Chill Effect matters, which it only does for Bonechill Support, it's calculated just above this in CalcPerform, on line 730.

**Review by Wires77 — APPROVED** [review]
In testing this, I think there is potentially a problem with Bonechill, but it's separate to Summon Skitterbots.  The functionality covered by this PR works fine, so I'm good to merge it

**Pull request merged**
