### PR TITLE
General's Cry Mirage fixes

### LINKED ISSUE #2734: Weapon removal tooltip suggests ever-increasing Full DPS improvement
* **What happened?**

The "Removing this item from Weapon 1 will give you" breakdown in the weapon tool tip for certain skills can be made to constantly increase the supposed Full DPS gained.

This manifests both in 2.3.0 and current `dev` (793399f).

* **What steps will reproduce the bug?**

1. Import the build code.
2. Open the Skills pane.
3. Select "Earthquake, General's Cry".
4. Hover the "Weapon 1" dropdown.
5. Observe the Full DPS figure on the Cane of Kulemak climb up as long as the tooltip is shown.

The altered amount persists into that tooltip on the Items pane but cannot be triggered to climb in there. It doesn't seem to affect any obvious calcs.

* **Does it reproduce every time?**

Yes.

* **Provide a build code:**

https://pastebin.com/6CW1XHgH

* **Screenshots:**
gcry

### PR DESCRIPTION
**Pull request by Nostrademous**
Modified General's Cry mirage warrior DPS contribution to work the same as Mirage Archer. It is slightly different logic as General's Cry gem has an "active" and "support" component and we need to pull data from both. 

Fixes #2734

### CODE REVIEW

**Comment by zao** [comment]
Verified that this PR seems to address the visual glitch reported in #2734.

**Comment by yuzi-co** [comment]
Could you please also take a look at #2834

**Review by ppoelzl — APPROVED** [review]
LGTM.

**Comment by Helyos96** [comment]
Sorry for not reviewing this PR before it was merged. Got a few points:

* Mirage DPS is not the same as combined DPS, even though a skill supported by GC should only have mirage DPS.
* You dropped my changes regarding Non-channeled skills and the ignore-attack-speed patch
* Nodes on tree still show weird values

gc_bug_tree_node

**Comment by Nostrademous** [comment]
@Helyos96 

You are right, there is a few over-sights there. I need to zero out or ignore the original skill for DPS purposes and I need to re-add your patches.

I will need to dig to see why things still show weird values.

**Pull request merged**
