### PR TITLE
Adding quality mods to Zealotry and Anger

### LINKED ISSUE #1732: Anomalous Anger burning damage not working
Thank you for reporting an issue.

Before reporting a bug, **please make sure that you are running the latest version.**
You can get the latest version number from `CHANGELOG.md`

Please try to fill in as much of the template below as you're able.

* **What happened?**

Anomalous Anger doesn't increase the damage of burning arrow.

* **What were you trying to do?**

swap from default to anomalous anger

* **What steps will reproduce the bug?**

swap from default to anomalous anger

* **Does it reproduce every time?**

yes

* **Provide a build code:**

https://pastebin.com/2JxCqbcn

Always provide a build code that exhibits the bug you want to report, even if it is not specific to a particular build. This helps us greatly to reproduce bugs faster. Otherwise, we will have to ask you for the code first before investigating, which would delay any possible fixes.
* **Screenshots:**
If you receive an error or experience graphical bugs, include one or multiple screenshots. GIFs or short videos are also okay, if the bug cannot be displayed in a still image.

### PR DESCRIPTION
**Pull request by Wires77**
Fixes #1732

### CODE REVIEW

**Review by ppoelzl — COMMENTED** [review]
It's fine to also commit the related changes to the skill data itself.

**Comment by Wires77** [comment]
But...on #1715 you rejected the PR because I did just that....unless I'm misunderstanding what you mean by "skill data"

**Comment by ppoelzl** [comment]
In #1715 you included only the changes to the generated Lua files. So all your changes would have been reverted after the next time we generate them.
Generally, our prefered workflow is to have a PR that changes some aspect of automatically generated files to
* include changes to the export scripts (e.g. `./Export/Skills/act_dex.txt`
* also include the related changes to the data files (e.g. `./Data/Skills/act_dex.lua`)
Please avoid including any unrelated changes to the date files (e.g. changes caused by new game patches)
I hope that clears it up to you.

**Comment by ppoelzl** [comment]
Apart from that, it would be preferable but not required if you could rebase your PR unto the latest changes to dev.

**Comment by Wires77** [comment]
In #1715 there aren't any changes to be made to the .txt file.  The lua file changes based on bases.lua in that instance.  I thought that was our workflow, but you asked me to remove it last time so I removed it this time.

**Comment by ppoelzl** [comment]
I understand that our workflow might be confusing in this particular case, but I'd like you to include changes to the data files if they are caused by changes to the `.txt` files, and not in other cases.

**Review by ppoelzl — APPROVED** [review]

**Pull request merged**
