### PR TITLE
Add Search box to Add Modifier in ItemTab

### PR DESCRIPTION
**Pull request by pHiney**
The list of crafts is becoming more difficult to find things.

I have tested using Life, life, mana, Wizard.

All lists appear to contain the correct entries and no entries when that is appropriate (eg, Wizard in master crafts)

P

### CODE REVIEW

**Comment by LocalIdentity** [comment]
All the dropdown lists in PoB are already searchable if you just click on them and start typing, that negates the need for this PR

**Comment by LocalIdentity** [comment]
https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/182

**Comment by pHiney** [comment]
> 
> 
> All the dropdown lists in PoB are already searchable if you just click on them and start typing, that negates the need for this PR

I had no idea you could do that, and neither do my friends
Probably needs a hint added then ...

**Comment by LocalIdentity** [comment]
> > All the dropdown lists in PoB are already searchable if you just click on them and start typing, that negates the need for this PR
> 
> I had no idea you could do that, and neither do my friends
> Probably needs a hint added then ...

Yeah it could definitely use a hint somewhere I think. If you make a PR for that, I would be happy to merge it

**Comment by pHiney** [comment]
.

**Pull request closed without merging**
