### PR TITLE
removed 20% more phys damage while dual wielding

### PR DESCRIPTION
**Pull request by stephanabel**
Removed the 20% more physical damage while dual wielding modifier

### CODE REVIEW

**Comment by stephanabel** [comment]
solves #992

**Comment by jeroenroosen** [comment]
I also spotted the mod in data/3_0/Minions.lua, which I imagine is used for e.g. Animate Guardian calcs, should it be removed there as well?

**Comment by LocalIdentity** [comment]
> I also spotted the mod in data/3_0/Minions.lua, which I imagine is used for e.g. Animate Guardian calcs, should it be removed there as well?

Yep, that should go too

**Comment by jeroenroosen** [comment]
@stephanabel will you pick that up in this PR?

**Comment by stephanabel** [comment]
> @stephanabel will you pick that up in this PR?

I updated the PR, thanks for the hint!

**Pull request merged**
