### PR TITLE
Added customisation options for decimal and thousands separators

### PR DESCRIPTION
**Pull request by Leftn**
Not everyone uses the same separators.

This PR plans to help this by adding options to choose which separator character is used when displaying numbers.

Uses the formatNumSep code from https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/244#issuecomment-593084211

### CODE REVIEW

**Review by Wires77 — CHANGES_REQUESTED** [review]
Unchecking the box for show separators (in either location) removes your selection for the decimal separator, reverting back to `.` instead of what you selected.

**Comment by Wires77** [comment]
Sorry, just saw that you updated this.  Since you changed the name of the separator variable, peoples' settings aren't going to persist when they load PoB again.  I'm okay with combining the two page options, but you'll need to check for the old options and select one to go with moving forward.

**Comment by Leftn** [comment]
> peoples' settings aren't going to persist when they load PoB again.

Could I not do something like:

`self.showThousandsSeparators = node.attrib.showThousandsSeparators or node.attrib.showThousandsCalcs or node.attrib.showThousandsSidebar `

So that we can fallback to old variable settings, but default to checking showThousandsSeparators?

> you'll need to check for the old options and select one to go with moving forward.

I'm not 100% sure I understand, do you mean that I should pick either `showThousandsCalcs ` or `showThousandsSidebar ` as the new variable name to use after the variable name merge?

**Comment by Wires77** [comment]
> Could I not do something like:
> 
> `self.showThousandsSeparators = node.attrib.showThousandsSeparators or node.attrib.showThousandsCalcs or node.attrib.showThousandsSidebar `
> 
> So that we can fallback to old variable settings, but default to checking showThousandsSeparators?
> 

Yeah, this is all I meant, by "select one" I meant set the new variable to `node.attrib.showThousandsCalcs` or `node.attrib.showThousandsSidebar`.  What you have will set the new variable to `true` if either of them were set, which I think is fine.

**Comment by Leftn** [comment]
I did an oopsie when trying to merge, and i'm not familiar enough with git to fix... 

I think i'm going to close this PR and create a new one due to my screwup, sorry everyone.

**Pull request closed without merging**
