### PR TITLE
Hide config options that can be hidden by default behind conditions

### PR DESCRIPTION
**Pull request by deathbeam**
Config changes:

- Remove "Is your Crit Chance Lucky?" - The only sources can already be
  enabled with existing conditions and the lucky is implied after that
  (Blood Sacrament, Focus Mod, Dance with Death)
- Only show "# of times skill has chained" if there is condition behind
  it (Gloomfang for example)
- Only show "# of times skill has pierced" if there is condition behind
  it (Drillneck for example)
- Only show "melee distance to enemy" if there is stat that depends on
  melee proximity (Close Combat, Slayer for example)
- Only show "projectile travel distance if there is stat that depends on
  distance ramp (Point Blank, Longshot for example)
- Only show "is enemy bleeding" if there is condition behind it
  (Bloodletting for example)
- Only show "# of poison on enemy" if there is condition behind it (Vile
  Toxins for example)A
- Only show "is the enemy maimed" if there is condition behind it (Maim
  support for example)
- Only show "is enemy burning" if there is condition behind it
- Only show "is enemy ignited" if there is condition behind it
  (Snowforged for example)
- Only show "is enemy frozen" if there is condition behind it
- Only show "effect of shock" if enemy is shocked
- Only show "is enemy on consecrated ground" if there is condition
  behind it (Bottled Faith for example)
- Only show "disable ehp gain on block" if there are any on block
  effects
- Only show "life regen mode" if there is effect that depends on it (Enduring Cry etc)
- Only show "armour calculation mode" if there is effect that depends on it (armour mastery etc)
- Only show "enemy corpse life" if there is skill that depends on it
  (Cremation, Detonate Dead)
- Only show "# of summoned totems" if there is perstat or enemy mult
  that depends on it
- Only show "is enemy moving" if player has bleedchance
- Only show "Don't disable items" if there are items that are disabling stuff

New functionality:

- ifStat and ifEnemyStat for PerStat and StatCondition config checks
- ifTagType for tag type config checks
- if SkillData for skill data config checks
- config tab now supports multiple if checks at once
- Replaced all ifXList with support for type checking the value so if value is list it will be treated as list of OR checks. This works for all ifX conditions in config tab instead of only specific ones that had list support before
- Do not account for "Base" mods (mods from CalcSetup) as actual used
  conditions as they are used only as descriptors for what the mods do
- IfMod can now only account for presence of mod regardless of flags and conditions

### Link to a build that showcases this PR:

https://pobb.in/8dGpjGCyF-w7

### Before screenshot (empty pob):

image

### After screenshot (empty pob):

image

### CODE REVIEW

**Comment by deathbeam** [comment]
Also added hiding for "disable ehp gain on block" only if there are on block mods present

**Comment by deathbeam** [comment]
Also added support for hiding:
- life regen mode
- armour calculation mode

And changed all the ifXList to support type checking the value and treating lists correctly as list of OR checks. This also applies to all ifX options not to just specific ones with ifXList support

**Comment by deathbeam** [comment]
Added also hiding for enemyCorpseLife. This is last of the "relatively easy to hide" config options that I found I think.

**Comment by Regisle** [comment]
> Also added hiding for "disable ehp gain on block" only if there are on block mods present

that config option also disables on suppress as well, so needs to show if those are in build

**Comment by deathbeam** [comment]
Ah completely missed that, updated (also updated the label and tooltip of the option to also mention suppress while at it)

**Comment by Nightblade** [comment]
Will there be some mechanism to override/show all these?

**Comment by deathbeam** [comment]
Not planning anything like that for this PR at least. But also all of the option this PR is hiding do not do anything when checked anyway except the crit lucky one without them actually enabling anything that is already in the build, so I dont rly see the need either

**Comment by Nightblade** [comment]
Oh OK, carry on then!  👍

**Comment by deathbeam** [comment]
Another additions:

- Only show "# of summoned totems" if there is perstat or enemy mult
that depends on it
 - Only show "is enemy moving" if player has bleedchance
 - Do not account for "Base" mods (mods from CalcSetup) as actual used
conditions as they are used only as descriptors for what the mods do
- IfMod can now only account for presence of mod regardless of flags and conditions

**Comment by deathbeam** [comment]
Added autohiding for new "Don't disable items" config option, now it only shows if there are items that are disabling anything (from #5664)

**Review by LocalIdentity — APPROVED** [review]

**Pull request merged**
