### PR TITLE
fixed modifiers to "[Any Damage] with melee skills" not working for DoT

### LINKED ISSUE #7705: % more Physical Damage with Melee Skills not affecting ignite damage
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### Check for support

- [X] I've checked that the behaviour is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What platform are you running Path of Building on?

Windows

### What is the behaviour in-game?

% more Physical Damage with Melee Skills (new stat from 3.25 War Banner) should affect ignite damage with physical to fire conversion, similarly how to how "% more physical damage with fire skills" already does in path of building.

### What is the behaviour in Path of Building?

% more Physical Damage with Melee Skills (new stat from 3.25 War Banner) only affects the hit damage, not ignite damage.

### How to reproduce the issue

Paste the different stats in the calculator custom box with some phys to fire conversion.

100% more Physical Damage with Melee Skills (doesn't work with ignite)
100% more Physical Damage with Fire Skills (works with ignite)

### Character build code

```shell
https://pobb.in/KKjxT0UXP0it
```

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by DieMango**
Fixes #7705  .

### Description of the problem being solved:
Changed the Flag of the mod "with melee skills" from:
ModFlag.melee -> SkillType.Melee
### Steps taken to verify a working solution:
- creating a custom modifier "100% increased physical damage with melee skills" (and with more)
- check with all damage can ignite/poison and 100% bleed chance for all DoTs

### Link to a build that showcases this PR:
-
### Before screenshot:
-
### After screenshot:
-

### CODE REVIEW

**Comment by DieMango** [comment]
I accidentally pushed to the same branch where I had a PR open.

Description of the problem being solved:
added support for Ambush by creating a statMap in /src/Export/Skills/act_dex.txt that creates a GlobalEffect "Ambush".
Link to a build:
https://pobb.in/WHBCnFfCHtUJ
Before Screenshot:
image
After Screenshot:
image

**Comment by LocalIdentity** [comment]
@DieMango I can revert the commit for you and you can open another PR for the ambush changes

**Comment by DieMango** [comment]
That would be perfect thank you.

**Comment by DieMango** [comment]
I created a standalone branch and the PR for Ambush.
#7757

**Review by LocalIdentity — APPROVED** [review]

**Pull request merged**
