### PR TITLE
Allows you to see all boxes when viewing many jewel sockets

### LINKED ISSUE #115: Jewel Tooltips Too Tall
Builds with multiple jewels will get tooltips that are too tall/unreadable. It makes it impossible to see what the impact of a jewel in certain slots will be.

It would be nice to have some sort of solution for this, maybe a scrollbar or a mouse wheel scroll?

image

### PR DESCRIPTION
**Pull request by Wires77**
Fixes #115 
Closes #325 since I deleted the old fork

### CODE REVIEW

**Comment by Wires77** [comment]
Any issues with this PR?

**Comment by Wires77** [comment]
This is ready to merge again

**Comment by Wires77** [comment]
Build code to test with:

eNq1W21z4jgS_jz8ChdVd3Vba4gl2bKdS3YrAZJhJkwIZCaT_TKlGAHe2BaxDYRs7X-_lg3BEF5Ebna3ioDcr4-6W93y7snvz2GgTXic-CI6LaOqUdZ45ImeHw1Oy19vLypO-fffSidtlg6v--djP5BPfit9OMm-awGf8AD4ylrK4gFPvy0kkR8g6YFFPT_9IuKQAdEXEfHFWovHnh_wJFksewFLki8s5KflrgcSyhpLPB71asv1nDBkftQV3iNPL2MxHmW6RyxKh1xELT8S8aXoLWhf19mfK-sTn09bogcym632ded2YVUtHvOFoeDjh5N2wGY87qYs1RL4OC2fAVRswOsshE8QxIIxSEEurhoIUQsj03Bp-Wgzc3fEeW_JVHUR-gmk7Zg3-n3upf6E12JwYsgib2kbrZrbOA-nbo2D1B8FPo8LtlnbOD6-EY8MYxvxrUhZUG93X2kJpVWXmJja2ETE2c0n0le-rRru_HTYFn4ioneoqYnwwY947_9gPZsMDmVtsYjVRKLgXDddbgnGW7ekw5-KlNbWqKrz56U86uyQV6Tcal4zUvABhBXptht35fd5wVt3RxZ5x5K4GXn71UvCr1HMEx5PCsm3Q_4qRxtqGi_YvyPYJWOHD3i01FLdreaKc294CbWvw1K-3xcZOEtDsL0TIUlcRIjgXWI3QLRDwSrHARBJxlWISJXuIj4QoUbE48GsO_R5UHDEcHYiVWQqIoapippVd5QsO9SpCUuyw3M_vrk_Of2KK1sPgBYPOAeOHl-r6ib6iSztWPwpD7PgQL6zOBTjZWUjNt7peU5edNzcClV7OEt8D06Z7NTv8N4Y7Cug7JCt-7E4mFtiwkOI_Oxch9ajcHwaW4v1eQB9zvoJuitAg2ATy1a_ztKUeY910RtwVZZMyUEcF34MkCV-4RCrbC8wNSHTRJX6yh8M0wga0gMUDJlI1snp9q0XUx4DD_S2yX5fi9QttjwWt8bHRcyjl5my_BVyJQWNqDeO5UYp61jneKvm5Cjr_eW3ZjgScZot1ljgJZnIZjQap1qU9ezJox8EP6Jx-CBbxvyvbNmP3lCGfuL9eBj3-7IxL4MxcTaCNC4uGrXb5rfGnKXLs9zTPBEEbJRw6OkjPyhrPnzpSmVdKDleqkAN3em8jd9PK_tLBf1Z076fTnbSCmQALgu4qt-3sxGX25iouT5P3_2054GaU3lnreLWIPJTJdC5x2YKdK9npAJtI-BnfiArsQpOLYjJvISrUEM5jf2HccpViLMWVsEC2ccpuFVsZhQszc9KBbnzfmI_5bykqsQTnFCK2Nd5n0OUquCZp_Ite-TRvEgtCtJJlh6JlkCluuRhcj6DGe5CIrU21a0QnJbTeAx1qMf7DIZeWL8Zs8BPZ3Ody_Wr_AokW02GYtodj0a5JJmSCaB9dZWbdBtzrrGsH5A9iKyDuV_wo3jd0ezJ-qxFUAiB3SaOoxPXMZEO7Sl2deIQ09ERtW1LN11kOzo2XMfWMTGwrcNkSUydmKZDdIyATSe267o6Ja5NdeQYhOiWhVxDN7FNDZ0aBnwHHtPWLQebpo4dQuCpSw1Lt-FTtwyHYp0Q-Kub1EWGjilyQZiLgNy0sYWkgRQ-4Y-rI8sEVmoRIHcc7EhWE2xFmIJuw8RYx9i0iU6xYeoUgT8g13Bh2SUWLBPHJMBq21KAiaUj0mwXgShsg35kSc0UZ3a6EgGpy8QG1i2KKDhlEwugcBywybSwblqG9IAS-E0tMB2oADEXATIWwQjsQi4oAvSkNPBPykMZetSVCrH0CyEJEuADIGGMwHYTuTo2Kdhr4UyHZRkgBvRLGsuWnlkg0kYIbIPNAt3IdEE3kqg5FJAF0AFNQmwTFBmm3BrHpmCGY8IWEwtDAJhE2kttkEINQFnaZctrN4ipwqUbQvOrtDyGZHh9OPnaucq-fBim6Sg5PjqaTqfVEUuHos-fodGueiI8GgETBGYlO7ErUuzRGfxznn28eCFtPN3-8b11c98_uww-2nf96_alYC_feO3rw49IdKKP34Mnr0njmKDKdePhKT5_7jj3z0-0Zl15lT-CzufZlX8b2neN59tpenn_VJk0W59E90fDDfqfLusvz3580_KeIuvepp8n3V738831Xd-5tz-fD--mL-LMfpo9XfTrads669S_TzuB-NKvPw5-fCLN9otLPgN0l3cXT0n4qUXP-492_Q6ArqSDG8e4859cs35X4Wm_-TBrjT5fXT82_7C8y-92rf5S-5NOxPnk2ozuGzeuuLuejB9n3mkG3tECvZP81jHJoZz_ypJUYo0ohtZcg5MtzKE_2kKHkGUo0GVZoUCHwUUVeRC6rop9pkNtV0UvkaG2l8w1DRWtWdFa0pHtqBAYlxSsk4VPDT0VLyA1LaKyabLsqNBB4VLwNivTCnQY26ZS7BGkFCtQp5GKu8iA0qkSUxQcUYIZ6rOCv1CYqZI8ZCiFMoUTTMkN4hKl1LAtqpKSruWo6IXjQkkvHByOyva6tmuriDNMw1CCD3oBhV2TrYRS4YPjTmk3oLVQCipoSZSCHnoCFTobI7UCqVaCoMcgVAkXU0kvNDZURV7WXKgUIVPe7irIc6E3UdkP6DrVopkq4Ze1SipFAwGhCn6m5SjZJ7tZBb0EUSV5GLuuqXRUukQlTmWfriJODgpv3Tg5KnQ78AMmlGyokiOM_PJFwJgrn8nFxY9swPnm86mWcBZ7w24an5bL2osQ4f1puYKk3XJC-shZ2mKj-cwkH89nKDKfoFKW1n2Yu-Ns-luMYpLwu7yty1-UnDTB5mQ-T8nvXZ5mb4PHCYdJUUS9O85GIsqWpab8ygkItQmLfRalmUI5POZz2IcOLKezY-3rl-bN10apO2QjHv8bZCT_TbRbMfaGpVo8TliPx9plICY8mdNoUmrpWy71WGvHXMNVWjVWl0gVGcW12jgGB9NSfmPFe9rrE1KaD5vHGjZK85041s4r2b-lDK0OfzrWKC01w1Hge758bpT-ilk04MdG1fr7P45RQdj45V-aH3kxZzAua_ncr7Gop-U3Blp-ZVD6a47IMfr7V6yded44Zt5M67DUjwaa9BBrzSjlQeAP5J4sGWDi-ftXU4XlV6TJS4_skanV-XPKJdwF3VIU0uSVx5wIAohHg3RYUCft20khpaCi0yueZmzI2CgZv4MLrenK70uKKADbduTwe5nX9GbvWbTFewotvwxZSNgA9RvdigJkZWiJXkdGmZbFGpSWqrXIovya5khmw4ZkwzkZ3phsbZg6WayJvpYOuVYD7T3tUvRKzRgQgYLQ7-_Mr-25hHfm0lo-IVLMJ7yCN-CVX5pqqdCyWywtf4GyQGs6hFlam8qAkfvH5mYXIgw575SBVrOYMwlUfjMpv2Ur82uuLPPWwmaVPVeYXVa_3WFEi7SvAZGX0rW4eE2Ht5vuZ2fJpo0-j9k0gjrqhwkI_MSnPNhew8wKXSlghVDeQbVM0wIRgnJoAVksX98B0QpAKnG9gwLvpSCbc0M-MjfC1AgBZPF6-tTGkXzPVfrmx34PomkO3JUf-jLaUwGxuwojNoqQwHH1ANu4VqaLAJEiuXz3AwcrbHPXf-GKW_LPQWSpQNRiCRgyK7VjPwnBPW8_RmbRkZA9--E4zA6p0i40rA3ALm6qV6CyKvYva5k3f0GwGwlzOxJUCQn5WnQtxXaggFYiJU_xnxEZhfLwTwWGrQLHnQ9gyF1K92NBNmWNfF-XVUHwyH_k8xL-MyBSL0LvgakbiMXb1bxdXfb5i7O6QDIv8YXZYvESfd5cb22siz20gtJNWnF3ykba2cMsSSTO-YyyYZwssp5z2NHDWC4CljxqZDfRLpPQbtaPPAh5-lOYsJKR6EBdErP3CVazBx-6h0Kkybs20dxNlMfegejkkvdBKHqzxSR1mOFn4TjgqQIg74MavQNqdHiKKWGoGL3vyPpdrEgNOJV0VNwCaYVyuCgm3n6ZHTkb4PckAH53bCttu6Vgt9ombTiGjubnUHYRlV3-ZP_dkYj6_gAoTo7W_yeF_wGjYpxz

**Comment by LocalIdentity** [comment]
Had a bit more of a look and with a build like this https://pastebin.com/5aghh31T (Herald stacker from last league) the tooltips can get very large. Noticed that PoB still shows the very long vertical scroll bar for the tooltip as if it was still using the current vertical tooltip box and is not adding a horizontal scroll bar like it should. If these 2 issues are sorted out then it seems like the PR would be ready to merge

**Comment by Wires77** [comment]
Fixed the immediate scrollbar issue, though the code isn't as nice as I'd like.  Plus while debugging I noticed the bottom border of a tooltip gets cut off.  It's too late here to make my brain do that math properly to find the error, so I may commit a bit more to it tomorrow.

**Comment by Wires77** [comment]
This is ready for approval/merge again

**Pull request merged**
