### PR TITLE
Implements Combat Rhythm Cluster Notable

### LINKED ISSUE #402: Implement Combat Rhythm Notable
All mods don't parse

```
10% increased Attack Speed if you've Hit with your Main Hand Weapon Recently
10% increased Movement Speed if you've Hit with your Off Hand Weapon Recently
```

### PR DESCRIPTION
**Pull request by Nostrademous**
Closes #402

### CODE REVIEW

**Comment by Wires77** [comment]
Can't you just make these check two conditions instead, "HitRecentlyWithWeapon" and "DualWielding"?

**Comment by Nostrademous** [comment]
Yeah, but that makes it work very specifically just for that cluster Notable only. The way it is done now will make it work for future modifiers that specify main hand recent hits or offhand

**Comment by Nostrademous** [comment]
Also, that modifier should still partially apply if you weren’t dual wielding

**Comment by Wires77** [comment]
Sorry, I more meant a combination of the two flags, different for each line still.  HitRecentlyWithWeapon alone would suffice for the first one, and combining both would work for the second line (since you can't hit with an offhand weapon without dual wielding).

The problem with doing it this way is not being able to see this cluster jewel notable appear in a list of DPS increases (at least until you equip it, select the node, and check the config box).

**Review by LocalIdentity — APPROVED** [review]

**Pull request merged**
