### PR TITLE
Update perfect agony keystone

### PR DESCRIPTION
**Pull request by Paliak**
### Description of the problem being solved:
Updates perfect agony keystone to 3.25

This could use a glance over from someone more familiar with ailment calcs.

### CODE REVIEW

**Comment by lundburgerr** [comment]
Was just about to create my own pull request for this! :)
I noticed that you get the same bug as I do. The tooltip calculation for chance to bleed when you hover it is correct, but is then ignored completely, this does also affect the damage calculation, see screenshot
Screenshot from 2024-07-20 12-34-55


This also seems to affect the calculated damage for bleed as it ignores perfect agony. Your tooltip also doesn't show the derivation from crit and non-crit damage, compare between yours and mine:
Screenshot from 2024-07-20 12-37-53
Screenshot from 2024-07-20 12-06-45

I also had a similar issue with chance to chill, where the chance was just 0% in every case even thought he tooltip calculated it correctly.
For reference, this is my branch: https://github.com/PathOfBuildingCommunity/PathOfBuilding/compare/dev...lundburgerr:PathOfBuilding:perfect_agony

**Comment by Paliak** [comment]
>I noticed that you get the same bug as I do. The tooltip calculation for chance to bleed when you hover it is correct, but is then ignored completely,

The value shown uses the adjusted crit chance while the tooltip uses the crit chance shown in the left bar:

https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/9481c10746f58e73f72572363ae6891129a95200/src/Modules/CalcOffence.lua#L3695-L3700

https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/9481c10746f58e73f72572363ae6891129a95200/src/Modules/CalcOffence.lua#L3716-L3721

Would need to dig into the reasoning behind:

https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/9481c10746f58e73f72572363ae6891129a95200/src/Modules/CalcOffence.lua#L3911-L3912

>tooltip also doesn't show the derivation from crit and non-crit damage, compare between yours and mine:

Don't see much of a point in showing the non crit derivation if you can only apply the crit one.

**Comment by lundburgerr** [comment]
I wouldn't know what an adjusted crit chance would be for bleed and why poison wouldn't have it, I figure there's maybe some convoluted calculation made for bleed though. It's very confusing because you don't see the same discrepancy without PA (and crits don't naturally affect bleed chance). Either way, bug or not, probably independent of your PR.
I definitely don't trust the bleed numbers as is though, someone that knows code should probably double check if the calcs are right.

**Comment by Regisle** [comment]
> I wouldn't know what an adjusted crit chance would be for bleed and why poison wouldn't have it, 

I havnt looked at the PR yet, but bleed uses "stack potential" (fishing for a higher roll bleed), for poison all poisons deal damage and so the high rolls and low rolls cancel each other out

**Comment by lundburgerr** [comment]
> > I wouldn't know what an adjusted crit chance would be for bleed and why poison wouldn't have it,
> 
> I havnt looked at the PR yet, but bleed uses "stack potential" (fishing for a higher roll bleed), for poison all poisons deal damage and so the high rolls and low rolls cancel each other out

It does make sense for the damage calculation to be complex since you have a cap on stacks. I don't understand why the displayed bleed chance in the Calcs tab without PA is just your "normal" chance to bleed, while with PA it's not just your normal chance to bleed times crit chance. Fishing for higher rolls would be true whether or not you use PA.

With PA (crit_chance*bleed_chance=2.4%, but bleed chance shown is 11%):
Screenshot from 2024-07-20 14-10-54

Without PA (bleed chance shown is the same as bleed chance in tooltip) :
Screenshot from 2024-07-20 14-10-29

**Comment by Paliak** [comment]
@lundburgerr 
> Fishing for higher rolls would be true whether or not you use PA.

It is applied it's just the breakdown not using the right values. See [5269862](https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/7725/commits/5269862faa22e1358b8cee78ae5152916a92f3b3). Only thing is that the used formula could be explained better.

**Comment by lundburgerr** [comment]
Yeah I think I understands what's happening now

https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/9481c10746f58e73f72572363ae6891129a95200/src/Modules/CalcOffence.lua#L3912-L3915

For the bleed calculation an intermediate value `ailmentCritChance` is calculated for the bleed chance that compensates for bleed being capped on number of stacks. The same snippet does not exist for the other ailment calculations.

And then in the function `calcAilmentDamage` the entire snippet under `if breakdown and chance ~= 0 and not hideFromBreakdown then` calculates the tooltip chance using the normal crit chance. Whereas `output[type.."Chance"] = chance ` is calculated using the  `ailmentCritChance`.

https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/9481c10746f58e73f72572363ae6891129a95200/src/Modules/CalcOffence.lua#L3694-L3723

So I'm pretty sure the damage calculations are correct, it's just the bleed chance calculation used that I personally think is very confusing and it would be better to use "normal" bleed chance in the calcs tab. But that could be in another PR if desired.

**Comment by lundburgerr** [comment]
> It is applied it's just the breakdown not using the right values. See [5269862](https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/7725/commits/5269862faa22e1358b8cee78ae5152916a92f3b3). Only thing is that the used formula could be explained better.

I'd prefer the opposite (keep the tooltip, modify Calc tab value), but I'm also not gonna argue about it :) Good job

**Comment by Paliak** [comment]
> > It is applied it's just the breakdown not using the right values. See [5269862](https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/7725/commits/5269862faa22e1358b8cee78ae5152916a92f3b3). Only thing is that the used formula could be explained better.
> 
> I'd prefer the opposite (keep the tooltip, modify Calc tab value), but I'm also not gonna argue about it :) Good job

Then it would ignore the stacks cap as it would use the non adjusted crit chance

**Review by LocalIdentity — APPROVED** [review]

**Pull request merged**
