### PR TITLE
Add support for changing item quality in the standard edit item interface

### LINKED ISSUE #5791: please add quality modifying dropdown so we can stop editing items to check what quality beyond 20 gives.
### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Is your feature request related to a problem?

Currently to adjust the quality of an item, or even base def %'s(currently decimal format and not the actual values, but that's fine) you have to open the item, click edit, find quality/base def%(as not all items start at 100%(aka 1) when creating items for whatever reason)  and manually adjust in there.

### Describe the solution you'd like

simply add drop down box or a slider somewhere to adjust these two, or at least quality % as sometimes I just want to see if its really worth it to me going through the steps to get it higher(hillock/tainted currency/beast altar corruption, sacred orb etc...) as in some cases(especially evasion) getting a little extra ultimately gives you nothing in return.

can do the same thing catalysts get on armor/weapon pieces for a quality slider so we can easily see if a specific quality % hits a breakpoint were shooting for.

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by hexeaktivitat**
Resolves #5791 by adding the feature requested.

### Description of the problem being solved:
Adds a text input box to control the quality of items. Opted for a text input box over proposed slider to match gem quality better and to avoid the need to set a maximum value on item quality.

### Steps taken to verify a working solution:
- Verified that it works for relevant gear and flask items
- Verified that it does not display the interface when working with jewellery, jewels, or quivers
- Verified that updates to item quality in the box affect the item statistics and adjust the parameters accordingly

### After screenshot:
screenshot_2023-04-04-10:23:56

Sample interface with increased quality values

screenshot_2023-04-04-10:11:48

Flask variant

screenshot_2023-04-04-10:17:47

Does not display on quiver item

### CODE REVIEW

**Comment by QuickStick123** [comment]
I get this crash when trying to make an amulet on your branch.
image

You should also probably make the format for quality consistent across catalysts / regular items as well. But I am unable to tell if you have done that because of the crash.

**Comment by hexeaktivitat** [comment]
Pushed a change to address that, seems odd that it would break on amulets specifically.

I didn't change anything with the amulets, apologies. I figured it would be better to leave them as they were, but consistency makes sense. Will work on that now.

**Comment by Wires77** [comment]
Amulets are fixed, but now it looks like something broke with other items.  Trying to edit a shield, bow, and a chest piece result in a similar error.  I also get this error when crafting an item: 
image

**Comment by hexeaktivitat** [comment]
Finally got the time to figure this one out; hopefully this resolves the outstanding issues without adding some new bug. Also happy to refactor the logic if needed. :relaxed:

**Review by Wires77 — APPROVED** [review]

**Pull request merged**
