### PR TITLE
Interpret pastebin link varations from YouTube descriptions

### PR DESCRIPTION
**Pull request by zao**
When copying a pastebin link text from YouTube it may append a `?` to the URL, failing to match our patterns. This fix strips the stray question mark after trimming whitespace.

### CODE REVIEW

**Comment by zao** [comment]
Given a video like this https://www.youtube.com/watch?v=fhAYWkooxBg, there's links to PoB pastebins in the description.

When you right-click and copy link, you get a long tracking URL like:
`https://www.youtube.com/redirect?event=video_description&redir_token=QU...TQ&q=https%3A%2F%2Fpastebin.com%2FBpywmgEZ`

If you instead hand-select the text of the link and copy that to clipboard, the result varies across browsers.
Firefox produces `https://pastebin.com/BpywmgEZ​?` while Edge (Chromium) produces the more expected `https://pastebin.com/BpywmgEZ​`.

This has been a recurring user-facing problem seen on stream when newcomers fail to import the build.

**Review by Wires77 — COMMENTED** [review]
Can we make this pastebin-agnostic?  Thinking of all the merge conflicts this will have with #2537

Could replace URL-encoded values and strip out the youtube part of the URL instead, so if a youtuber posts a link to one of the other sites it could work the same for that

**Comment by zao** [comment]
Oh, I was unaware of the work made in that PR, only checked for conflicting implementation work internally.

It might be possible, depends on how much goes into robustly parsing and decoding the query parameter.

**Comment by zao** [comment]
This PR now instead detects a YouTube redirect link, extracting an arbitrary URL from the query parameter and prepares it for further processing regardless of which site it refers to.

**Review by Wires77 — APPROVED** [review]

**Pull request merged**
