### PR TITLE
Relabel "Total DPS" to "Hit DPS"

### PR DESCRIPTION
**Pull request by raylu**
### Description of the problem being solved:

total, combined, and full DPS carry a bit of baggage and are confusing

### Steps taken to verify a working solution:
- created a build with hit, bleed, ignite, poison, decay, impale, cull, and mirage archer
- checked stat comparisons by mousing over gems/items

### Link to a build that showcases this PR:
https://poe.ninja/pob/Kf4

### Before screenshot:
image

### After screenshot:
image

### CODE REVIEW

**Comment by QuickStick123** [comment]
Does third party software rely on this being total dps or is this purely cosmetic e.g. poe.ninja

**Comment by raylu** [comment]
as @Regisle mentioned in discord, purely cosmetic. I exported from my branch to ninja: https://poe.ninja/pob/KgX

the exported XML (https://github.com/raylu/poegemplan/blob/main/pob.py) says
```xml
<PlayerStat stat="TotalDPS" value="315.56533292936"/>
<PlayerStat stat="TotalDot" value="0"/>
<PlayerStat stat="BleedDPS" value="25.545212452977"/>
<PlayerStat stat="WithBleedDPS" value="341.11054538233"/>
<PlayerStat stat="IgniteDPS" value="101.72445725055"/>
<PlayerStat stat="WithIgniteDPS" value="417.2897901799"/>
```

**Comment by mw-stanley** [comment]
I think "Average Damage" would be clearer if it was "Average Hit Damage" too?

**Comment by raylu** [comment]
> I think "Average Damage" would be clearer if it was "Average Hit Damage" too?

wow I just noticed that attacks have "average damage" but spells have "average hit"... not sure exactly what to do here. to me, they're conceptually both "average hit damage", but it feels weird to label to separated things the same

**Comment by QuickStick123** [comment]
Yeah I would just convert them both to average hit damage.

**Review by LocalIdentity — APPROVED** [review]

**Pull request merged**
