### PR TITLE
Improvements for Power Report

### PR DESCRIPTION
**Pull request by Mamotromico**
- [x] Add distance value on power report
- [x] Add cluster notables to the list
- [x] Allow filtering of cluster notables

Partial implementation of  #1497

### CODE REVIEW

**Comment by Mamotromico** [comment]
#

**Comment by Mamotromico** [comment]
Preview

**Comment by olafurw** [comment]
This is amazing.

**Comment by Mamotromico** [comment]
I believe I have everything suggested on #1497 barring the cutoff on distance, which I plan to do on a later point

**Pull request merged**
