### PR TITLE
Added a Power Per Distance column for the Power Report window

### PR DESCRIPTION
**Pull request by Lharz**
I was thinking that a Power Gain Per Distance (or Power Gain Per Passive Point) column in the Power Report window would be very nice, so I added one.

I think it's working good and I'm sure I won't be the only one needing this. :)

### CODE REVIEW

**Comment by LocalIdentity** [comment]
The columns need to be widened a bit for the heading for each column to not look like they're overflowing on the edges

**Comment by LocalIdentity** [comment]
Consider renaming it to Power per Point. There's also the issue when sorting by the power per distance that anoint only notables are weighted much lower than they should be.

**Comment by Lharz** [comment]
Indead. I'll try, won't be very easy as I can't open the console on AZERTY keyboard, so debugging is hard.

**Comment by LocalIdentity** [comment]
You can use an actual debugger which should help you a lot. Send me a message on Discord (LocalIdentity#9871) and I'll invite you to the PoB discord server we have

**Comment by nls0** [comment]
It should include the power gained from traveling to the node as well. Right now, it just divides the power of the node itself by the distance.

**Comment by Wires77** [comment]
> 
> 
> It should include the power gained from traveling to the node as well. Right now, it just divides the power of the node itself by the distance.

This is taken care of in #2250 

Power per distance column is also included in that PR, so this one is unnecessary.

**Pull request closed without merging**
