### PR TITLE
Fix: Added area baseflag to Chain-Hook

### PR DESCRIPTION
**Pull request by pundm**
chain-hook seems to be missing the area base flag

before picture in #2224 

after:
image

### CODE REVIEW

**Comment by pundm** [comment]
It was only showing me one changed file, now its 2 more here, i will see how i can fix the pull request. Sorry

**Comment by Wires77** [comment]
That's because I just forgot to merge a couple commits back into dev from master, so basing your branch off of master pulled those in.

**Review by Wires77 — CHANGES_REQUESTED** [review]
You need to make the same edit to Export/Skills/act_str.txt.  This file you edited is auto-generated by the exporter, and will get overwritten if the other file isn't changed as well.

**Comment by pundm** [comment]
Hey, i added the area tag in Export/Skills/act_str.txt
Sorry I'm a noob but i dont know how to get rid of the other 2 changed files. Should i delete the PR and try to make a new one from clean dev?

**Comment by Nostrademous** [comment]
LGTM

**Review by Wires77 — APPROVED** [review]
> 
> 
> Hey, i added the area tag in Export/Skills/act_str.txt
> Sorry I'm a noob but i dont know how to get rid of the other 2 changed files. Should i delete the PR and try to make a new one from clean dev?

Nope, you're good.

**Pull request merged**
