### PR TITLE
+Flask effect works with silver flask

### LINKED ISSUE #5242: Increased flask effect does not affect onslaught on silver flasks
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Check for support

- [X] I've checked that the behaviour is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What is the behaviour ingame?

As of 3.20, flask effect should scale onslaught. Onslaught currently scales with buff effect which was previously a bug but now intended, but flask effect still doesn't work.

### What is the behaviour in Path of Building?

No scaling from flask effect.

### How to reproduce the issue

Add silver flask, give yourself increased flask effect.

### Character build code

```shell
https://pobb.in/Doj5hDzqky0I
```

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by Fabere456**
Fixes #5242

### Description of the problem being solved:

PoB would not take into account +Flask effect when calculating silver flask onslaught. This change adds a check when calculating onslaught and adds flask effect to the equation if a silver flask is active.

### Steps taken to verify a working solution:

- Checked +flask effect increases relevant stats when a normal or magic silver flask is active
- Checked other flasks are not adding relevant onslaught stats when active
- Checked onslaught from sources that is not a silver flask is not benefited 
- Checked if onslaught is allocated from a non silver flask source and a silver flask that the +flask effect is still properly active

### Link to a build that showcases this PR: 
https://pobb.in/MdzvxLSfWxbr

### Before screenshot:
Before

### After screenshot:
After

### CODE REVIEW

**Comment by QuickStick123** [comment]
This has a problem with flask effect on the flask not applying everything else seems fine including explicit mention to silver flask as effect doesn't apply to onslaught from rotgut for example.
image

**Comment by Fabere456** [comment]
Newest commit should fix the increased effect on a flask itself.

Are you saying rotgut is an issue? Just want some clarification.

Also with this implementation if there is a silver flask with reduced effect and another source of onslaught the flask will override for a worse onslaught which is not what should happen. Not sure how large of an issue this is because why would someone run a reduced onslaught flask with another source of onslaught, but it is an issue none the less

**Comment by Fabere456** [comment]
Just added in the break

**Comment by Fabere456** [comment]
So is this good to push? I've tried to fix the error with lower flask effect overriding another source of onslaught but I can't figure it out. So if that is to detrimental I'll probably just close to keep the request tab clear

**Comment by QuickStick123** [comment]
This is in a good enough state to merge tbh if you wanted flasks to apply the strongest or weakest just store the Max/Min silver flasks effect by iterating over them and if there is a silver flasks applying this effect. To handle the edge case of reduced flask effect always overriding current onslaught you can probably look at the source variables of the onslaught to see what is applying it and do some logic there.

**Comment by Fabere456** [comment]
Newest commit should make it so the highest flask always applies and activating a lower flask doesn't lower damage. I don't really know how to check all the sources of onslaught to make it properly override a lower flask if there is another source

**Comment by QuickStick123** [comment]
The functionality looks good you just have two typos

**Review by LocalIdentity — APPROVED** [review]

**Comment by c20k20w** [comment]
This calculation does not factor in MagicUtilityFlaskEffect in modDB:Sum("INC", nil, "FlaskEffect")
which are present on old Sentinel belts and Pathfinder's Master Alchemist node
an existing calculation exists on [line 1504](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/dev/src/Modules/CalcPerform.lua#L1504)

**Pull request merged**
