### PR TITLE
Issue 1633 - Fix Voidforge wording

### LINKED ISSUE #1633: Voidforge not imported correctly
The Voidforge in the unique item list has
Gain 300% of Weapon Physical Damage as Extra Damage of an Element

However, the real Voidforge has
Gain 300% of Weapon Physical Damage as Extra Damage of a random Element

Which is not a mod understood by PoB. This can lead to confusion when importing a Voidforge build.

### PR DESCRIPTION
**Pull request by Wires77**
Fixes #1633

### CODE REVIEW

**Review by ppoelzl — CHANGES_REQUESTED** [review]
We have to keep outdated wordings in the mod parser to not break old builds.

**Comment by Wires77** [comment]
Fixed, though I wish we had a way to update old wordings if it's our mistake, otherwise we have a bunch of dead code in here purely for backwards compatibility.

**Review by ppoelzl — CHANGES_REQUESTED** [review]
I'd prefer you to leave the old mod untouched.

**Comment by Wires77** [comment]
I don't see the point in having two lines we have to maintain in the future when this change works perfectly fine.  In fact, it'd be even better to have "weapon" as an optional qualifier and combine it with the lines below it.

**Pull request merged**
