### PR TITLE
Add Armour Cruncher Spectre

### PR DESCRIPTION
**Pull request by fialhoFabio**
Fixes #5131.

### Description of the problem being solved:

Armour Cruncher was missing from the spectre list.

### Steps taken to verify a working solution:
- It wasn't on the list
- Add to the Spectres.txt and generate code
- It is on the list now
- Numbers are correct, but the curse on hit effect is not getting applied

### Link to a build that showcases this PR:
https://pastebin.com/EUxKfbDe

### Before screenshot:
image

### After screenshot:
image
image

### CODE REVIEW

**Comment by fialhoFabio** [comment]
I don't know how to make him apply vulnerability on the calcs
idk if have something to do with this commented mod

image

**Comment by fialhoFabio** [comment]
btw i saw the PR #5131, and thought it was a good first issue to try.

**Comment by QuickStick123** [comment]
See SeawitchVulnerability as how you would go about implementing curses on spectres.
image
image
image

**Comment by fialhoFabio** [comment]
I don't think that the Sea Witch is a comparison, she has a skill that apply vulnerability, but the armour crusher has a mod that apply it on hit, and i can't find a spectre that do the same thing.

image

**Comment by fialhoFabio** [comment]
Well i kinda found something similar, like the blackguard mage that have spellBlockChance mod on him... idk

image

**Comment by QuickStick123** [comment]
Yeah it might be new case there currently isn't anything like it in the codebase atm. So if you want to properly support it you could try to figure out minion trigger stuff which mightn't be supported ? not sure. 
Here is the current curse on hit stuff.
image


If you want to be able to more easily ask people questions about how you might implement this stuff join the discord by asking one of the maintainers to invite you.

> There is a [Discord](https://discordapp.com/) server for active development on the fork and members are happy to answer your questions there. If you are interested in joining, send a private message to any of Cinnabarit#1341, LocalIdentity#9871, Yamin#5575 and we'll send you an invitation.

**Comment by fialhoFabio** [comment]
Idk if this is the correct way of increase the curse effect, but 30 * 1.04 = 31.2 and that is +2 gem lvl

**Comment by fialhoFabio** [comment]
image

**Pull request merged**
