### PR TITLE
Max hit improvement

### LINKED ISSUE #1645: Maximum Physical Hit Taken is calculated using incorrect logic
In the Calcs tab, "Damage Taken" section, the line item for "Maximum Hit Taken" is calculated by taking your total EHP pool, and dividing it by your damage taken modifier, as it should be.

However, for physical damage, the damage taken modifier is calculated according to the hit configured in the Configuration tab. Normally this is fine, but this in the case of max hit taken definitely has issues. With a configured hit size of 1k, my character might say my max hit taken is 30k. But if my character were hit for 30k, it'd be dead several times over because my mitigation is much less effective against the 30k hit.

Expected behavior would be, given the function DT(h) which returns the damage taken modifier for a give hit size h, this line item would show the solution to the equation EHP/DT(h) = h.

### PR DESCRIPTION
**Pull request by Edvinas-Smita**
Fixes #1645 ~~#4847~~.

### Description of the problem being solved:
Max hit taken should not depend on enemy damage. This aims to fix that by changing how max hit is calculated.

### Steps taken to verify a working solution:
- Flat damage reduction (i.e. endurance charges) checked at low, mid and extreme values
- Overwhelm checked at low, mid and extreme values
- Damage taken as checked at low, mid and extreme values
- Transcendence and/or unbreakable checked
- Damage taken-as was kept in mind
- Math?
- Spreadsheets

### Link to a build that showcases this PR:
https://pobb.in/KAH_0AClx7EI (stolen from poe ninja)

### Before screenshot:
Damage reduction for reported phys max hit (88% taken as phys = 108690) results in 2608539 / (2608539 + 5 * 108690) = 0.82758 reduction. Plugging that back in for damage received from physical portion of the "max hit" results in 108690 * 0.17242 * 1.1 (Aspect of Carnage) = 20614 damage. This character has total pool of 11956 (molten shell). Seems pretty dead to me.
image

### After screenshot:
Damage reduction for reported phys max hit (88% taken as phys = 79898) results in 2608539 / (2608539 + 5 * 79898) = 0.86719 reduction. Lightning portion (10895 damage) after resists and penetration (1852 dmg) gets a 208683 / (208683 + 5 * 1852) = 0.9 reduction. Plugging that back in for damage received results in (79898 * 0.13281 + 1852 * 0.17 * 0.1) * 1.1 = 11707 damage. Not quite exact, but better?
image

The discrepancy happens due to complexity of calculations when taken-as modifiers are involved. With no conversions this is as accurate as floating point operations and rounding can get. With conversion to a single element, highest observed ratio between the pool and damage taken from the reported hit is ~40%. Converting to two elements go up to ~72%. Element to element conversion is still quite broken.
Some examples of produced deviations:
<details>
  <summary>Flashbang warning</summary>

image
image
image
image
image
image

</details>

### CODE REVIEW

**Comment by QuickStick123** [comment]
This looks pretty good maybe capture the magic armour formula number in a variable
Yes overwhelm probably applies after damage reduction is capped then made sure to not go bellow zero.

**Comment by QuickStick123** [comment]
This does not fix https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/4847 as that was a different issue with enemy armour not correctly setting when changing between modes.

**Comment by Edvinas-Smita** [comment]
My bad with the #4847. I changed changed both of the occurrences of damage reduction capping. Not sure which magic number You referred to, but if it was the smoothing ratio then I made that available in breakdowns.
> good maybe capture the magic armour formula number in a variable

Talking about smoothing I added one more magic step which produces pretty magical results:
<details>
  <summary>Flashbang warning</summary>
 
(orange line is current, red was previous)
image
image
image
image
image
  
</details>

With the latest commit elemental taken-as elemental is also captured and it seems to work much, much better.

**Comment by QuickStick123** [comment]
How well does this fare on the divine flesh / tempered by war if it is with 10% of actual value I think it is good enough to close.
https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/3632
https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/4444
https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/1930

**Comment by Edvinas-Smita** [comment]
Without any armour applying to elemental damage, the max hit is calculated basically within floating point accuracy. With armour applied, max hit stays within 8% error (a bit eyeballed, but easily within 10%).

From #3632 the DoT taken is still broken, as there was no work done here that would have affected it.
#4444 should be fully resolved.
For #1930 I'm not quite sure about the math performed in the initial described issue, but it does look resolved to me.

**Comment by QuickStick123** [comment]
Mostly solves https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/5118

**Comment by QuickStick123** [comment]
Mostly solves https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/4917

**Comment by QuickStick123** [comment]
Mostly solves remaining issues of https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/2264

**Comment by QuickStick123** [comment]
Fixes https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/5223

**Review by LocalIdentity — APPROVED** [review]

**Pull request merged**
