### PR TITLE
Fix Blood offering stats not calculated #744

### LINKED ISSUE #744: Blood offering stats not calculated
The Blood Offering granted by Bloodbound chest armour is not calculated in any way towards the players with Necromancer's "Mistress of Sacrifice" ascendancy node active.

I checked and compared active offerings and blood offering (act_int.lua + other.lua) and I cannot find any indication as to why that would be; their tags are exactly the same apart from cascade, but that's because it's a granted skill and it can't be linked to that.

In game, the ability does provide its perks when the ascendancy node is selected, which from what I can see in the stat description, is correctly coded.

### PR DESCRIPTION
**Pull request by talkmill**
Fixes #744  .

### Description of the problem being solved:
Enabling Mistress of Sacrifice in the Necromancer ascendancy does not apply apply blood offering to the player when Bloodbond is equipped.

### Steps taken to verify a working solution:
Blood offering was not shown, since the effect of Mistress of Sacrifice was set (in ModParser.lua) to affect:
"Bone Offering", "Flesh Offering", "Spirit Offering"

I added "Blood Offering" to the list and rebuilt ModCache.lua, this causes Blood Offering to be applied if Mistress of Sacrifice is enabled (and Bloodbond equipped)

### Link to a build that showcases this PR:
https://pobb.in/neMBDf3Zut_4

### Before screenshot:
image

### After screenshot:
image

### CODE REVIEW

**Comment by QuickStick123** [comment]
This looks good I would consider adding support for the regen and maybe the offer mods as well if you are up to it.
https://www.poewiki.net/wiki/Blood_Offering
image

**Comment by talkmill** [comment]
Good point!

I was a bit unsure about those since they are dependent on two variables (life sacrificed and corpses consumed).
Since life sacrificed is 20% of Life, i guess that can easily be calculated.
Is the right approach for corpses consumed just to add it as a configuration option?

**Comment by QuickStick123** [comment]
Consumed corpses is already a config option
image
You would just implement it like this mod
image
"for each nearby corpse, you and nearby allies regenerate (%d+) mana per second, up to (%d+) per second"
Duration can just be copied from the other skills.

**Comment by talkmill** [comment]
Added the life regeneration based on the consumed corpses option.

The last one (Minions Regenerate 35% of Sacrificed Life per second)seems a bit tricky. It would want the Sacrificed Life as a Mult (which is 20% of the player life), however i can't see a way to calculate this. 
For attack calculations I assume that it could have been calculated in an initialFunc. But i can't find something similar to defensive calculations, is there a smart way to get the playerlife as a multiplier i'm missing?

**Comment by Lothrik** [comment]
Blood Offering in this needs a cap. I'm fairly certain it consumes a maximum of 5 corpses, but I might be misinterpreting the 3.8.0 patch note. Currently it consumes an infinite number of corpses.

The configuration option ``# Corpses Consumed Recently`` should be updated so it displays when either condition (Mistress of Sacrifice is present, or Blood Offering is present) is met. Currently it's impossible to configure the number of corpses Blood Offering consumes without allocating Mistress of Sacrifice.

The ``Regenerate 35% of Sacrificed Life per second`` can be handled like this:
```lua
["blood_offering_%_of_lost_life_to_regenerate_as_life_per_second"] = {
	mod("LifeRegen", "BASE", nil, 0, 0, { type = "GlobalEffect", effectType = "Buff" }, { type = "PerStat", stat = "LifeUnreserved", actor = "parent" }),
	div = 500,
},
```
Unfortunately this does not handle the "10% more Life Regeneration granted to Minions per corpse Consumed" behavior. I'm not entirely sure how to implement that without changing how ``ModStoreClass:EvalMod`` works.

This was the closest I got without editing that function, but it has.. numerous unresolved issues:
```lua
["blood_offering_%_of_lost_life_to_regenerate_as_life_per_second"] = {
	mod("LifeRegen", "BASE", nil, 0, 0, { type = "GlobalEffect", effectType = "Buff" }, { type = "PerStat", stat = "LifeUnreserved" }, { type = "Multiplier", var = "CorpseConsumedRecently", limit = 5 }),
	mod("LifeRegen", "BASE", nil, 0, 0, { type = "GlobalEffect", effectType = "Buff" }, { type = "PerStat", stat = "LifeUnreserved", actor = "parent" }, { type = "Multiplier", var = "CorpseConsumedRecently", actor = "parent", limit = 5 }),
	div = 500,
},
```

**Comment by talkmill** [comment]
Thanks for the thorough answer.
I thought `ifMult = "CorpseConsumedRecently"` should have caused it to show with Bloodbond equipped, however ifMult only looks into base mods. I added a dummy base mod to get it to show, it seems to work, but it is not the most beautiful solution. Not sure If there is any better way of doing it?

For the LifeRegen it seemed to work if i created a new multiplier mod in "blood_offering_%_of_lost_life_to_regenerate_as_life_per_second" that can then be used in "blood_offering_life_regenerated_+%_final_per_corpse"

It adds the liferegen for both player (if Mistress of Sacrifice is enabled) and minion with a 5 corpse limit.  

I tried to compare the stats calculated to ingame, and the numbers seems to almost line up.
Enabling blood offering gave:
27.3 to 156.2 in game, 27.3 to 157.55 in PoB - https://pobb.in/oQqtnhstTpRF

Changing the gear a bit gave:
23.1 to 132 in game, 23.1 to 133.2 in PoB

So there is still a slight mismatch, but not sure if it's small enough to be a possible rounding error?

**Comment by Wires77** [comment]
That's definitely a rounding error.  I was playing with the calcs here and found that it was flooring the intermediate value to the tenths place.  E.g. For the build you linked, 173.6 was my base regen, and the extra regen for 4 corpses was 69.2.  173.6 * .1 = 17.36, and 17.3 * 4 = 69.2.

I agree the code is a bit messy, and was wondering if a pre-function would be appropriate to avoid both issues.  Another thing I was adding was support for the 20% in case that becomes a different value in the future.

Weird that the patch notes say 4 corpse limit, but if in-game testing shows 5 being the limit, that sounds fine.

I'll push my change to this branch.  The other thing I added was support for duration scaling based on the corpses consumed, which eliminates the need for that Dummy mod as well.

Here's a fresh reload of the build:
image

**Review by LocalIdentity — APPROVED** [review]

**Pull request merged**
