### PR TITLE
Update boss armour/evasion multipliers and add override fields to config

### PR DESCRIPTION
**Pull request by ybbat**
Basic implementation for #5619 

As mentioned in issue it can be very useful to override the default monster evasion value due to many monsters/bosses having far more than the assumed amount, leading to misleading dps numbers.

### Link to a build that showcases this PR:

https://pobb.in/WkrKXvXutsGZ GrimroFlameHaze

### Before screenshot:

image

### After screenshot:
Using value of [lvl 84 Atziri](https://poedb.tw/us/Atziri%2C_Queen_of_the_Vaal#AtziriQueenoftheVaalAtziri) for example
image
image
As expected, 91.93% rounded up to 92%
image

### CODE REVIEW

**Comment by QuickStick123** [comment]
If the average evasion on bosses is higher across the board then consider setting up placeholders like for the other stats so these numbers are more realistic. You could also consider doing the same for armour if that is also significantly higher on bosses.

**Comment by ybbat** [comment]
> If the average evasion on bosses is higher across the board then consider setting up placeholders like for the other stats so these numbers are more realistic. You could also consider doing the same for armour if that is also significantly higher on bosses.

I have added a quick placeholder for pinn+uber bosses, based on the average evasion of the 7 main pinnacle bosses.

Unfortunately it doesn't seem trivial to just "get all the pinnacle bosses" from the ggpk, is there a list that the previous placeholders are using, i.e. should elderslayers/guardians/elder guardians/atziri/uberatziri included in the pinnacle boss presets?

I hadn't looked into armour previously but it does seem similar in that the multiplier varies significantly between bosses, however there already seems to be a 33% more on armour in the pinnacle preset, and 100% more on armour for uber bosses. Is there more detail on what this more multiplier is based on?

I also may look into adding a field for the user to select to use the high end evasion/armour rating for monsters rather than average if that sounds reasonable.

**Comment by ybbat** [comment]
I have updated the PR so that the evasion/armour multipliers are exported from the ggpk, currently I have populated ubers.txt and pinnacles.txt with a conservative list of bosses included in each category.
An armour multiplier field has also been added to the config.

**Comment by QuickStick123** [comment]
Overall looks excellent. It might be a nice idea to present these number as the raw flat numbers as that would be more useful to a user at a glance. This would require you to move around some calculations namely removing 495-497 in CalcSetup.lua and moving these numbers to the config tab as pre calculated values (probably just give base stat of levelTable * mult). Enemies also have accuracy so might be nice to check that as well and add if it different enough alongside evasion/armour.
image

**Comment by Regisle** [comment]
what quick said is probs true, 

but also to be nitpicky, you should be using camelCase as it makes it hard to read with everything lower case, 

the ubers should probs be included in the same file with just a marker that its uber (particularly if they have the same evasion/armour) eg an example of exporting 
`#boss SynthesisVenarius Venarius {Uber}`
 and then your directive table.boss should be something like
` directiveTable.boss = function(state, args, out)
    state.id, state.name = args:match("(%w+) (%w+)")
    local isUber = args:match("{Uber}")
`

This might be a good idea to combine with #5612 in some way, I could easily export the armour/evasion values there, Ill talk in the discord about it and see what people want

**Comment by Nightblade** [comment]
I'll add `ubers` to the spell-checker

**Comment by ybbat** [comment]
Thank you for the feedback!

image
Config now uses the flat evasion/armour value.

I looked at accuracy and it is almost always 100%, there are a couple of enemy types that have a different value but they are extremely rare and not on relevant monsters anyway, though if this should change in future it will be simple enough to add.

Pinnacles.txt and Ubers.txt has also been consolidated into Bosses.txt with an {Uber} arg as suggested by [Regisle](https://github.com/Regisle). This could also be updated to include other bosses such a breach/mapbosses/etc but this would involve manually finding all the relevant bosses and adding to this file.

**Review by LocalIdentity — APPROVED** [review]

**Pull request merged**
