### PR TITLE
Implement Superchage Notable

### PR DESCRIPTION
**Pull request by rskupnik**
A placholder for #425

### CODE REVIEW

**Comment by rskupnik** [comment]
Seems to work fine, I'll do some more testing tomorrow

supercharge-0
supercharge-1
supercharge-2
supercharge-3

**Comment by rskupnik** [comment]
I think I know how to fix this, will try to find some time for this tomorrow

**Comment by BlueManiac** [comment]
What about ailment damage? (ex. with stormfire) Or is this mod specifically for damage inflicted on targets?

The current merged implementation for the mod do not seem to take ailment damage into account. Perquil's Toe do say that it's specifically for hits, but the supercharge mod do not.

**Comment by LocalIdentity** [comment]
Added in this PR https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/547

**Pull request closed without merging**
