### PR TITLE
314 uniques

### PR DESCRIPTION
**Pull request by pundm**
PR to gather some 3.14.0 unique updates - no logic added, only text changes.

- Infernal Mantle
- Law of the Wilds
- Null's Inclination
- Signal Fire
- Apep's Slumber
- Mask of the Spirit Drinker
- Sacrificial Heart
- Cowards Chains
- Dance of the Offered
- Story of the Vaal
- Architects Hand
- Rigwald's Quills
- Atziri's Reign
- Vessel of Vinktar

### CODE REVIEW

**Comment by pundm** [comment]
The 'Story of the Vaal' commit should be seen as experimental as I'm not confident in its solution.

**Comment by Nostrademous** [comment]
I would suggest you turn this into two PRs.
1) Unique changes
2) Implementation of new/altered modifiers

This way we can push the new uniques out without having to test modifier implementation as potentially breaking PoB.

**Comment by pundm** [comment]
> 
> 
> I would suggest you turn this into two PRs.
> 
>     1. Unique changes
> 
>     2. Implementation of new/altered modifiers
> 
> 
> This way we can push the new uniques out without having to test modifier implementation as potentially breaking PoB.

Ok, have to find out how to do this retroactively.

**Comment by pundm** [comment]
the PR should now only include unique item changes without any logic/modparser changes.

**Review by LocalIdentity — APPROVED** [review]

**Pull request merged**
