### PR TITLE
Add a tooltip stat-diff toggle to Items tab

### PR DESCRIPTION
**Pull request by Nightblade**
Fixes #n/a.

### Description of the problem being solved:

Adds a keyboard shortcut to toggle tooltip generation off/on in the **Items** tab, in response to a user's request to add a manual-calculation mode and button, or something of that nature.

The shortcut, and tip-text, are taken from the **Tree** tab: <kbd>Ctrl</kbd>+<kbd>d</kbd>

This was the simplest code-change (hack) I could see at the time, and while it does solve the user's issue in a roundabout way, I realise there are good reasons why this PR may end up rejected.

A better way might have been to intercept recalculation requests and only recalc when a hotkey is used, but that seemed rather involved at first glance.

### Steps taken to verify a working solution:
Tested with user's build code on current dev branch of pob.

### Link to a build that showcases this PR:
https://pobb.in/LhJE9HFWkVWX  (purely experimental)

### Before screenshot:
image

### After screenshot:
image

edit: updated "After screenshot" to latest version

### CODE REVIEW

**Comment by Wires77** [comment]
Does this speed up hovering jewels in involved builds by a lot?  To have a chance of approval, this would still need to show the stats on the jewel (just not the comparison) and the Ctrl+D text on the normal tooltip so users know the feature exists.

**Comment by Nightblade** [comment]
> Does this speed up hovering jewels in involved builds by a lot?

Yes, presumably because it prevents the tooltips from calling further (re)calculations.

&nbsp;

> To have a chance of approval, this would still need to show the stats on the jewel (just not the comparison)

Probably doable, but beyond my capabilities currently, so it would be dependant on someone else having a squint at it.

**Comment by Nightblade** [comment]
Actually, I may have spoken too soon regarding my capabilities.  I'll have a go at it.

**Comment by Nightblade** [comment]
Wasn't actually that hard yay!
image

**Comment by Nightblade** [comment]
Added code to save/load the setting, PR read for review.

**Comment by Nightblade** [comment]
Another benefit of this enhancement is visibility when running pob at reduced horizontal resolution with a lot of jewels in your passive tree:

before
image

after
image

**Review by LocalIdentity — APPROVED** [review]

**Pull request merged**
