### PR TITLE
The Iron Mass Fix

### PR DESCRIPTION
**Pull request by Nostrademous**
Fix how the weapon is given to the Skeletons.

### CODE REVIEW

**Review by ALT-F-X — CHANGES_REQUESTED** [review]
This fix gives every minion you have the weapon, making damage numbers for every minion but skeletons wrong.

**Comment by Nostrademous** [comment]
> This fix gives every minion you have the weapon, making damage numbers for every minion but skeletons wrong.

True, will fix when I get home, it's an easy fix. Thanks for the comment.

**Comment by ALT-F-X** [comment]
This seems to still give Skeleton Archers the wrong base damage (they can't use a melee weapon). I'm not really comfortable in Lua, could you confirm?

**Comment by Nostrademous** [comment]
Yeah, the Skeleton Archers are not affected by this. The issue is Phatasmal which is not yet supported changing the default skeletons from Melee to Ranged and the system not knowing it needs to update the tags.

**Pull request merged**
