### PR TITLE
fix: un-krangle cluster jewel orbit calculations

### PR DESCRIPTION
**Pull request by dbjorge**
### Description of the problem being solved:

#3972 introduced an issue where multiple-skill Cluster Jewels rendered incorrectly when using tree version 3.17.

We calculate `node.oidx` values for Cluster Jewels in `PassiveSpecClass:BuildSubgraph` based on index values from `/src/Data/ClusterJewels.lua`. That is, those indices are all relative to the `totalIndicies` of a given jewel type as specified by `/src/Data/ClusterJewels.lua`. However, the calculation of `node.x` and `node.y` in `PassiveTreeClass:ProcessNode` expects those `oidx` values to instead be relative to `tree.constants.skillsPerOrbit`. It used to be safe to assume that those values were identical for a given orbit, but this is no longer a safe assumption as of 3.17; for Medium and Large cluster jewels, `totalIndicies` is 12 but `skillsPerOrbit` is 16.

The result of this is that the nodes for the jewel end up all squished to one side:

image

An earlier solution involved updating the rendering code to continue to use `skillsPerOrbit` of 12 for cluster jewel skills, but that ended up causing this different looking issue where the skills rendered correctly relative to each other, but at an incorrect offset:

image

This happens because the very last step in `PassiveSpecClass:BuildSubgraph`'s `oidx` calculation before the indices get translated into `x, y` values involves offseting `node.oidx` by `proxyNode.oidx`, where `proxyNode`  comes from the TreeData the subgraph is being inserted into.

The fix I implemented for this was:
1. Implement a `translateOidx` helper with translation tables for 12 -> 16 and 16 -> 12 based `oidx` conversions
2. Update the `proxyNode.oidx` offset step to perform the offset in clusterData-based-coordinates by first translating `proxyNode.oidx` to those
3. Add a new step to translate the final `node.oidx` coordinate to TreeData-based-coordinates before having the tree calculate x/y positions

(an earlier iteration instead kept the `proxyNode.oidx` offset step in TreeData-based-coordinates, doing it after the `node.oidx` translation, but this isn't quite accurate - if you do that, you get [this issue](https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/3982#issuecomment-1024997719) that @Guitaraholic reported in a comment below)

We understand that this is similar to the logic GGG is using; we expect this to continue to work even after `/src/Data/ClusterJewels.lua` gets updated for 3.17. Particularly, our understanding is that medium and large cluster `totalIndicies` values will remain 12, rather than updating to 16 like the `skillsPerOrbit` values.

### Steps taken to verify a working solution:

Verified the following matrix of test cases:

|  | 3.16 tree | 3.17 tree |
|-|-|-|
| no cluster jewels | ✔ | ✔ |
| large -> 2x medium -> small jewels in each large slot | ✔ | ✔ |
| medium -> small jewels in each large slot | ✔ | ✔ |
| small jewels in each large slot | ✔ | ✔ |
| Voices (variety of passive counts) -> 3x medium -> small jewels in each large slot  | ✔ | ✔ |
| Keystone clusters in each large slot | ✔ | ✔ |

...plus:

* [x] smoke test with a 3.10 (Delirium) build/tree
* [x] smoke test with adding cluster jewels to an already-open 3.17 build (as opposed to converting a 3.16 tree or loading a saved 3.17 build)

### Link to a build that showcases this PR:

* [Build with trees for each of the 3.16/3.17 cases in the test matrix above](https://pastebin.com/WMVe7EVu)
* [3.10 smoke test with assorted cluster scenarios](https://pastebin.com/qh2SxPcs)

### After screenshot:

(3.16) Closeup of one case
image

(3.17) Closeup of same case after 3.17 conversion
image

(3.16) Full view of a tree with many jewels
image

(3.17) Full view of a same tree after 3.17 conversion
image

### CODE REVIEW

**Comment by Guitaraholic** [comment]
Works for 10 passives and the pathing looks better but getting strange bunching on 12 passives 
image

**Comment by dbjorge** [comment]
Thanks for the report, had regressed it again with the d1d84fc update to bring it closer to GGG's implementation. Can you test again now?

image

**Comment by Guitaraholic** [comment]
image

Yep that sorted it - awesome 👍

**Comment by dbjorge** [comment]
Thanks for confirming. Updated the PR description accordingly.

**Review by Wires77 — APPROVED** [review]
LGTM

**Pull request merged**
