### PR TITLE
Feature CWDT Trigger

### PR DESCRIPTION
**Pull request by ProphetLamb**
Triggers skills using CWDT.

### Description of the problem being solved:

In PoB currently, CWDT skills are cast whereas in PoE they are instant & triggered. This PR applies the trigger mechanism to CWDT.
Values are verified using the [wardloop calc](https://docs.google.com/spreadsheets/d/1nwCNWFHBigjIA3PlIiwPk296QIjxDkJ1nZN5OD5PvcE) , and a pen and paper :3

Please note this is only tested for the current ward loop, there might be wired edgecases, where the logic fails.

### Steps taken to verify a working solution:
- Import a CWDT build.
- Calculate main-link CWDT dps manually -> 65mil
- Compare with PoB value -> OK

- Import a CWDT build.
- Calculate aux-link (two skill) dps manually -> 2.3mil, 5.4mil
- Compare with PoB value -> OK

### Link to a build that showcases this PR:
https://poe.ninja/challenge/builds/char/a258314816/SnakieCarryU

### Before screenshot:
main-link
aux-link

### After screenshot:
main-link
aux-link

### CODE REVIEW

**Comment by QuickStick123** [comment]
Pretty sure this is already done in https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/4599

**Comment by ProphetLamb** [comment]
> Pretty sure this is already done in #4599 maybe double check

Thanks for pointing out the PR. It indeed does implement CWDT triggering. Yet it produces interesting values.
image
The trigger rate is capped by the cast rate, which is not the case in game.

**Comment by QuickStick123** [comment]
@Paliak

**Comment by Paliak** [comment]
CWDT doesn't work right now as i'm fixing the order in which mods to effective source trigger rate are applied. If you'd like to test you can git checkout the commit from before i've marked it as draft. CWDT and other triggers will be supported but this can be merged if this feature can't wait until #4599 is merged.

**Comment by Paliak** [comment]
Pushed some local commits. The mentioned issue should be fixed. I have plans for proper support for cwdt loops but the whole pr will have to wait until christmas is over and i have some more time to work on it as i've been really busy the past few weeks.

**Comment by ProphetLamb** [comment]
I have been experimenting around with how best to count CWDT. Currently both PRs are assuming, that the trigger operates at maximum rate. 
Though this rate can be calculated by introducing a new meta-stat `degen_hit_flat` the life loss due to hit damage per second on specific items.

# Hit degen flat rate

The rate must be calculated in the base damage calculation, and is item/gem specific.

## Eye of Innocence
For CWDT loops using the EoI assume a CWDT maximum trigger rate and calculate the number of hits on enemies times the ignite chance times 100 to obtain the `degen_hit_flat` increment per skill

(I) $$degenhitflat :=100*\sum_{s=gems} [tag_{spell}(s) \land supported_{cwdt}(s) \to cdr(s) * hits(s) * ignite(s) ] [else \to 0]$$

where 
- $100$ is the on ignite dmg of the Eye of Innocence,
- $tag_{spell}(s)$ is whether the skill has the tag `skill`,
- $supported_{cwdt}(s)$ is whether the cwdt support is linked to an active skill,
- $cdr(s)$ is the modified base cool down recovery time divided by the number of active skill gems in the link,
- $hits(s)$ is the hit multiplier (set by the user in the skills tab), and
- $ignite(s)$ is the ignite chance for an active skill.

Practically in the base calculation a active skill checks if the EoI is equipped, then performs the calculation.

## Heartbound Loop
The Hearbound loop calculation is based on minion deaths, only minion skills supported by CWDT need to be considered.
The calculation is similar to EoI, but a bit simpler

(II) $$degenhitflat :=450*\sum_{s=gems} [tag_{minion,spell}(s) \land supported_{cwdt}(s) \to max_{minion}(s) / duration_{minion}(s) ] [else \to 0]$$

where 
- $max_{minion}(s)$ is the maximum number of minions summoned,
- $duration_{minion}(s)$ is the duration of the minions.

This computes the maximum `degen_hit_flat` rate, each minion spell supported by CWDT now needs to be checked against the actual minion uptime to compute the real number of minions expired per second.

(III) $$degenhitflat':=450*\sum_{s=gems} [tag_{minion,spell}(s) \land supported_{cwdt}(s) \to r(s) * once_{minion}(s) * cdr(s)] [else \to 0]$$

with
- $r(s) := clip(degenhitflat / (damage_{cwdt}(s) * cdr(s), 0, 1)$,

where
- $damage_{cwdt}(s)$ is the damage threshold for the CWDT support gem, and
- $once_{minion}(s)$ is the number of minions summoned per cast.

Finally let $degenhitflat = degenhitflat'$, so that `degenhitflat` is the stablized amound of hit damage per second. 

# CWDT trigger-rate

I am unsure if the trigger rate can be calculated in the main calculation pass, or if we need a step inbetween.

In anycase, from (III) the fromula for the calculation of the trigger rate for an arbitrary skill supported by CWDT can be inferred, as a percentage of the maximum trigger rate.

(IV) $$triggerrate(s) := r(s) * cdr(s)$$

with
- $r(s) := clip(degenhitflat / (damage_{cwdt}(s) * cdr(s), 0, 1)$,

where
- $cdr(s)$ is the modified base cool down recovery time divided by the number of active skill gems in the link.

This computes the final CWDT trigger rate for any given skill.

# Minion skills

I think minion skills supported by CWDT deserve to be explicitly mentioned. In (III) we use CWDT to compute the average number of active minion as a meta-step. Minion skills should use this number for damage calculations, instead of the maximum number of minions.

# Postscriptum

@Paliak I hope my research helps to get the correct CWDT calculations down. I did my math on the paper, and in case I didnt miscalculate, the trigger rate for the mainlink in my demo pob should be $3.86$ casts/s.

**Comment by ProphetLamb** [comment]
While the heuristic, assuming maximum trigger efficiency, helps PoB to suggest proper upgrades, it's a stop gap measure.
I think it will take quite some effort to implement this correctly in #4599 .

I agree with @Paliak that it is sensible to merge this as is for the Christmas release 🎄 and later drop this implementation in favour of #4599 .

**Comment by Paliak** [comment]
Pob already calculates the self damage for Boneshatter and Forbidden Rite. The hard part of implementing cwdt in #4599 is getting total self damage / s values. The rest is mostly trivial.

**Comment by ProphetLamb** [comment]
> Pob already calculates the self damage for Boneshatter and Forbidden Rite. The hard part of implementing cwdt in #4599 is getting total self damage / s values. The rest is mostly trivial.

The write-up proposes a heuristic with asymptotical error with increasing passes to compute the total damage taken per second. The main twist is, instead of starting at 0 we start max possible dps and then calculate what we sustain. This approach has much nicer properties then the former, bc the dps doesnt oscillate, and is stable after the 2nd pass.
We then use the total damage taken per second to compute the individual activation-frequencies for the CWDT gems.

The current self damage calcs for FR and BS do not support triggering .

**Comment by ProphetLamb** [comment]
Well technically you can induce it, bc the method is I=0 and I+=1. For the write-up I stuck the the current two pass calculation of PoB

**Comment by Paliak** [comment]
Defense calcs in pob are already based on passes so i'll likely just tie into that. I don't think using the selfDmg/s to calculate trigger rate of individual skills will give the correct values due to cwdt rotation and rotation of skills within each cwdt setup. The current implementation of FR and BS self damage will not work but it shouldn't require too many changes.

**Comment by ProphetLamb** [comment]
> Defense calcs in pob are already based on passes so i'll likely just tie into that. I don't think using the selfDmg/s to calculate trigger rate of individual skills will give the correct values due to cwdt rotation and rotation of skills within each cwdt setup. The current implementation of FR and BS self damage will not work but it shouldn't require too many changes. 

- Yes the method is intended to tie into the passes PoB uses.
- The order of operation is of no matter for avg damage, so using the function $cdd(s)$ produces correct results.
- Yes
I suggest you give the write up a read, it's designed to require minimal adjustments to the code on #4599, I am a bit more verbose with then required bc ppl generally don't like large equations ;)

**Comment by Paliak** [comment]
>I suggest you give the write up a read

I have a few times now and honestly i only have a rough idea of the approach. 

I don't see how your method accounts for the fact that cwdt can miss a trigger opportunity if a triggered skill is on cooldown. I agree that it does work for skills that have no cooldown but i don't see how cdd(s) can handle setups with multiple skills that have different cooldowns. To my understanding cdd(s) assumes that any given triggered skill takes up an equal percentage of total cwdt trigger rate which is not the case for setups such as CWDT-Steelskin-FrostBomb-Arc.

Good chance your approach could be modified to use values returned by calcMultiSpellRotationImpact; Though i'll need time to really understand how it works to do so.

**Comment by ProphetLamb** [comment]
@Paliak Thanks for pointing out that cooldowns are not considered. I did not consider gem setup with cooldown.

I hope the method is still of use and can be adapted to work. I think we already have code that handles tearing (cd miss) in `getTriggerActionTriggerRate`.

**Comment by Paliak** [comment]
A formula would be great if you can come up with one. Repeated addition of floats causes all kinds of small errors.

**Comment by Paliak** [comment]
>Generating a Markov chain then permutating works

I'll need to read-up on the math involved but one i get around to implementing cwdt loop support i'll give replacing the simulation that that a try.

**Comment by ProphetLamb** [comment]
math
I tried this algorithm for a few different skill combinations, and the results are proportional to the PoB values, but somehow I always end up with slightly lower Triggerrate then expected... To the best of my knowledge this should be correct. Any idea what I am missing?

**Comment by Paliak** [comment]
ServerTickRate is defined as `ServerTickRate = 1 / 0.033` you seem to have defined it as `1/33`. The values coming from the simulator are slightly inflated due to repeated addition of small floats but the error should be no more than `0.0005`. `K_AB[tot]` looks about correct to me but `K_A[tot]` seems too low.

**Comment by ProphetLamb** [comment]
OK, so it seems I had a small mistake in the calculation of the chance for the cast to be blocked. Visualizing the jigsaw helped calculate the bias for the correct avg. The calculation is accurate for all skills tested, unless a rotation is skipped aka. wasted.

I am currently looking into how to compute the chance to skip a rotation.

Frost Bomb
Arc

```python
import math as m
import numpy as np
import matplotlib.pyplot as plt

# utility
class Dyn:
  def __init__(self, **kwargs):
    self.__dict__.update(kwargs)
  def __repr__(self):
    return str(self.__dict__)

def foreach(list, action):
  for i in list:
    action(i)

def ceil(x, base):
  return base * m.ceil(x/base)


# params

# server tickrate [1/s]
st = 33

# attack rate [1/s]
aps = 5

# cooldown time [s]
cdt = .15

skills = [Dyn(uuid = 'Frost Bomb', cd = 2.5), Dyn(uuid = 'Arc', cd = 0)]

foreach(skills, lambda s: setattr(s, 'trigger_next', 0))
foreach(skills, lambda s: setattr(s, 'trigger_count', 0))
foreach(skills, lambda s: setattr(s, 'triggers', []))

def simulate():
  """ Simulation from calcMultiSpellRotationImpact in CalcPerform """
  time_max = 100
  time_delta = 1 / 10000
  time = 0
  tick = 0
  tick_cur = 0
  trigger_next = 0
  trigger_inc = 1 / aps
  idx = 0
  wasted = 0
  
  while time < time_max:
    if time >= trigger_next:
      idx_cur = idx
      while skills[idx].trigger_next > time:
        idx = (idx + 1) % len(skills)
        if idx == idx_cur:
          wasted += 1
          trigger_next = time + trigger_inc
          break
      
      if skills[idx].trigger_next <= time:
        dt = time - skills[idx].trigger_next
        skills[idx].triggers.append(dt)
        
        skills[idx].trigger_count += 1
        skills[idx].trigger_next = time + skills[idx].cd
        tick_temp = tick
        while skills[idx].trigger_next > tick_temp:
            tick_temp += (1/st)
        skills[idx].trigger_next = tick_temp
        idx = (idx + 1) % len(skills)
        trigger_next = time + trigger_inc
    
    time += time_delta
    
    if tick < time:
      tick_cur = tick
      tick += (1/st)
  
  rates = [time / skill.trigger_count for skill in skills]
  return wasted, rates

rot_cd_time = sum([ceil(max(s.cd, 1/aps), 1/st) for s in skills])

def calculate(s):
  cd = ceil(max(s.cd, 1/aps), 1/st)
  inaccuracy = cd / rot_cd_time
  trigger_min = cd
  trigger_max = cd+1/aps
  
  trigger_avg = trigger_min * (1-inaccuracy) + trigger_max * (inaccuracy)
  return trigger_avg

waste, sim_rates = simulate()
calc_rates = [calculate(s) for s in skills]

print(dict(calc=[[calc, 1/calc] for calc in calc_rates], sim=[[sim, 1/sim] for sim in sim_rates], acc=[int(sim/calc*10000)/100 for sim, calc in zip(sim_rates, calc_rates)]))

lables = [s.uuid for s in skills]
values = [s.triggers for s in skills]

fig, ax = plt.subplots()

for i in range(len(values)):
  ax.plot(values[i], label=lables[i])

plt.show()
```

**Comment by Paliak** [comment]
Have you tested with two skills that have no cooldown ? `{'calc': [3.333333333333333, 3.333333333333333], 'sim': [2.499999999945097, 2.499999999945097], 'acc': [133.33, 133.33]}` 

The wasted trigger count is only used to check whether any wasted trigger opportunities exist so not sure if a percentage is necessary.


Poe server tickrate is 30 ticks /s .

**Comment by Paliak** [comment]
It may be easier to continue the discussion on discord. Dm LocalIdentity#9871 for an invite link.

**Comment by ProphetLamb** [comment]
Well this is the best accuracy I can calculate, the rest would simply be a more optimized simulation
image

**Comment by ProphetLamb** [comment]
Here is the overview of a few different skills (with lower sampling rate)
image
image
image
image
image

**Comment by Paliak** [comment]
I wonder if hybrid approach would be worth considering.

If none of the linked spells have cooldown then the trigger rate for any of them would simply be `aps / spellcount`
If all linked spells have cooldown apply the formula to each one.
If only some skills have cooldown apply formula to those then subtract their rates from aps and divide the result by the amount of spells that have no cooldown to get their rates.

The simulation could be applied in the uncertain interval instead of the formula for more accurate results.

The simulation could likely also be sped up a good bit even if just by coming up with a way to calculate the biggest usable time delta for a given combination of trigger and skills instead of using a hard coded one.

Thanks for the work you've done. No way i'd be able to come up with this myself.

**Comment by ProphetLamb** [comment]
I spend a few minutes creating an optimized simulation.
Here is the result with 1 iteration
image
3 iterations
image
9 iterations
image
Well, that's not really useful (besides academic fun), because noone is going to even notice the tiny errors.
The steps are at the rate of server ticks, so for pob the approximation with 1 iteration would suffice, because even a 1% increase in trigger rate would already skip over a few "steps".

Nonetheless, with three iterations, the results are good all around:
I present the simulation with 3 iterations with the previously used skills

image
image

Something is still wrong with the penalization of the active skill, when using a different skill cooldown... I would appreciate help in figuring out what exactly it is.
image
image
image

Here is the link to my workingset
https://github.com/ProphetLamb/PathOfBuilding/blob/feature_stochastic_trigger_rotas/tests/skill_rota.ipynb

**Comment by ProphetLamb** [comment]
Ah solved it.
Interestingly enough, the transition between the heuristics is more smooth than I thought.
image
image
the small jump in the "calculated" between the smooth line and the jagged line, occurs where the heuristic calculation is swapped for the simulated heuristic.

I improved the calculation, and now we don't have to iterate/simulate anything at all, instead we have a $O(n^2)$ algorithm to calculate the result. Funnily enough, it's modified code from my simulation. Turned out, executing one iteration of the "simulation" starting with each skill yields accurate results. Therefore, my simulation is in fact a calculation, lols.

**Comment by ProphetLamb** [comment]
I ran a few benchmarks, and it would appear, that the new method is a bit faster than the simulation. 

21:02:13: begin Ice Spear
21:02:18: finish Ice Spear

|    Metric   |      Simulate      |     Calculate      |
|-------------|--------------------|--------------------|
|  Mean [ms]  | 102.38326848249027 | 0.1823929961089494 |
| Median [ms] |       93.75        |        0.0         |
|  25th [ms]  |       93.75        |        0.0         |
|  75th [ms]  |      109.375       |        0.0         |
|   Min [ms]  |       78.125       |        0.0         |
|   Max [ms]  |       156.25       |       15.625       |
|   Std [ms]  | 17.42274825699866  | 1.6782798810605861 |
|-------------|--------------------|--------------------|
21:02:18: begin Ice Spear Arc
21:02:24: finish Ice Spear Arc

|    Metric   |      Simulate      |      Calculate       |
|-------------|--------------------|----------------------|
|  Mean [ms]  | 102.38326848249027 | 0.060797665369649805 |
| Median [ms] |       93.75        |         0.0          |
|  25th [ms]  |       93.75        |         0.0          |
|  75th [ms]  |      109.375       |         0.0          |
|   Min [ms]  |       78.125       |         0.0          |
|   Max [ms]  |       156.25       |        15.625        |
|   Std [ms]  | 18.58360976151792  |  0.9727626459143969  |
|-------------|--------------------|----------------------|
21:02:24: begin Frost Bomb Arc
21:02:29: finish Frost Bomb Arc

|    Metric   |      Simulate      |     Calculate      |
|-------------|--------------------|--------------------|
|  Mean [ms]  | 101.83608949416342 | 0.607976653696498  |
| Median [ms] |       93.75        |        0.0         |
|  25th [ms]  |       93.75        |        0.0         |
|  75th [ms]  |      109.375       |        0.0         |
|   Min [ms]  |       78.125       |        0.0         |
|   Max [ms]  |       156.25       |       15.625       |
|   Std [ms]  | 17.97637997332328  | 3.0215889201821935 |
|-------------|--------------------|--------------------|
21:02:29: begin Ice Spear Frost Bomb
21:02:34: finish Ice Spear Frost Bomb

|    Metric   |      Simulate      |     Calculate      |
|-------------|--------------------|--------------------|
|  Mean [ms]  | 100.98492217898833 | 0.1823929961089494 |
| Median [ms] |       93.75        |        0.0         |
|  25th [ms]  |       93.75        |        0.0         |
|  75th [ms]  |      109.375       |        0.0         |
|   Min [ms]  |       78.125       |        0.0         |
|   Max [ms]  |       156.25       |       15.625       |
|   Std [ms]  | 17.969181729207655 | 1.6782798810605861 |
|-------------|--------------------|--------------------|
21:02:34: begin Frost Bomb Arc Ice Spear
21:02:40: finish Frost Bomb Arc Ice Spear

|    Metric   |      Simulate      |     Calculate      |
|-------------|--------------------|--------------------|
|  Mean [ms]  | 102.07928015564202 | 0.6687743190661478 |
| Median [ms] |       93.75        |        0.0         |
|  25th [ms]  |       93.75        |        0.0         |
|  75th [ms]  |      109.375       |        0.0         |
|   Min [ms]  |       78.125       |        0.0         |
|   Max [ms]  |      171.875       |       15.625       |
|   Std [ms]  | 18.233421556069974 | 3.1626475689785876 |
|-------------|--------------------|--------------------|

**Comment by Paliak** [comment]
Looks awesome. I'll translate it to lua and post the commit hash here when i'm done.

**Comment by Paliak** [comment]
```Python
if aps >= tt0_br:
      return aps / len(skills)
```

Does the main calculation account for trigger cooldown and attack speed alignment ? Currently Pob doesn't do it but i've added it to #4599 by calling `calcMultiSpellRotationImpact` twice. First call takes in effective attack speed ( accuracy, crit, trigger chance etc ) and the trigger cooldown to check how many attacks will actually cause the trigger to trigger and then the trigger rate of the trigger is fed back into the simulator with all the linked skills to get their trigger rates. 

https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/f397759e598502f984aa5d529ad3d2fab2d14942/src/Modules/CalcPerform.lua#L380-L410

Numbers for Coc-Cyclone-Arc produced by the above snippet Build: https://pobb.in/0rJatrtMY8O_

obraz

I've tried to reproduce the numbers the original simulation returns in the above case and got:

obraz

I set data.cdt to 0 for the above. The original simulation seems to return expected values but the new formula seems to just do 
```PYTHON
if aps >= tt3_br:
      return 1/ceil(s.cd,stf)
``` 
I've also tried forcing `def calculate(data: Dyn) -> t.List[float]` to use `quick_sim(data)` for cases where cdt is 0 but i seem to get the exact same results. Any ideas on how the calculate function could be modifed to handle such cases ?

**Comment by Paliak** [comment]
Looking closer at a Coc-Cyclone-Arc graph i think the above might just be me mistaking an error in calculation for a bug as the calculated value is within 5% of the simulated one. 

obraz

**Comment by ProphetLamb** [comment]
@Paliak If you increase the `limit_simulation` to $32$ the steps disappear. 
Setting `data.cdt=0` will probably break all calculations. The code expects it to be the cooldowntime of the CoC/CWDT trigger

**Comment by Paliak** [comment]
`data.cdt = 0` seems to work fine as long as the triggered skill has cooldown since `s.cd = max(s.cd, data.cdt)` 

obraz

`s.cd = max(s.cd, data.cdt)` was the part i was missing.

Might just not bother with the effective trigger rate of trigger value since it's not really something a user would be particularly interested in anyway.

Thanks again.

**Comment by ProphetLamb** [comment]
> `data.cdt = 0` seems to work fine as long as the triggered skill has cooldown since `s.cd = max(s.cd, data.cdt)` 
> 
> obraz
> 
> `s.cd = max(s.cd, data.cdt)` was the part i was missing.
> 
> Might just not bother with the effective trigger rate of trigger value since it's not really something a user would be particularly interested in anyway.
> 
> Thanks again.

Awesome, I suggest you experiment with the number of iterations for the sim. 32 is probably far to large... Tho idk. Well have to see what gives good results:D

**Comment by Paliak** [comment]
The breakdown needs some tweaks to handle the rates being passed around in a new format, some things could be inlined to make things faster (lua doesn't really like oop too much so things like iterators can be a bit slow), and the simulation count could be adjusted furter like you've mentioned but overall seems to work great. Roughly around a 200ms per skill speedup for #4599 (simulation for whole socket group is ran for every triggered skill in that group) .


Calculated:
obraz

Simulated:
obraz

(the error is likely caused by rounding because s_format automatically rounds to the specified format)

**Comment by ProphetLamb** [comment]
@Paliak Iterators decouple very long nested loops nicely, I like them. Python iterators are also not the fastest... I generally don't advice to do per case optimization of business logic (which this kinda is) for the specific Lang, at the cost of readability/ maintainability. 

Especially because a language update can change the speed of things under the hood and all your work is nil. This occurs painfully often, especially with Java and C#.

If we really want performance I can rewrite it in C/Rust+Cdecl then dynamic link it to lua. Should get us down to effectively 0time

**Comment by Paliak** [comment]
I think maintainers want to keep things in lua for the most part. Take a peek at the commit.

**Comment by Paliak** [comment]
This should be good to close now.

**Pull request closed without merging**
