### PR TITLE
New Structure Fix-Ups

### PR DESCRIPTION
**Pull request by Nostrademous**
- Update some `.gitignore` stuff
- Made APP_NAME global to set window title

### CODE REVIEW

**Review by ppoelzl — CHANGES_REQUESTED** [review]
I don't think there's anything wrong with still calling the application "Path of Building". It's not like we're trying to misrepresent its origin or identity by any means.

**Comment by Nostrademous** [comment]
> I don't think there's anything wrong with still calling the application "Path of Building". It's not like we're trying to misrepresent its origin or identity by any means.

I agree, however, some amount of submitted screenshots that are bug reports are from people using the original PoB and not the fork. This provides another indicator.

**Comment by ppoelzl** [comment]
That's the purpose of the (kind of) watermark in the bottom left. Changing the window title isn't a defense against overly cropped screenshots either.

**Comment by Nostrademous** [comment]
> That's the purpose of the (kind of) watermark in the bottom left. Changing the window title isn't a defense against overly cropped screenshots either.

Okay. Changed it to what it was.

**Review by Wires77 — APPROVED** [review]
LGTM

**Pull request merged**
