### PR TITLE
Change watcher's eye dodge mods to suppress mods

### PR DESCRIPTION
**Pull request by deathbeam**
- Haste one is legacy but in standard its suppress spell damageA
- Grace is now suppress spell damage not dodge attacks

Signed-off-by: Tomas Slusny <slusnucky@gmail.com>

### Before screenshot:

image

### After screenshot:

image

### CODE REVIEW

**Comment by Wires77** [comment]
This is actually generated automatically now.  https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/dev/src/Data/Uniques/Special/Generated.lua#L565

I'm not actually sure how you got the dodge mods to appear since the generated version of the jewel should take precedence...were you on a really old version by chance?

Regardless, the proper fix would be to simply remove Watcher's Eye from jewel.lua.

**Comment by deathbeam** [comment]
Oh i see. And well im on latst dev branch so not sure, they are just there.

**Comment by deathbeam** [comment]
Alright removed watchers eye from the file instead and it looks like that works too

**Comment by Wires77** [comment]
What OS are you on?  I assume it behaves correctly with other generated uniques and if you remove watchers eye from jewel.lua?

**Comment by deathbeam** [comment]
linux, with pobfrontend. And yea after i removed watchers eye from jewel.lua it behaves correctly, i am not sure about other generated uniques. I checked on windows without pobfrontend and there its behaving fine. I guess its just some scuffed load order on pobfrontend then. Still removing it from the file probs do not hurts anyone and at least fixes it on linux i guess?

**Comment by Wires77** [comment]
Yeah, this looks good to me, I may check on the underlying issue at some point, but in reality this shouldn't really happen anyway

**Review by Wires77 — APPROVED** [review]

**Pull request merged**
