### PR TITLE
Add support for additional life recovery flask mods

### LINKED ISSUE #3866: Implement Life Flask Mod 'of Perenniality'
### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Is your feature request related to a problem?

I can't see how much life recovery I'll receive due to Perenniality's effect:
Recover an additional 39% of Flask's Life Recovery Amount over 10 seconds if used while not on Full Life

Currently, the effective flask stats show initial recovery only (based on duration shown and the fact that nothing changes if I toggle 'always on full life' in configuration). The mod is also shown in red.

### Describe the solution you'd like

Implementing the mod.

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Peechey**
Fixes #3866 

### Description of the problem being solved:
Adds support for additional life recovery if used while not on full life flask mods

### Steps taken to verify a working solution:
- Confirm full life config unchecked
- Add one of each mod tier to a flask
- Verify effective flask stats appear and calculate correctly
- Check several combinations of prefixes for instant recovery and recovery/duration modifiers
- Confirm additional recovery not included while full life config checked

### Link to a build that showcases this PR:
<pre>eNq9Wt9z4jgSfh7-ChVVc28TAgY2myO7RQjJUBVmOJyZuXtKKbYAbWSJteUkzNX979uSDZgEQ1t7lTxkjPn6h_prqbuV6f3-EgnyxOKEK3lRb56c1gmTgQq5nF_Uv91dfzqr__5brTehevF1dplyYb75rfahZ5-JYE9MXNS7nTrRNJ4z_X2tyrsHVUsq9YIpOaZ_qPhGhRf1L0qyOnmgMuR6_SkQNEm-0Ihd1P0AhOuEJgGT4WD7PgNGlEtfBY9M38QqXYK_dfLE2fNYhYAZjSdfp3cFo1wWjYLTH3oTQVcs9jXVJIFfF_U-rJ3O2RWN4DdooyIFVacnzXa9sV_CXzIWbpDNk1YZcBKz4WzGAs2f2CDmerCgMijYKJOrih2nQvOl4CwueNUpk_j8RrlXir1TmoqriV-MS_fsMFrp417_4HpxKSCMaN1GYjSXXLNKIhPFEyUrr2BHoDT0KnrgssIaxlTSgUoQ8bnlM4ZDDn0cbgrZjUMaLycshv2n8c5WEsgt-CxQsMer2KgiUliHmzEHyaHvIuBgyNfbvd4qJ539WQSW4q7YC05bEViKG0mN01YEHvDtSWlbEzC0bVBnrbMD53dwbsAjGeC0fpMxS1j8VDj2D-jflcj53Z7MpwdNTdmcIdd6y1iwuIGKOKWa4fbDBtX22gfDY8Co8BjgnvAc0L8rUSE8RnA3PL-cdA-BKwboB41DxI6VLJ6v_AVnAoG2wSyKoIJaFEAmRFGk4rqHTzQpbrBm9_BqMjguOxgUeRAIGbafmcTqD9MxiWpi_ThSaYzkIwOjFjBZrBIeQE9g28MpC9MAdxhtGr-xemIRZLjtGqFP3Ya5TPRSQIeLXTioFaKSRF9rGjxeqXDOKhmpLuGnyyXsc5MtWLlrHkOUE16ogZ-6CPRX6OIHdIlp2syWwhrYotEGbvl8oSXMSHgrr0Twa1lQlVRYzBaONnGdCoFqhifqGVQuzAiYVEOP6ban8Er9iJn8uULr34GjDAxlmMYmR9E2Xku8NdNr2BnZPI2ipYq1fTmgIkisypFcpppIO98mj1yIe5lGD2aKy_7dnhFFZMST4P4hnc3M0FsHZ2I7qg-vr4eDu9H3YS7iM3tSkUAJQZcJgyl4RkUCEhwefWPOh9M50Cg8DI35hIxBQyUNYg5BxIDNwIhy2Y7dGKSZiVFAYIUKhg_Y3WrJTAYk2Jjlxx4GbcdhFDKbaXELtBMzjgYW0BUKuWkvUOihYH0uTAXERW0M6Z0VTxweylnMH1KNzDY7JKD8MO0yaoHFhhC5O3DAvKlBOZH3cBhsXjFwSQmNBZq2KzZjkO7IbW-Pkzv6yGR-WK4Pxp7dawlJ4MS8YVFyuYIKdG3C--rOJaIaEpFFt-YO8k6Zc5gGmsW32Z1kbmxHzUVdxym8DNmMpsK8_1dKBdcrc9AX3uYqYHwlyUI9m04mU2OOgASoub3NvukLnWswNtZG7YLuYsYItU2gaTvNaZ7FBT4ULzhHoTUe0QR8X-W5f1GHKgAHPDx0zs48r040qCtcrkKXnt2bZuJG84feMITtHn4xco3szbfprX34sNB6mZw3Gs_PzydLqhdqxl6gyz4JVNRYghrw8pMtQp-MoUYffi7nfftjFTXWmnrZBWxmoNcwq7H0meWahy8K9qL5zrxcf7DB-M7ZM0kYFIeFr2Ozwp9KRf-xqzex_MyoHtPlhjnzbU6El_MAh-8VhwjFNtHWbBrgv9elujfSwEQeePPsM20vitOEZVcsPxhdKmlfZ5ayGgtQm5leFswphTKyOifj_s1oUBsoaebUGCaqkAyBKEkFMYcJuQYSHomakYnxSnKbDLVBTGcAPSfGw9okZjP-ck7-Cw3DnJ03_2eFYAKJGYWNMQW3oCNb9WG_S92u-VDdd-C3CmYQY83K9UOgGdIge7UW7tzX8kw8J6c1G7cp-_OcdDs1qHOCB1wn5ptu-yPha8skM0lyJSysed5HEps5B75cqyZm2bX8E6GS0I0HpH360SzeOvYPiGvyzySLy0Y4N2Flm6eQAIaDhPCZYSQkzwtIQ8h1QEhi-k0rbnPLULLLTXMfN5fpw4OAJqiEl5FJlcQUYhQrExprIHEkoc2TuhBdJ1baOFK8X7dRf0NJ0-sUKdtlpZPFf_OSLs1fAkKS-y9WJbx57ffkrbWPtyv-8-eqnLf-QypDNG3DF9ic63vzxFTvlhtjzS1jrUOUtXf2UTF0QNmURfCUQNxslHe_JbNYRcS4CEFk0oazhKVm9z1Zau9j6Tv4QnU5TZfG_sqRI8ezzkNy1Om8A0ets_fkqFNSnUImk_LSJJh0LUp27nLkqXV_j2RqtyphCk-r9Q5h94Vaz91ZMKERgRYrGtnd0tiP6WwxXhmmucW0yjDtLaZZhmltMeu_4uY9z4F-p1hKiyozIGn6z3QJx-8KqqYgWbtXXFR-JbJX9LVYCyd2GHWplE4cHdq3liNOXTKhK4qUJcc-l1r7XPLcwosLQuv_JNZ2c7LrZg0pti-aLvl0hIHPTERMVzW0J5O6LnaOpN-NMJXMRbHnvouaLvbabrnQdMu89nF6MIGtqnZfejkuHHXuvC04x_1xOAO9Y8sOoebaO6uK9O2PslN-dVyEUFsSQ8Tbqo5YZ8c5rC2HPOy67STPLX296lnWdj_2HXK66Rx8D5MQb1s4VA931O2_0fwgmXRnoeuQle40_I10wR7JRha5a_BQh8hNzRDecjlKW87hdTwu8Hy6LMdDxKnpTkPbOVodl9Vg9ot7kh9xqR-lYk9ty0ZgGBnt1b69Ubd_u1ZyxueA6DVe_4fwvwB3SK0o</pre>

### Before screenshot:
image
image
image

### After screenshot:
image
image
image

### CODE REVIEW

**Comment by deathbeam** [comment]
This formula is incorrect.

Correct formula is:

```lua
flaskData.lifeTotal * (flaskData.lifeAdditional / 100) * output.LifeRecoveryRateMod
```

From in-game testing with 2 flasks (first one is with 18% recovery mod second one without)

```
Nothing:
918
803
115 diff

10% flask eff:
1138
1022
116 diff

30% inc flask recovery rate:
921
805
116 diff

10% inc life recovery from flasks
1068
953
115 diff

10% reduced life rec rate
961
857
104 diff
```

**Comment by Peechey** [comment]
LifeRecoveryRateMod is a good point but duration _is_ over 10 seconds (no FlaskRecoveryRate used concerning the mod), I'm adding additionalRecovery to flask's recovery over the flask's duration and then showing what's leftover. Do you have the flask info or build I can use to test with the totalAdditionalAmount formula you're suggesting?

**Comment by deathbeam** [comment]
Oh I see what do you mean. I think that is a bit confusing, imo it would be better to just display the regen stat separate otherwise it gives wrong impression that the value is changing when you take sources of inc life recovery from flasks or flask recovery rate. 

E.g something like 

Life recovered: 3819 over 2.99s (additional life recovered: 381 over 10s).

Or even put that on separate line.
It is less fancy but a lot clearer in what it actually does.

**Comment by Peechey** [comment]
I believe the formula is correct now, I'm testing with one of my Scourge characters in game (with odd variety of flask nodes and life recovery rate nodes) and the values line up, but there is an issue with instant recovery flasks effective flask stats that I'm looking into.

image

In-game, RF'ed to 1 life, zero regen, then flasked back to 852 after 10 seconds, with rounding I'm pretty sure it's right

image

**Comment by Peechey** [comment]
Fixed instant flasks stats and adjusted the stats wording a little more (still open to opinions, I get what you're saying deathbeam, smarter way isn't as clear. I hope this way is a little more understandable). Showing total life recovered and then have the rundown in parentheses of how that comes to be. Examples below on new build
<pre>eNrNWltzGrkSfja_QkVVzlvMzbAOB-8WtrFDFSQcxknOPqXkGQFaa6TZkcaE3dr_flqaAWZtLo2yW3v84AzD1xd93Wp1y-n99C0W5Jmlmit5VW2c16uEyVBFXM6vqp8e7t5eVn_6sdKbULP4OLvOuLDf_Fg567lnItgzEyBXJYamc2Y-rzW1voKmhEqzYEqO6S8qvVfRVfWDkqxKHqmMuFl_CgXV-gON2VU1CEG4SqgOmYxutu9zYEy5DFT4xMx9qrLEmX3mbDlWEWCG48nH6UPJKJdlo-DzWW8i6IqlgaGGaPh1Ve3D0umc3dIYfoM2KjJmabi8bP_QuGi6361qbbdwkDAWlYSa-4CTlA1mMxYa_sxuUm5uFlSGW3P1fXKnYseZMDwRnKUlr9r7JN6_Uv7u3T7sgzJU3E6CDbR53uw0tyQdllPmuP9fuFlcCyDUw4qVHc4lN8xTeKK4VvI71lcW3R8iFT9y6bXCMZX0RmkEjyM-YzjkIMDhprA1cEjr5YSlsHkN3tmTBAoLAQsVFIhTbJwiUlqHnzEPyUHgI-BhKDDb6tDcH3T2axm4F3fLvuG0lYF7cUNpcNrKwAO-PSvjDhRM2DaoTv1AwQ-7FjuUIU7pJ5kyzdLn0jnRQQoU0d1W8vpBwSmbM-RKR4yFi3s4TKfUMNxu2KDah8mxWBQ5FriDnDZS4ARyrOALcs7fHQKfSM8XmkaI3SpZOl8FC84EAu24LIugOC0LINOhLHLiugfPVJc3V6NzeDU5HJccDBoBEIgYtvuZpOoX21-J08T6aayyFBmPHIxawGSx0jyEzsD1lVMWZSGuEG3axLF6ZjFkuOsxocHd0rxP9FpAa4xdOKgV4iSJvjE0fLpV0ZydZOR0iSBLEtjnNluwcnc8BZY1L51_bzsI9Edo_29ogmnd7JbCGtii0QZGfL4wEmYrvJUXIvi1LKjSJyxmC0ebuMuEQLXEE7UElQs7O-rT0GO67Sf2Tmh3KZO_rdD6_wRHGRjIKEttjqJtvJR4baZXc7O1fRrGiUqNe3lDRaidyqFMMkOkG4z1Exfiq8ziRzvz5f9ua0QZGXMdfn3MZjM7LVfBmdSN-IO7u8HNw_DzoBAJmKtUJFRC0EQzGJ8lF1XC4SGwxgKozaFBoGG8LMbq41g4Q8OUA33HoXaYRLjqRvPjODs1I2AQByoYlqKHVcJsxDWOpaLIHce68RiBy6dZzLLczIwhnYV0hcBtWggEdiBYnwt7xmF4GkP65ocjBg2HVcofM4PKKNf8IzywbTBiWeVGD5X5GFjRqCDMF13ZcWRxAmDSDtoEZIhu2YxBMqM2sisOD_SJyaLsrUtcz-0iTTTUvnsW6-sVnCV3ltAXdygxNZBuLB7ZW8gHZSsqDQ1LR_mt5IwKbUtdWc1V1aQZvIzYjGbCvv9PRgU3K1uyS28LFc5bvVBL25Tkeuzu1hCR0Sj_pi9MocIaWVt1K3pIGSPU9XO2g7SFOacFPpQvOYeRsx5TDc6vijS_qkJBh1oND-3Ly1arSgyoK12wQsOd353m4lbzWW8QwY6OPli5Wv7m03TkHs4WxiS6W6stl8vzhJqFmrFv0DCfhyquJaAGvHzrzpO31lCtDz_X8777cYpqa029_BI2N9Cr2dW4-Nnl2ocPCjae_c6-XH9wZHzmbEk0g2q_CExqV_ibUvHPbvWWy_eMmjFNCt7td0UcWkUUoKrecuAndVm2DqYF_nd95vaGBuJQ0G6fA2bcVXGmWX5P8oXRREn32trJj0oAurTMQ3Q2pXAyrLpk3L8f3lQGEBdJBbGlgtwB509EzUj_MZORrd2Vm5TOgPYusf5UJimb8W9dYu-dKwEcufbD73Doz1m38cdIwWBgFTk9_QgCBgHNX03BP-ixVo1KkVJd0qxXHAdT9muXdNoVOIoED7nRXVKvFHhCJaEbRaTReWPdc_r_BUvV_9a552v1pA_VRBriZBt1iIilRRM-syRFZLmAvIDkA4Qktpdz4i7Ylqc_E9bcRdh19vgooMEgfswVZNXP2384mQlNDadiKKGHkma9jPbXv5fd1uUbktrZDSgpGCtUsKjSaLXfEC7DlFFL2YbaFIbnSrvuIrB5SRN7Kx-RYgFi9X8RudauyAWMmcVfFznrw4uwNf7eqHU6B6JWuLLh85-MQyDUujnP6YUiB8U7HkbbgeMVprHFNPZhmlvM-k9SRR3cWwPLpa-sMIeRRrCkCcR-pTWwk5d_0t6aKaadnaIvxZo4scOoa6WM9nRo11qOOHXNhDlRZF9Id7nU3OVSy49eHAnNv0jsws_Jjp81pNguNn3y6UgE3jOYXsyphnZkUsfHzpH0uxdQmrSP4pb_Lmr42Lvwy4WGX-ZdHA8PhthT1e5KL8-Fo-pO28MfjxrYOmYmgpPSja4nhm83y1751fYRQm1JTCBen9eIdba9aW16xL3jt5NafunbOj3LLvzLvkdON7zJb2ES4gIDet3BHXX7O5ofZCT9o9DxyEr_MHxHumBLspVF7ho81IO5qR3Umj6ltOlNr2e5wMfTZzktBE8N_zBceLPV9lkNZr_4J_kRl_pxJnacbfngCgOju-pzd2zuz1JKzvgcEL3ay_8j-j_dM0-Z</pre>

image
image
image

**Review by Wires77 — APPROVED** [review]
LGTM

**Pull request merged**
