### PR TITLE
Add support for on-kill explosions

### LINKED ISSUE #2851: Explode mods aren't supported
**Is your feature request related to a problem? Please describe.**

Explode mods (e.g. Obliteration) have no support currently.  For certain builds, building around corpse explosion sources makes sense and it would be helpful if the damage could be estimated. 

**Describe the solution you'd like**

When explode mods appear, add a new pseudo skill called "On-Death Explosion" or similar and give it base damage and tags appropriately, based on % of monster life.  For example, Obliteration grants "On-Death Explosion" that deals 5% base secondary chaos damage that scales by global damage, chaos damage, and area damage, and can be mitigated by chaos resistance and inc/red chaos damage taken by enemies.  It also can apply poison with global chance to poison on hit, and poison mods apply to its damage.  

For example, a character with 200% increased chaos damage would deal 15% damage with this explosion source.  

Multiple sources of explode (e.g. Occultist with 2x Obliteration) all apply to the base damage of the pseudo skill.   

Many explode mods can be found on the [Wiki](https://pathofexile.fandom.com/wiki/Explode), but some may need to be amended.  

**Describe alternatives you've considered**

**Additional context**

I'm hoping to work on a pull request to implement this feature but I don't know where to start.  I've reached out to join the discord so I can start developing it myself.  I'll update the feature request as I work on it.

### PR DESCRIPTION
**Pull request by Edvinas-Smita**
Fixes #2851.
Supersedes #2070.

### Description of the problem being solved:
Building around explode mods is harder than it needs to be.

### Things that can be improved:
- Ailments - don't know what the end result should look like for chance to explode mods

### Link to a build that showcases this PR:
https://pobb.in/1uqMcLIhdiDD

### Before screenshot:
image

### After screenshot:
image
image
image

### CODE REVIEW

**Comment by Nightblade** [comment]
You can fix the spelling warning if you use a capital P in `notNumpart`.

**Comment by QuickStick123** [comment]
There are some gems with relevant mods that you may want to consider supporting.
I am also not 100% sure how these interact with chance to destroy corpse on kill.
https://pobb.in/mEMB8idC83FX
image
image
image
image
image

**Comment by Edvinas-Smita** [comment]
To the best of my knowledge, multiple effects can happen at the same server tick, so a corpse can be destroyed and exploded by any amount of sources at once.

Decoy totem and Cremation alt quality explosions scale a bit too differently to the other "global explode" mods.

Bane would fit the theme quite a bit more, but it also looks a bit more tedious to implement. It is also an effect which can only trigger from using the skill itself and can not chain. I considered not including other explode sources that have a condition of the enemy being killed by attack or spell hits, due to them being shown as equally powerful as unconditional explode mods, while in practice it is a night and day difference of power. Those mods were included only because it was easy to do so.

**Review by LocalIdentity — APPROVED** [review]

**Comment by aliunwala** [comment]
The "on monster kill explosion" feature used to appear under the "main skill drop down" 
image

I no longer it see it there. I have gear that should give explodes. (This was working during 3.21 but seems to have stopped working during 3.22) 
Here is a POB: https://pobb.in/aXR1T99oPDvz

Did  "on monster kill explosion" feature move? 
(Hopefully I am just blind and need someone it point it out to me.)

Thanks for any help/pics

**Comment by LocalIdentity** [comment]
> The "on monster kill explosion" feature used to appear under the "main skill drop down" image
> 
> I no longer it see it there. I have gear that should give explodes. (This was working during 3.21's POB versions but seems to have stopped working during 3.22's POB versions)
> 
> Here is a POB: https://pobb.in/aXR1T99oPDvz[Poblink](pob:pobbin/aXR1T99oPDvz) that replicates the issue
> 
> Did "on monster kill explosion" feature move? (Hopefully I am just blind and need someone it point it out to me.)
> 
> Thanks for any help/pics

I just had a look and found that we accidently broke support for the wording on the Crusader Body armour mod. We'll fix it for the next update but for now just change the wording from `a tenth` to `10%`
The whole mod should look like this `Enemies you Kill have a 35% chance to Explode, dealing 10% of their maximum Life as Physical Damage`

**Comment by aliunwala** [comment]
Yep that fixed it. Thanks for that! And the crazy fast response.

Tested it locally and it works:
image

One more note you need to make sure it works for the bow/weapon mod too, for when you make the change:
image

**Comment by LocalIdentity** [comment]
Yeah, I had a look and it broke on a bunch of other things too. Synth implicit mod, Obliteration, new explode tattoo and the Chaos cluster jewel mod

**Pull request merged**
