### PR TITLE
Add support for Dark Ideation

### LINKED ISSUE #429: Implement Dark Ideation Notable
Mod does not parse:

    2% increased Chaos Damage per 100 maximum Mana, up to a maximum of 80%

### PR DESCRIPTION
**Pull request by ppoelzl**
Fixes #429

### CODE REVIEW

**Comment by ppoelzl** [comment]
Selected the wrong branch, will fix it and open a new PR.

**Comment by ValentinUsedREKTItsSuperEffective** [comment]
Hello, 

Modifications done to Dark Ideation aren't effective. I don't know if it might help but replacing

**Comment by ValentinUsedREKTItsSuperEffective** [comment]
Hello, I think there had some regression concerning Dark Ideation as the modification in modParser doesn't exist anymore.

**Comment by LocalIdentity** [comment]
The node is working perfectly as intended and was readded in this PR https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/570

**Pull request closed without merging**
