### PR TITLE
Add support for several different spectres: Arena Master, Ruins Hellion (partial), Trial Windchaser, Aurid Synthete, Ancient Wraith, They of Tul, Ancient Suffering, Merveil's Retainer, Primal Crushclaw, and Primal Rhex Matriarch

### LINKED ISSUE #743: Add ruins hellion to spectre list.
im not sure if they add to my spectre buffs or not (rallying cry)
but would be great if i can see them in the list

https://poedb.tw/us/mon.php?n=Ruins+Hellion

### LINKED ISSUE #1775: Feature Request: Add Arena Master and its buff to the spectre pool
Monster stats: https://poedb.tw/us/Arena_Master#Lvl84
Monster's primary ability that is sadly not listed on poedb: buff called Arena Master's Presence

image

Buff is AoE and provides to everyone in range:
- 20% increased damage
- 20% increased Attack Speed
- 20% increased cast speed
- 20% increased movement speed
Base duration: 3 seconds

With that, please also provide a checkbox when Arena Master is selected as an active spectre: "Are you and your minions affected by Arena Master's Presence?"

### LINKED ISSUE #2315: Add support for spectres' warcries (and maybe add Ruins Hellion to the spectre library)
Some spectres have powerful warcries that make them really useful, e.g. the [Ruins Hellion](https://poedb.tw/us/Ruins_Hellion), which performs a Rallying Cry that causes all nearby allies to take 30% less damage from enemies taunted by the Ruins Hellion.

Although with some effort it is possible to get the Ruins Hellion itself to at least show up in Path Of Building, by modifying the relevant .lua files, there is currently no support for its warcry skill as far as I can tell.

Ideally, this would work in the same way as the option to enable curses for raised spectres under the Skill Options section of the Configuration page, with an extra checkbox to enable the effects of warcries, or maybe making the existing checkbox enable warcries and curses simultaneously.

### LINKED ISSUE #2598: Trial Windchaser spectre
Снимок
Trying add new spectres 
Copy the code from spectre button on poe db (https://poedb.tw/us/Trial_Windchaser)
Paste it in this files by notepad+ and got a errors,
Снимок1
After removing new spectre text all work good, any help or tips how to add this spectres in pob?

### LINKED ISSUE #2894: Please add a couple more spectres: "Ancient Wraith", "Wraith", "Aurid Synthete" if possible
**Is your feature request related to a problem? Please describe.**
There are a couple spectres I'd like to see added. I've tried to add them manually but it produces errors and doesn't work.
the spectres are:
Ancient Wraith
Wraith
Aurid Synthete

**Describe the solution you'd like**
Add the above spectres to the list

**Describe alternatives you've considered**
I've tried adding the code to the spectre lua and skills lua, but when I try for these spectres it doesn't work

**Additional context**
Having some physical spell projectile spectres like the ones above would be amazing for spectre builds, but it's very hard to accurately find their dps

### LINKED ISSUE #3965: Add Support for Primal Rhex Matriarch Spectre
### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Is your feature request related to a problem?

One of the recommended spectres for Absolution builds is the Primal Rhex Matriach from Harvest as it has an AoE lightning debuff it perodically applies. As far as I can tell, it is yet to be implemented in Path of Building.

### Describe the solution you'd like

I'd love it if it could be added to the spectre library. Here's a link to the spectre-able monster on PoEDB:

[Primal Rhex Matriarch ](https://poedb.tw/us/Primal_Rhex_Matriarch#PrimalRhexMatriarchHarvestRhexT3Spectre)

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Lothrik**
PoB: https://pastebin.com/5BWwNYxT

Trial Windchaser: Fixes #2598.
Arena Master: Fixes #1775.
Ruins Hellion: Fixes #2315. Fixes #743.
Ancient Wraith and Aurid Synthete: Fixes #2894.
Primal Rhex Matriarch: Fixes #3965.

[Arena Master](https://poedb.tw/us/Arena_Master#ArenaMasterAdjudicatorGrandMasterSpectre) is used for its unique [Arena Master's Presence](https://poedb.tw/us/Arena_Masters_Presence) skill that grants "20% increased Damage, Attack, Cast and Movement Speed" for 4 seconds with a.. 12 second cooldown apparently? I'm pretty sure this used to give 40% and had an 8 second cooldown &mdash; pretty severe nerf. I'm not convinced implementing this buff is worth the effort.

[Ruins Hellion](https://poedb.tw/us/Ruins_Hellion#RuinsHellionHellion3Spectre) is apparently used for the "Enemies Taunted by you deal 30% less Damage with Hits and Ailments against other targets" component of its Rallying Cry skill, but PoB doesn't even implement effects like that for the player, never mind a minion that has ~8K HP and is apparently used for a taunt..?

[Trial Windchaser](https://poedb.tw/us/Trial_Windchaser#TrialWindchaserGuardBowColdSpectre) and [Aurid Synthete](https://poedb.tw/us/Aurid_Synthete#AuridSyntheteSynthesisSoulstealer4Spectre) seem fully functional. Aurid Synthete has a lot of weird triggered spells.

[Ancient Wraith](https://poedb.tw/us/Ancient_Wraith) has +1 curse and Enfeeble on Hit.. which seems **extremely** valuable but I'm not sure how to implement it.

Preview: 

New config option ("enable buffs" -- note that both of these options default to Enabled): 

Brief documentation:

### CODE REVIEW

**Comment by Lothrik** [comment]
I just noticed the ``DelveMonsterEnfeebleOnHit`` and ``AdditionalCurseOnEnemies_`` entries in Ancient Wraith's modList. I'll see if I can get that mechanic working.

**Comment by Lothrik** [comment]
Ancient Wraith's +1 curse and Enfeeble on Hit thing works now. I had to add support for like.. everything.. to get this working.

**Comment by Lothrik** [comment]
Added [Ancient Suffering](https://poedb.tw/us/Ancient_Suffering) (Temporal Chains on Hit) spectres.

The two curse on hit spectres and Arena Master are basically 100% functional now.

They need to be set as the active spectre somewhere (not just in your spectre library) for their unique effects to show up properly under calcs.

**Comment by Lothrik** [comment]
As the curses used by Ancient Suffering and Ancient Wraith can't be datamined and are relevant for #3930, I asked viperesque what the proper internal names are for their curse skills and replaced my placeholder internal names:

Ancient Wraith Enfeeble on hit is from the DelveMonsterEnfeebleOnHit mod

Ancient Suffering Temporal Chains on hit is from the MonsterChanceToTemporalChainsOnHit1 mod

**Comment by Lothrik** [comment]
Added Frigid Roar to [Primal Crushclaw](https://poedb.tw/us/Primal_Crushclaw) spectres and added [Primal Rhex Matriarch](https://poedb.tw/us/Primal_Rhex_Matriarch) spectres (plus their Thunderous Roar debuff). Both debuff values were confirmed by viperesque.

**Review by Wires77 — APPROVED** [review]
LGTM!

**Pull request merged**
