### PR TITLE
feat: added possibility to compare gem quality in dps

### PR DESCRIPTION
**Pull request by sebbi08**

### CODE REVIEW

**Comment by LocalIdentity** [comment]
I'm not too sure what this feature is meant to achieve, we can already compare the difference quality makes on a gem

**Comment by sebbi08** [comment]
ok how is it currently possible ?

**Comment by Wires77** [comment]
Seems to be some issues with this one:

image

**Comment by sebbi08** [comment]
oh, yea I fixed that bud somehow missed pushing it. When I am back home I will have a look

**Comment by ppoelzl** [comment]
Superseded by #2800

**Pull request closed without merging**
