### PR TITLE
Refactor project structure

### PR DESCRIPTION
**Pull request by ppoelzl**
Preparatory changes for automated testing and version 2.0.0:
* Change project structure to `src` layout
* Unpack runtime to `runtime` directory
* Update launcher to latest version to recognise new layout
* Delete skill tree zip files as they are no longer needed
* Add new manifest sources to support new layout
* Update manifest updater script to recognise new layout
* Update documentation to reflect new layout

Note that even though future versions of Path of Building will update with the files in the `runtime` directory, unlike the skill tree zip files, `runtime-win32.zip` has to be kept and maintained indefinitely, for backwards compatibility. Otherwise, updating from installations <= 1.4.170.27 would fail to update `Path of Building.exe` due to the whitespace characters in that file name. Newer versions of Path of Building are patched and don't exhibit this behaviour anymore. However, it is not possible to patch older versions to perform an intermediate update to patch the downloader, before attempting to download the latest version.

### CODE REVIEW

**Comment by Wires77** [comment]
I tested replacing my manifest.xml with the one from your branch to test the update process, after tweaking the branch and repo owner names, of course.  My main PoB checked for updates and found none.  I believe this is expected, since there were no changes to the underlying files, but let me know if it isn't.

I also tested some standard dev practices with the new executable location.  The first thing I noticed is that the `Builds` directory moved into `src/`, which means dev builds won't be listed anymore until they're moved into the new location.
Additionally, the new executable doesn't seem to play well with debugging, as I get this error when using the EmmyLua debugger in PyCharm:

image

The old executable still works fine, since the new executable is mostly for updates anyway.  Neither of the dev issues are showstoppers, but we may just want to communicate that when the update is pushed out.

**Comment by ppoelzl** [comment]
* I haven't regenerated the manifest hashes, so it's expected that there is no update. I thought I did though. Ma bad!
* You're right that we have to notify our contributors that their default testing build location changes as well.
* EmmyLua not working with the updated launcher is a new bug introduced by fixing #1745. To my knowledge, separating of executing environment and injecting the debugger are mutually  exclusive, so we might have to revert the fix.

**Comment by Wires77** [comment]
Tested this some more, updater seems to work fine in various states of update.  I did have to add a hack to replace `PathOfBuildingCommunity` with `ppoelzl` when doing the update check, otherwise it couldn't find the files.

> EmmyLua not working with the updated launcher is a new bug introduced by fixing #1745. To my knowledge, separating of executing environment and injecting the debugger are mutually exclusive, so we might have to revert the fix.

Yeah, there have been a few old issues complaining about LUA_PATH, so I'm hesitant to fully revert, even if the issue is pretty niche.  If we can't figure it out having a working debugger is going to win out though, I agree.
- https://github.com/Openarl/PathOfBuilding/issues/848
- https://github.com/Openarl/PathOfBuilding/issues/588
- https://github.com/Openarl/PathOfBuilding/issues/1062
- https://github.com/Openarl/PathOfBuilding/issues/728

**Review by Wires77 — APPROVED** [review]

**Review by Wires77 — APPROVED** [review]
Rebased off of the dev branch, should be good to merge now

**Comment by ppoelzl** [comment]
Yeah, LGTM too.

**Pull request merged**
