### PR TITLE
Revert "Add latest and trending builds list to the build list module …

### LINKED ISSUE #7944: Trending Builds section should be not be present.
I feel like everything around merging the 'Trending Builds' advertising feature was a mistake. 

The biggest issue is of course that this is thinly veiled advertising for a for profit website. The site has active advertisements and directly profits off other people's content that it scrapes. Path of Building should probably not be funneling money directly to a random entity with a default feature.

The content that it scrapes is also another problem. The site being advertised is clearly just scraping youtube channels and posts on reddit to get builds, this is pretty blatantly seen in the presence of a video that has a whopping 0DPS being one of the first visible builds when looking at the page in Path of Building.

clicbait_zdps

In general that the list of builds is a mix of misreported DPS with clickbait, youtube oriented titles and a literal link to something that isn't a build doesn't inspire a great deal of confidence in the feature, and that's ignoring [a lot of other issues I have with the presentation in general](https://www.reddit.com/r/pathofexile/comments/1ebtnrd/comment/levgk8o/).

The list of builds also does not have a way to access where the build originates, the preview button takes you to pobarchives.com and you have to actively scroll down to find the video, which has already exposed you to said advertising.

You also cannot ever turn off 'Similar Builds' as a button, it simply displays forever without being able to try and find builds. I feel like this is also a poor feature in general as 'similar builds' is very vague and doesn't really present enough information on why something is similar at all.

The feature in general is putting a lot of power in the hands of a single entity running a for profit, closed source website [that allows people to actively pay to advertise their builds](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/7943) which the layperson will ***100% assume is directly affiliated with Path of Building***.

As an aside, the operators of the site itself are also [actively running a reddit bot](https://www.reddit.com/user/Civil-List8387/) that actively attempts to redirect people away from an open source, non-profit, ad-free site (pobb.in) to his own for profit, closed source site that fulfils functionally the same role. 

I find it very hard to believe anything about the implementation of this feature was done with any goal other directly feeding people to a very specific website, this seems doubly obvious with the request for the site to be 'default' in the original pull request.

I'm genuinely baffled how anyone thought merging it was a good idea and feel like this implies a need for greater controls on what gets merged into the actual app in general.

### PR DESCRIPTION
**Pull request by kwjanssen**
Reverts (#7389)

This reverts commit 8bea7bd77822ac8bbab876d49e1a8181e217581c.

Fixes #7944 #7946 #7943 #7941 .

### Description of the problem being solved:
Removes integration with 3rd parties that could be abused. See various discussions in issues for more context.

### Steps taken to verify a working solution:
- Revert

### Link to a build that showcases this PR:
N/A

### Before screenshot:
before revert

### After screenshot:
after revert

### CODE REVIEW

**Comment by enpinzolas** [comment]
I would not be necessarily against the similar builds feature as long as it can aggregate from more APIs (poe-vault, maxroll, etc...) since the sorting algorithm is based from similarity (passives, items, skills) instead of some potentially PTW feature, but the trending page really should just go.

**Comment by snt0** [comment]
Better integration would involve the user initiating the search. Maybe a "find similar builds" box that matches on common skills?

**Comment by niklasstich** [comment]
The fact that this is enabled by default and you seemingly can't deactivate it at all is ridiculous. Why is there no "None" option in the drop down (which should be selected by default)? 
image
This is some crazy entitlement for an open source project.

**Comment by mcarabolante** [comment]
Let's say that by default there shouldn't be any site selected, it should be up to the user to decide which one he wants to use as a datasource, that would deal with one issue.

However, there is another major one, who, based on which discretions will define which site should or not be integrated with PoB, reason I ask this, there are certains sites that are known for offering low quality/non functional builds, should they be allowed in PoB? If not why? What is worse there are known ones that does RMT.

While I dont mind the UI/UX, the feature itself looks great and can be very helpful for newcomers, the datasource issue might generate enough issue to make it not viable

**Comment by Orden4** [comment]
> However, there is another major one, who, based on which discretions will define which site should or not be integrated with PoB

The completely hands-off approach would just be to not provide any options and just require users to add sites via plugins hosted on their site. Like that, it is entirely up to the users discretion which sites they are interested in seeing builds from. That being said, I have no clue if this can be done in an easy/safe manner.

**Comment by sirgregoryadams** [comment]
All the arguments here are valid, _however_, this should all be discussed _before_ the feature is added. So, until all of this has been clarified, I strongly believe that it should be removed.

**Comment by Wires77** [comment]
> All the arguments here are valid, _however_, this should all be discussed _before_ the feature is added. So, until all of this has been clarified, I strongly believe that it should be removed.

To be fair, the PR that this is reverting was open for 5 months without any responses other than mine.

**Comment by sirgregoryadams** [comment]
> > All the arguments here are valid, _however_, this should all be discussed _before_ the feature is added. So, until all of this has been clarified, I strongly believe that it should be removed.
> 
> To be fair, the PR that this is reverting was open for 5 months without any responses other than mine.

For sure. Absolutely no blame at all. What I'm suggesting is to remove the feature for now, and have that discussion in the context of the reaction the feature received. That's all.

**Comment by MagerlinC** [comment]
I agree that this feature has an odd feel to it. While I understand the idea of new-player appeal for browsing builds, there are other tools out there for that, and most people I have talked to so far were primarily mildly shocked to see clickbait titles all over their build planning tool. Maybe this could be improved with other resources for builds added, but for now, I would also be in favor of reverting.

If there are also financial ties to the platform in question.... Well.

**Review by murphyfa — APPROVED** [review]
**This feature was added with the intent of personal gain by the author and should be reverted immediately.** For the integrity of the project, none of this author's code should be trusted or kept. If there's any room for discussing a similar, community-driven feature, that should be proposed separately.

LGTM 👍

**Comment by jjstewart** [comment]
> > All the arguments here are valid, _however_, this should all be discussed _before_ the feature is added. So, until all of this has been clarified, I strongly believe that it should be removed.
> 
> To be fair, the PR that this is reverting was open for 5 months without any responses other than mine.


What am I missing here?

image

**Comment by 0x42424242** [comment]
Just want to add support for removing this feature. Path of Building is amazing software, and it does it's job - build calculation - fantastically. Adding the amalgamation of public builds and a browsing feature feels like a significant step away from it's original purpose. 

Sometimes, in my opinion, it's much better for a tool to do one job, and do it exceedingly well, rather than scope creep out into different areas. Often these secondary features are only half baked, and add significant maintenance overhead to the project.  It really feels like separate websites, whoever they are (maxroll, pob archives, poe vault, poe ninja) are a more suitable place to take care of this amalgamation problem. 

Please don't go down the  "Path of Building has to be the only needed tool" path. 

With that said, I acknowledge that nothing was said on the original PR so I don't feel like this is the merger's fault in any way.

**Comment by aymendps** [comment]
At first, I liked the idea, but after considering the unnecessary risks/maintenance the project will have to take, and the lack of transparency behind the PoB Archives website owner, I believe this feature has to be reverted. If there is a adjusted version to be added in the future, I suggest one that does not have the "trending" space, or any space that encourages monetized content/ads. But rather a "search" space where the user can search for builds by skill/name/creator. The search can then be conducted through multiple providers that are trusted by the community, and will only be there as an opt-in feature for the user to LOOK for something specific, rather than getting bombarded by rmt biased boosted builds.

**Comment by PPFilip** [comment]
> > All the arguments here are valid, _however_, this should all be discussed _before_ the feature is added. So, until all of this has been clarified, I strongly believe that it should be removed.
> 
> To be fair, the PR that this is reverting was open for 5 months without any responses other than mine.

Which also means, that the guy pushed it few days after he started scraping all reddits and pester people with his bot. I'd say the lack of interest then vs now, is because regular users (me included, I am not a contributor here) usually won't follow repos for changes to comment on - for better or worse.

If this feature is to stay, it should be done in less intrusive way - disabled by default (at the risk of getting lost though) or enabled but with no site preselected (with a text saying you can select a provider in dropdown or smth), so people are not giving telemetry to a random 3rd party without consent the moment they start pob.  I'd argue that I do not mind hitting pob update link on start, or load data when I press import build,  but the act of calling extra API on launch that is not necessary to function or run the game is a bit too intrusive.

**Comment by Moremackles** [comment]
Adding my two cents: It's a cool feature, but other replies here have convinced me it is not handled the best way. I would rather it be removed then implemented the way it is currently since it's unclear who would take up the mantle of refactoring it to be less intrusive. That being said, I can see the upsides and I wouldn't be upset if it stayed.

**Comment by calmbook1300** [comment]
Please respect your _users_ and don't fill PoB with clickbait.

**Comment by jjstewart** [comment]
Is this going to get merged?

**Comment by Nightblade** [comment]
Latest / trending builds list is currently disabled, see #7995

**Pull request closed without merging**
