### PR TITLE
Fix impale not using enemy damage taken

### LINKED ISSUE #7787: Impale damage doesn't take the right average damage hit to calculate impale dps
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### Check for support

- [X] I've checked that the calculation is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What platform are you running Path of Building on?

Windows

### What is the value from the calculation in-game?

In game the calculation is that each stack of impale take 10% of the incoming damage. So if I inflict a 10000 physical damage hit, I should have 1000 damage stored. PoB actually does this well but the average hit taken is wrong.

### What is the value from the calculation in Path of Building?

I have a build with an average physical hit of 330000 physical damage. The average physical hit taken is 150000 but I cannot find this value anywhere from the impale calculation.

### How to reproduce the issue

- Get a melee skill.
- Put a phys weapon.
- Get 100% impale chance and watch the average hit indicated on your skill and the average hit used by the impale calculation
- See the difference.

### Character build code

```shell
https://pobb.in/pvEW2M29dUAN
```

### Screenshots

image
image

### PR DESCRIPTION
**Pull request by mcheese**
Fixes #7787 .

### Description of the problem being solved:

Impale damage did not respect enemy damage taken modifiers. This bug is a result of fixing impale armour application recently.

Clarify "average physical hit" in impale breakdown as "average physical hit before mitigation".

### Steps taken to verify a working solution:
- Checked changes to impale dps with different "enemies take % more physical damage" modifiers and Pride/Vulnerability
- Tested with minimal example and real build

### Link to a build that showcases this PR:
https://pobb.in/wFfb1O9sTa5M

Change first line in Custom Modifiers and watch dps change. 1000 Hit DPS, 100% impale, 10% more damage taken, ignore all armour.

### Before screenshot:
image

### After screenshot:
image

----

As far as I can tell, the only relevant modifiers are `DamageTaken` and `PhysicalDamageTaken` (Physical reduction and Armour works already), Other modifiers affecting impale, like reflected damage or flat subtractions seem not relevant to enemy calculations. 

Impale damage is still not affected by attack damage taken, like Intimidate. Which I think is correct, but not 100%.

Also my first contribution, hope this is right.

### CODE REVIEW

**Review by Wires77 — COMMENTED** [review]
I'm actually not certain this is where the problem lies.  If you instead have "+100% critical strike chance" instead of "never deal critical strikes", the initial impale damage does already take into account increased damage taken.

This PR would make that double dip on increased damage taken

**Comment by mcheese** [comment]
Oh, seems like crit impale damage also still suffers from getting double reduced by armour.

**Comment by mcheese** [comment]
The later Impale calcs were combining the pre-mitigation `impaleStoredHitAvg` with post-mitigation `PhysicalCritAverage`.
But `impaleStoredHitAvg` is already a combination of crit and non-crits (maybe bad variable name?).

**Comment by Wires77** [comment]
Sweet, your fix is what I suspected it would be.  Do you want to expand on these tests I started in your PR too?  https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/7845/files

**Comment by Wires77** [comment]
Just steal them, way easier that way

**Review by Wires77 — APPROVED** [review]
These tests look great, thanks for adding them!

**Comment by gogonextwave** [comment]
Just register a account to say: This update seems wrong, my impale dps don't change by toggle on intimidated.

POB version: 2.45.0 
https://pobb.in/1oPxp3XfX9Et

**Comment by mcheese** [comment]
We talked about Intimidate, and other "increased Attack Damage taken" effects a bit. Ultimately it needs ingame testing.

For now, I'm of the opinion that it should not increase impale damage. As impale damage is stored before mitigation and damage taken increases, and then dealt as Reflected Physical Damage, which will be modified again. This damage should not be affected by Intimidate.

As said, I'm not 100% certain on this, it needs some actual confirmation.

**Comment by gogonextwave** [comment]
> We talked about Intimidate, and other "increased Attack Damage taken" effects a bit. Ultimately it needs ingame testing.
> 
> For now, I'm of the opinion that it should not increase impale damage. As impale damage is stored before mitigation and damage taken increases, and then dealt as Reflected Physical Damage, which will be modified again. This damage should not be affected by Intimidate, as it is no longer Attack Damage.
> 
> As said, I'm not 100% certain on this, it needs some actual confirmation.
> 
> Other thought: there is Impale from spells, which you won't expect to be influenced by Intimidate either. And I don't think there is a difference depending of the source of the Impale stack.

impale wiki: 
QT$A3R 5PGMV8WYTMC3ABE5

Vulnerability(take increased damage taken) can affect impale damage.

**Comment by mcheese** [comment]
Yes, and this patch was about this. Vulnerability, Pride, Maim(gem), etc are all working for Impale.

Intimidate is increasing **attack** damage taken. Vulnerability is increasing **physical** damage taken. They difference is "attack".

**Comment by gogonextwave** [comment]
So in your opinion, flesh and stone don't work too?

**Comment by mcheese** [comment]
Current Flesh and Stone says `While in Blood Stance, Aura makes Enemies take up to 20% more Physical Damage from Hits`. This should work. Physical Damage from Hits is fine.

**Comment by Minimonium** [comment]
Flesh and Stone doesn't contribute to the impale damage in the current version of PoB.  

With Poacher's Mark impale damage is calculated correctly (see Average Hit), while Flesh and Stone is ignored in the calculation. 

https://pobb.in/HZCd68ql348l

image
image

vs Poacher's

image
image

**Comment by mcheese** [comment]
Yeah, just checked too. That's a bug. I'll get on it in a bit.

**Pull request merged**
