### PR TITLE
Made inspiration charges default to maximum

### PR DESCRIPTION
**Pull request by Wires77**
Thought about doing the same for Intensify and Infused Channeling, but those work differently and would take more work than I have time for at the moment.

### CODE REVIEW

**Comment by Nostrademous** [comment]
@Wires77 can you tackle issue #559 this (if it's still an issue) here too?

**Comment by Wires77** [comment]
> 
> 
> @Wires77 can you tackle issue #559 this (if it's still an issue) here too?

It was a lot more obvious after these changes.  I fixed it with the latest commit, however the fix seems kind of odd and leaves me wondering why we do different calculations for the main skill and the calcsTab skill.

**Comment by Nostrademous** [comment]
I can't specifically to this instance as don't know which part of the code you are referencing, but in CalcsTab we have different modes at top (effective, in-combat, etc) which have different buffs (and charges) present or not depending on selection. Possibly why.

**Comment by Minimonium** [comment]
Would it be better instead to calculate an "average" by default DPS for it? 
There is a downtime on the gem which is proportional to the attack mana cost, simply setting the number of charges to maximum would be misleading. Does PoB already calculate the DPS with respect to the charges uptime?

**Comment by Minimonium** [comment]
The coefficient would be in the manner of
```
reset_mana = 800 // assume that we start the reset count from the first attack
recharge_average_charges = 2 // (0 + 1 + 2 + 3 + 4) / 5
mana_cost = X
recharge_attacks = 5
recharge_mana = mana_cost * recharge_attacks
coef = (recharge_average_charges * recharge_mana + (reset_mana - recharge_mana)) / reset_mana

max_charges_dps = ...
effective_dps = max_charges_dps * coef
```
Here we calculate how much DPS we lose depending on the ratio of the recharging part of the reset mana value

**Comment by Wires77** [comment]
The problem with calculating an average for this is that you exclude setups that generate charges with one skill and almost never remove them, e.g. Righteous Fire.

The majority of builds are going to have a sub-100 mana cost and thus will spend at least 50% of their cast/attack time at full charges, anyway.

If you want to make a separate feature request for calculating the average, feel free, but that's beyond the scope of this PR.

**Review by ppoelzl — APPROVED** [review]
LGTM. Reasonable changes to enable accurate DPS sorting for Inspiration Support.

**Pull request merged**
