### PR TITLE
Added DPS calculations for Toxic Rain

### PR DESCRIPTION
**Pull request by kkienzle**
Implemented DPS Calculations for Toxic Rain in three different variations, including an estimated average overlap of the sporepods. The formula for the average DPS overlap is a shortened version of the one from this reddit thread:
https://www.reddit.com/r/pathofexile/comments/9ik19a/toxic_rain_calculator_spreadsheet_and_guide/

The given numbers for the different radius sizes are estimates based on my own ingame observations with comparisons to RF setups of different sizes as well as the observations of the proportions of the OP in the above linked reddit thread. Onfortunately we don't have the exact numbers for the different area sizes of the skill to improve on these estimates.

### CODE REVIEW

**Comment by NickRyder** [comment]
Can you please separate out the average dps overlap into a separate PR. We are still contemplating whether we want to support such features.

**Comment by kkienzle** [comment]
Ah ok, that makes sense. Could i instead include an option in the config tab to manually set the amount of pods that should be included in the calculation?

**Comment by NickRyder** [comment]
Yes, that sounds good.

**Comment by kkienzle** [comment]
Removed the average DPS overlap and instead included a config option for the number of overlapping pods.

**Comment by LocalIdentity** [comment]
Added in 1.4.169.1

**Pull request closed without merging**
