### PR TITLE
Add support for Sandstorm Visage crit mod

### PR DESCRIPTION
**Pull request by andrewbelu**
### Description of the problem being solved:
Add support for Sandstorm Visage main hand crit -> spell base crit

### Steps taken to verify a working solution:
- Ensured crit chance is not affected when main hand is empty
- Base chance is set to main hand's critical strike chance when a weapon is equipped in the main hand
- Base chance is increased with b

### Link to a build that showcases this PR:
https://pastebin.com/KVyAewuk

### After screenshot:
image
image

### CODE REVIEW

**Comment by QuickStick123** [comment]
Minor note the way you implemented it the mod would be considered baseCritFromMainHand as the application to spells is handled exclusively by the config and spell tag.

**Comment by andrewbelu** [comment]
Fair enough, perhaps in future use cases it may come into play. Updated

**Comment by QuickStick123** [comment]
Fixes https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/5342

**Review by LocalIdentity — APPROVED** [review]

**Comment by QuickStick123** [comment]
It works you probably forgot to rebuild mod cache
image

Testing this mechanic ingame saw unarmed setting base crit on spells to 0% which this doesn't do.

**Pull request merged**
