### PR TITLE
Fixed Summon Holy Relic's Boon Aura

### LINKED ISSUE #187: Summon Holy Relic dps is wrong
Hey

Summon Holy Relic's dps is right now calculated using the players cast speed of the spell, not the minions "Skill cooldown"

Here is a ss of the skill at lvl 20
image
The dps shows up as 1869.5 since the players cast time is 1 sec, but the dps is actually 7478 since its 4 times faster at casting the spell!

### PR DESCRIPTION
**Pull request by kkienzle**
Fixes #187, although im not sure if the life regen for minions should include the buff affecting allies, which has a lower regen value. I changed the effectType from Aura to Buff because ingame testing shows that the regen value provided by the Holy Relic on the player is not affected by aura effect.

### CODE REVIEW

**Comment by ppoelzl** [comment]
It's a buff it if comes with a green border on the icon: https://pathofexile.gamepedia.com/Buff

**Comment by kkienzle** [comment]
Good catch. Does that give us any info wheter both regen values stack on minions or if only the stronger regen value is applied to them?

**Comment by PJacek** [comment]
@ppoelzl I don't like these changes. 
- The damage should be displayed as average hit. The nova triggers when player hits with an attack. It's almost never going to be exactly when cooldown ends.
- For some reason GGG has moved the regen data from the nova skill to the summon skill. This implementation while almost working correctly is technically incorrect as the buff is now granted by the player. (Equip Ichimonji, level 20 relic gives 339 life regen to minions instead of 309)
- The enchantment "Summoned Holy Relics have x% increased Buff Effect" doesn't apply.

**Comment by kkienzle** [comment]
Seems like the whole hittimeoverride stuff does not make a lot of sense, ill remove that part and instead create a seperate PR that changes the DPS display to instead show the average hit.

@PJacek i don't think there is currently a way to correctly implement global buffs targeted towards minions in pob apart from the `skill("buffMinions", true),` basemod, which affects the whole skill (e.g. Offerings). I haven't looked to deep into this but it might make more sense to "fix" buff effect scaling from ichimonji to only affect buffs on the player instead (On that note the Carrion Golem implementation uses the same way to apply buffs which get scaled by Ichimonji too, which seems unintended as well).

I'll add support for the helmet enchantment too, kinda forgot about that tbh.

**Comment by ppoelzl** [comment]
@kkienzle Skill-specific buff effect modifiers have to be manually added in `CalcPerform.lua`.
@PJacek made some good objections, so I'm assigning this PR the "wip" label" until the hit time override, regen target and buff effect scaling are fixed.

**Comment by kkienzle** [comment]
I've added support to define the `buffNotPlayer` and `buffMinion `flags as part of a tag for buffs in `CalcActiveSkill.lua`, which enables the possibility to define these conditions on a per mod basis instead of applying them to the whole skill. This was in my opinion necessary to ensure that both of the buffs of the holy relic skill get scaled appropriately by increased buff effect.

**Comment by Wires77** [comment]
@PJacek @ppoelzl This is ready for re-review

**Review by LocalIdentity — APPROVED** [review]

**Pull request merged**
