### PR TITLE
Rough Aurabot Exporter

### PR DESCRIPTION
**Pull request by NathanielHinshaw**
Super rough aurabot exporter, requires you to add a minion to the build, hover over the calc'd buff window on the calc's tab with minion stats selected, and then click the export button.  first time ever using Lua, so its pretty hacky, but it could come in handy down the line, if somebody who had a better understanding of Lua and/or the application design were to redesign it

### CODE REVIEW

**Comment by QuickStick123** [comment]
Superseded by https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/4967

**Comment by NathanielHinshaw** [comment]
@QuickStick123 this doesn't do quite the same thing as the PR that got merged

**Comment by QuickStick123** [comment]
What is it trying to accomplish I assume it is produce a list of parsable mods usable in PoB? I assumed the usage as putting an aurabot's buffs on another character was its primary purpose which the party tab solves.

**Comment by NathanielHinshaw** [comment]
its fairly close, this generates that list of buffs into an item that you can import into other builds, but generation of that item allows you to send a list of your buffs without having a properly un-private profile

in addition, and this might not still be relevant, but previously it was difficult to cycle on and off the buffs in the page, but that may have been fixed in a recent commit (noting it because as a separate "buff" item, you can cycle on or off the socket holding the stat-block

**Comment by Regisle** [comment]
yeah its much easier to cycle now, and it is possible to send the xml culled of almost everything excluding the exported mods if your worried about build being leaked, though doing that requires a bit of effort

you could also just copy the mods from the advanced view though and they can paste it in (and click rebuild) but thats 2-5 copy/pastes instead of 1

**Comment by NathanielHinshaw** [comment]
assuming that's true, then I agree, no need for this given some sort of culled XML support, as well as a means to cycle the buffs on/off, well done! @Regisle 

I personally run a public profile, but I know a ton of aura-supports the were using this PR don't

**Comment by QuickStick123** [comment]
Yeah there could probably be some improvements made to get your one click export kinda thing working again so feel free to open another PR working on updating the party tab to do this or any other improvements you feel are appropriate.

**Comment by NathanielHinshaw** [comment]
for sure, thanks for all the work y'all do!

**Pull request closed without merging**
