### PR TITLE
Added 2 new Spectre types

### PR DESCRIPTION
**Pull request by bsthomsen**
Hey,
I've added 2 new spectre types:
- Redemption Sentry
- Baranite Thaumaturge

Would love some help with adding the correct mods etc so they are calculated correctly.

poedb links:
https://poedb.tw/us/mon.php?n=Redemption+Sentry
https://poedb.tw/us/mon.php?n=Baranite+Thaumaturge

### CODE REVIEW

**Comment by dclamage** [comment]
Can you explain why you changed "Barrage Support" to be just "Barrage"?

"Barrage" is the active skill gem: https://pathofexile.gamepedia.com/Barrage
"Barrage Support" is the support gem: https://pathofexile.gamepedia.com/Barrage_Support

**Comment by ppoelzl** [comment]
Probably just an accidential change from running the exporter. But yeah, revert this please.

**Comment by bsthomsen** [comment]
I'll fix it, no worries. I didn't touch the barrage skill, however it seems someone have made changes inconsistently with the export. Because I just ran the export and it was renamed.

**Comment by ppoelzl** [comment]
Even if there were something wrong with the exported data, your PR is not the place to fix it.

**Comment by bsthomsen** [comment]
I get that, however it seems like the txt file contains the correct for naming it "Barrage Support". However while exporting it, the skill is only named "Barrage". Not sure if people manually changed the lua files? I can just cherry pick and remove the changes my commits do to it.

**Comment by bsthomsen** [comment]
@dclamage & @ppoelzl I've updated the commit without the other changes.

**Comment by ppoelzl** [comment]
@bsthomsen Could you please change the target branch to dev? I've missed that.

**Comment by bsthomsen** [comment]
@ppoelzl I can't because someone already merged it into dev. :)

**Pull request merged**
