### PR TITLE
Added Impale Damage to Combined Total Damage 

### PR DESCRIPTION
**Pull request by ALT-F-X**
Added logic to update output.CombinedAvg with Impale damage

### CODE REVIEW

**Comment by ALT-F-X** [comment]
#2322

**Comment by Helyos96** [comment]
I noticed this a few days ago when vulnerability would add chance to bleed and mess up the EQ Aftershock combined total damage. I tested your PR and it fixes it nicely, thanks. Haven't tested other cases referenced in your commits though (dot, non-impale).

**Comment by Nostrademous** [comment]
@ALT-F-X i assume this fixes #1188?

**Comment by ALT-F-X** [comment]
Yeah without testing it I can confirm this is fixing that problem.

The logic I added with this PR is: 

1. Impale existing is no longer considered if we show "Average Combined Damage". This is so we don't have duplicate information with "Damage Inc. Impale" when there isn't a DOT present.

2. Impale damage is now included in "Average Combined Damage".

I can't foresee this breaking anything considering how simple my changes are.

**Comment by Nostrademous** [comment]
Fixes #1188

**Comment by ppoelzl** [comment]
```lua
(o.WithImpaleDPS or 1) == true
```
always evaluates to `true`:
`true or 1` => `true` == `true`
`false or 1` => `1` == `true`
`nil or 1` => `1` == `true`
Simply leave out the impale output in the comparison instead.

**Review by ppoelzl — CHANGES_REQUESTED** [review]
```lua
(o.WithImpaleDPS or 1) == true
```
always evaluates to `true`:
`true or 1` => `true` == `true`
`false or 1` => `1` == `true`
`nil or 1` => `1` == `true`
Simply leave out the impale output in the comparison instead.

**Comment by ALT-F-X** [comment]
This was intended to visually show impale damage was being included in `CombinedAvg`.

**Review by ppoelzl — COMMENTED** [review]
It's better to just leave this out imo.

**Review by ppoelzl — APPROVED** [review]
LGTM now.

**Pull request merged**
