### PR TITLE
Add full support for Close Combat

### PR DESCRIPTION
**Pull request by PJacek**
Before, Close Combat would not add it's own mods if used with incompatible weapons but still allowed the skill to be used. Now, it disables the weapons.
The change to buff calculation in `CalcPerform` is needed for Combat Rush Effect. I think the mod db switch based on `activeSkillBuff` is there to stop generic `BuffEffect` from bleeding into buffs granted by support gems. It should be fine to change it for named effects.

### CODE REVIEW

**Review by ppoelzl — CHANGES_REQUESTED** [review]
I'd like the usage restriction to be more generic, so that it works with all support gems.
A quick grep through the code base reveals at least two more gems with usage restrictions:
* Barrage Support
* Close Combat Support
* Nightblade Support

Ever ything else looks good. It took me a while to figure out, but I get why the buff calcululations have to be changed.

**Comment by PJacek** [comment]
I changed the implementation to reuse existing logic. There is loss of flexibility because of not using the mod system but you only need to specify the required weapon types and it'll work for any support.

**Review by ppoelzl — CHANGES_REQUESTED** [review]
You should be able to drop the weapon condition mods on Barrage Support as well.

**Comment by Wires77** [comment]
Actually, taking a look at this, we can export the weapon types, too.  They live in GrantedEffects.RequireUsableWith

**Comment by PJacek** [comment]
Yeah, I've been working on this already. The special Varunastra logic needs to be adjusted. It says it counts as all weapon types but in reality it's all *active skill* weapon types. So for example both Viper Strike and Shockwave Support can be used while holding Varunastra but Viper Strike still can't be supported by Shockwave. It could probably be handled at the gem linking stage

**Pull request merged**
