### PR TITLE
Add handling for Doedre's Skin ignore curse limit mod

### PR DESCRIPTION
**Pull request by andrewbelu**

### CODE REVIEW

**Comment by andrewbelu** [comment]
Testing done: added Elemental Weakness and Enfeeble before and after curses socketed in Doedre's Skin, respectively. Added curses in Doedre's Skin. All curses in Doedre's skin were applied. and only one of Elemental Weakness/Enfeeble was applied. Increasing curse limit applied Enfeeble. Adding a mark into Doedre's Skin applied to the curse limit.

**Comment by pundm** [comment]
I checked this out, as i play with this armor at least once a league. It looks really nice!

PoB for testing purposes: https://pastebin.com/fTUGPWQu

**Review by Nostrademous — APPROVED** [review]

**Comment by Nostrademous** [comment]
LGTM, nicely done

**Comment by darkon76** [comment]
Doedre's skin has That support has 25% reduced Effect of Supported Curses.

The pob numbers will be inflated because the change doesn't apply the effect reduction.

**Comment by andrewbelu** [comment]
> Doedre's skin has That support has 25% reduced Effect of Supported Curses.
> 
> The pob numbers will be inflated because the change doesn't apply the effect reduction.

This use case is already handled. See the following block in Data/Skills/other.lua

```
skills["SupportCursePillarTriggerCurses"] = {
	name = "Doedre's Effigy",
	hidden = true,
	color = 4,
	support = true,
	requireSkillTypes = { SkillType.AppliesCurse, SkillType.Hex, SkillType.AND, },
	addSkillTypes = { SkillType.TriggeredGrantedSkill, SkillType.Area, SkillType.Aura, SkillType.AuraDebuff, },
	excludeSkillTypes = { SkillType.Totem, SkillType.Mine, SkillType.Trap, },
	ignoreMinionTypes = true,
	statDescriptionScope = "gem_stat_descriptions",
	fromItem = true,
	baseMods = {
		skill("manaCostForced", 0),
	},
	qualityStats = {
	},
	stats = {
		"skill_has_trigger_from_unique_item",
		"number_of_additional_curses_allowed",
		"curse_effect_+%",
	},
	levels = {
		[20] = { 1, 12, -25, levelRequirement = 70, statInterpolation = { 1, 1, 1, }, },
	},
}
```

You can test it yourself by socketing a gem in the armour, and seeing that it is less effective when socketed in the body slot with Doedre's Skin equipped.

**Comment by andrewbelu** [comment]
Upon inspection, there was a bug where if the same curse was socketed multiple times in Doedre's Skin it would continue adding it's effects. I've updated the code to make sure that no longer happens.

**Review by Wires77 — APPROVED** [review]
Odd issue with this build: https://pastebin.com/yqJBXFb6

Increased Physical damage taken stat from Vulnerability:

- Vulnerability on Doedre's Skin: 29% ✔️ 
- Vulnerability on The Deep One's Hide: 36% ✔️ 
- Vulnerability with both items: 37% ❌ 

I believe it's adding the curse effects together, even though they're from different sources.  Looks like this is a pre-existing issue for curses in general, though (#1774 ) so this looks good to me otherwise.

**Pull request merged**
